//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: setup_attempt
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Setup {
    /// A SetupAttempt describes one attempted confirmation of a SetupIntent, whether that confirmation is successful or unsuc…
    public struct Attempt: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// The value of application on the SetupIntent at the time of this confirmation.
        @Expandable<Stripe.Shared.Application, String> public var application: String?
        /// If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
        public var attachToSelf: Bool?
        /// Time at which the object was created.
        public var created: Date?
        /// The value of customer on the SetupIntent at the time of this confirmation.
        @Expandable<Stripe.Customers.Customer, String> public var customer: String?
        /// The value of customer_account on the SetupIntent at the time of this confirmation.
        public var customerAccount: String?
        /// Indicates the directions of money movement for which this payment method is intended to be used.
        public var flowDirections: [FlowDirections]?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// The value of on_behalf_of on the SetupIntent at the time of this confirmation.
        @Expandable<Stripe.Connect.Account, String> public var onBehalfOf: String?
        /// ID of the payment method used with this SetupAttempt.
        @Expandable<Stripe.PaymentMethods.PaymentMethod, String> public var paymentMethod: String?
        public var paymentMethodDetails: PaymentMethodDetails?
        /// The error encountered during this attempt to confirm the SetupIntent, if any.
        public var setupError: Stripe.Shared.ApiErrors?
        /// ID of the SetupIntent that this attempt belongs to.
        @Expandable<Stripe.Setup.Intent, String> public var setupIntent: String?
        /// Status of this SetupAttempt, one of `requires_confirmation`, `requires_action`, `processing`, `succeeded`, `failed`, o…
        public var status: String?
        /// The value of usage on the SetupIntent at the time of this confirmation, one of `off_session` or `on_session`.
        public var usage: String?

        public init(
            id: ID,
            object: String,
            application: String? = nil,
            attachToSelf: Bool? = nil,
            created: Date? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            flowDirections: [FlowDirections]? = nil,
            livemode: Bool? = nil,
            onBehalfOf: String? = nil,
            paymentMethod: String? = nil,
            paymentMethodDetails: PaymentMethodDetails? = nil,
            setupError: Stripe.Shared.ApiErrors? = nil,
            setupIntent: String? = nil,
            status: String? = nil,
            usage: String? = nil
        ) {
            self.id = id
            self.object = object
            self._application = Expandable(id: application)
            self.attachToSelf = attachToSelf
            self.created = created
            self._customer = Expandable(id: customer)
            self.customerAccount = customerAccount
            self.flowDirections = flowDirections
            self.livemode = livemode
            self._onBehalfOf = Expandable(id: onBehalfOf)
            self._paymentMethod = Expandable(id: paymentMethod)
            self.paymentMethodDetails = paymentMethodDetails
            self.setupError = setupError
            self._setupIntent = Expandable(id: setupIntent)
            self.status = status
            self.usage = usage
        }

        public enum FlowDirections: String, Codable, Hashable, Sendable {
            case inbound
            case outbound
        }

        public struct PaymentMethodDetails: Codable, Hashable, Sendable {
            /// The type of the payment method used in the SetupIntent (e.g., `card`).
            public var `type`: String?
            /// The payload `type` selects.
            public var details: Details

            fileprivate enum CodingKeys: String, CodingKey {
                case `type`
                case acssDebit
                case amazonPay
                case auBecsDebit
                case bacsDebit
                case bancontact
                case boleto
                case card
                case cardPresent
                case cashapp
                case ideal
                case kakaoPay
                case klarna
                case krCard
                case link
                case naverPay
                case nzBankAccount
                case paypal
                case payto
                case pix
                case revolutPay
                case satispay
                case sepaDebit
                case sofort
                case twint
                case upi
                case usBankAccount
            }

            public init(
                `type`: String? = nil,
                details: Details
            ) {
                self.`type` = `type`
                self.details = details
            }

            public init(from decoder: any Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.`type` = try container.decodeIfPresent(String.self, forKey: .`type`)
                self.details = try Details(type: try container.decodeIfPresent(String.self, forKey: .type) ?? "", from: container)
            }

            public func encode(to encoder: any Encoder) throws {
                var container = encoder.container(keyedBy: CodingKeys.self)
                try container.encodeIfPresent(`type`, forKey: .`type`)
                try details.encode(into: &container)
            }

            public struct AcssDebit: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct AmazonPay: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct AuBecsDebit: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct BacsDebit: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Bancontact: Codable, Hashable, Sendable {
                /// Bank code of bank associated with the bank account.
                public var bankCode: String?
                /// Name of the bank associated with the bank account.
                public var bankName: String?
                /// Bank Identifier Code of the bank associated with the bank account.
                public var bic: String?
                /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
                @Expandable<Stripe.PaymentMethods.PaymentMethod, String> public var generatedSepaDebit: String?
                /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
                @Expandable<Stripe.Mandates.Mandate, String> public var generatedSepaDebitMandate: String?
                /// Last four characters of the IBAN.
                public var ibanLast4: String?
                /// Preferred language of the Bancontact authorization page that the customer is redirected to.
                public var preferredLanguage: PreferredLanguage?
                /// Owner's verified full name.
                public var verifiedName: String?

                public init(
                    bankCode: String? = nil,
                    bankName: String? = nil,
                    bic: String? = nil,
                    generatedSepaDebit: String? = nil,
                    generatedSepaDebitMandate: String? = nil,
                    ibanLast4: String? = nil,
                    preferredLanguage: PreferredLanguage? = nil,
                    verifiedName: String? = nil
                ) {
                    self.bankCode = bankCode
                    self.bankName = bankName
                    self.bic = bic
                    self._generatedSepaDebit = Expandable(id: generatedSepaDebit)
                    self._generatedSepaDebitMandate = Expandable(id: generatedSepaDebitMandate)
                    self.ibanLast4 = ibanLast4
                    self.preferredLanguage = preferredLanguage
                    self.verifiedName = verifiedName
                }

                /// Preferred language of the Bancontact authorization page that the customer is redirected to.
                public enum PreferredLanguage: String, Codable, Hashable, Sendable {
                    case de
                    case en
                    case fr
                    case nl
                }
            }

            public struct Boleto: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Card: Codable, Hashable, Sendable {
                /// Card brand.
                public var brand: String?
                /// Check results by Card networks on Card address and CVC at the time of authorization
                public var checks: Checks?
                /// Two-letter ISO code representing the country of the card.
                public var country: String?
                /// A high-level description of the type of cards issued in this range.
                public var description: String?
                /// Two-digit number representing the card's expiration month.
                public var expMonth: Int?
                /// Four-digit number representing the card's expiration year.
                public var expYear: Int?
                /// Uniquely identifies this particular card number.
                public var fingerprint: String?
                /// Card funding type.
                public var funding: String?
                /// Issuer identification number of the card.
                public var iin: String?
                /// The name of the card's issuing bank.
                public var issuer: String?
                /// The last four digits of the card.
                public var last4: String?
                /// True if this payment was marked as MOTO and out of scope for SCA.
                public var moto: Bool?
                /// Identifies which network this charge was processed on.
                public var network: String?
                /// Populated if this authorization used 3D Secure authentication.
                public var threeDSecure: ThreeDSecure?
                /// If this Card is part of a card wallet, this contains the details of the card wallet.
                public var wallet: Wallet?

                public init(
                    brand: String? = nil,
                    checks: Checks? = nil,
                    country: String? = nil,
                    description: String? = nil,
                    expMonth: Int? = nil,
                    expYear: Int? = nil,
                    fingerprint: String? = nil,
                    funding: String? = nil,
                    iin: String? = nil,
                    issuer: String? = nil,
                    last4: String? = nil,
                    moto: Bool? = nil,
                    network: String? = nil,
                    threeDSecure: ThreeDSecure? = nil,
                    wallet: Wallet? = nil
                ) {
                    self.brand = brand
                    self.checks = checks
                    self.country = country
                    self.description = description
                    self.expMonth = expMonth
                    self.expYear = expYear
                    self.fingerprint = fingerprint
                    self.funding = funding
                    self.iin = iin
                    self.issuer = issuer
                    self.last4 = last4
                    self.moto = moto
                    self.network = network
                    self.threeDSecure = threeDSecure
                    self.wallet = wallet
                }

                public struct Checks: Codable, Hashable, Sendable {
                    /// If a address line1 was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
                    public var addressLine1Check: String?
                    /// If a address postal code was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
                    public var addressPostalCodeCheck: String?
                    /// If a CVC was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
                    public var cvcCheck: String?

                    public init(
                        addressLine1Check: String? = nil,
                        addressPostalCodeCheck: String? = nil,
                        cvcCheck: String? = nil
                    ) {
                        self.addressLine1Check = addressLine1Check
                        self.addressPostalCodeCheck = addressPostalCodeCheck
                        self.cvcCheck = cvcCheck
                    }
                }

                public struct ThreeDSecure: Codable, Hashable, Sendable {
                    /// For authenticated transactions: how the customer was authenticated by the issuing bank.
                    public var authenticationFlow: AuthenticationFlow?
                    /// The Electronic Commerce Indicator (ECI).
                    public var electronicCommerceIndicator: ElectronicCommerceIndicator?
                    /// Indicates the outcome of 3D Secure authentication.
                    public var result: Result?
                    /// Additional information about why 3D Secure succeeded or failed based on the `result`.
                    public var resultReason: ResultReason?
                    /// The 3D Secure 1 XID or 3D Secure 2 Directory Server Transaction ID (dsTransId) for this payment.
                    public var transactionId: String?
                    /// The version of 3D Secure that was used.
                    public var version: Version?

                    public init(
                        authenticationFlow: AuthenticationFlow? = nil,
                        electronicCommerceIndicator: ElectronicCommerceIndicator? = nil,
                        result: Result? = nil,
                        resultReason: ResultReason? = nil,
                        transactionId: String? = nil,
                        version: Version? = nil
                    ) {
                        self.authenticationFlow = authenticationFlow
                        self.electronicCommerceIndicator = electronicCommerceIndicator
                        self.result = result
                        self.resultReason = resultReason
                        self.transactionId = transactionId
                        self.version = version
                    }

                    /// For authenticated transactions: how the customer was authenticated by the issuing bank.
                    public enum AuthenticationFlow: String, Codable, Hashable, Sendable {
                        case challenge
                        case frictionless
                    }

                    /// The Electronic Commerce Indicator (ECI).
                    public enum ElectronicCommerceIndicator: String, Codable, Hashable, Sendable {
                        case value01 = "01"
                        case value02 = "02"
                        case value05 = "05"
                        case value06 = "06"
                        case value07 = "07"
                    }

                    /// Indicates the outcome of 3D Secure authentication.
                    public enum Result: String, Codable, Hashable, Sendable {
                        case attemptAcknowledged = "attempt_acknowledged"
                        case authenticated
                        case dataShareOnly = "data_share_only"
                        case exempted
                        case failed
                        case notSupported = "not_supported"
                        case processingError = "processing_error"
                    }

                    /// Additional information about why 3D Secure succeeded or failed based on the `result`.
                    public enum ResultReason: String, Codable, Hashable, Sendable {
                        case abandoned
                        case bypassed
                        case canceled
                        case cardNotEnrolled = "card_not_enrolled"
                        case networkNotSupported = "network_not_supported"
                        case protocolError = "protocol_error"
                        case rejected
                    }

                    /// The version of 3D Secure that was used.
                    public enum Version: String, Codable, Hashable, Sendable {
                        case value1_0_2 = "1.0.2"
                        case value2_1_0 = "2.1.0"
                        case value2_2_0 = "2.2.0"
                        case value2_3_0 = "2.3.0"
                        case value2_3_1 = "2.3.1"
                    }
                }

                public struct Wallet: Codable, Hashable, Sendable {
                    public var applePay: Stripe.Shared.ApplePay?
                    public var googlePay: Stripe.Shared.GooglePay?
                    /// The type of the card wallet, one of `apple_pay`, `google_pay`, or `link`.
                    public var `type`: Type?

                    public init(
                        applePay: Stripe.Shared.ApplePay? = nil,
                        googlePay: Stripe.Shared.GooglePay? = nil,
                        `type`: Type? = nil
                    ) {
                        self.applePay = applePay
                        self.googlePay = googlePay
                        self.`type` = `type`
                    }

                    /// The type of the card wallet, one of `apple_pay`, `google_pay`, or `link`.
                    public enum `Type`: String, Codable, Hashable, Sendable {
                        case applePay = "apple_pay"
                        case googlePay = "google_pay"
                        case link
                    }
                }
            }

            public struct CardPresent: Codable, Hashable, Sendable {
                /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
                @Expandable<Stripe.PaymentMethods.PaymentMethod, String> public var generatedCard: String?
                /// Details about payments collected offline.
                public var offline: Stripe.Shared.Offline?

                public init(
                    generatedCard: String? = nil,
                    offline: Stripe.Shared.Offline? = nil
                ) {
                    self._generatedCard = Expandable(id: generatedCard)
                    self.offline = offline
                }
            }

            public struct Cashapp: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Ideal: Codable, Hashable, Sendable {
                /// The customer's bank.
                public var bank: Bank?
                /// The Bank Identifier Code of the customer's bank.
                public var bic: Bic?
                /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
                @Expandable<Stripe.PaymentMethods.PaymentMethod, String> public var generatedSepaDebit: String?
                /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
                @Expandable<Stripe.Mandates.Mandate, String> public var generatedSepaDebitMandate: String?
                /// Last four characters of the IBAN.
                public var ibanLast4: String?
                /// Owner's verified full name.
                public var verifiedName: String?

                public init(
                    bank: Bank? = nil,
                    bic: Bic? = nil,
                    generatedSepaDebit: String? = nil,
                    generatedSepaDebitMandate: String? = nil,
                    ibanLast4: String? = nil,
                    verifiedName: String? = nil
                ) {
                    self.bank = bank
                    self.bic = bic
                    self._generatedSepaDebit = Expandable(id: generatedSepaDebit)
                    self._generatedSepaDebitMandate = Expandable(id: generatedSepaDebitMandate)
                    self.ibanLast4 = ibanLast4
                    self.verifiedName = verifiedName
                }

                /// The customer's bank.
                public enum Bank: String, Codable, Hashable, Sendable {
                    case abnAmro = "abn_amro"
                    case adyen
                    case asnBank = "asn_bank"
                    case bunq
                    case buut
                    case finom
                    case handelsbanken
                    case ing
                    case knab
                    case mollie
                    case moneyou
                    case n26
                    case nn
                    case rabobank
                    case regiobank
                    case revolut
                    case snsBank = "sns_bank"
                    case triodosBank = "triodos_bank"
                    case vanLanschot = "van_lanschot"
                    case yoursafe
                }

                /// The Bank Identifier Code of the customer's bank.
                public enum Bic: String, Codable, Hashable, Sendable {
                    case ABNANL2A
                    case ADYBNL2A
                    case ASNBNL21
                    case BITSNL2A
                    case BUNQNL2A
                    case BUUTNL2A
                    case FNOMNL22
                    case FVLBNL22
                    case HANDNL2A
                    case INGBNL2A
                    case KNABNL2H
                    case MLLENL2A
                    case MOYONL21
                    case NNBANL2G
                    case NTSBDEB1
                    case RABONL2U
                    case RBRBNL21
                    case REVOIE23
                    case REVOLT21
                    case SNSBNL2A
                    case TRIONL2U
                }
            }

            public struct KakaoPay: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Klarna: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct KrCard: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Link: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct NaverPay: Codable, Hashable, Sendable {
                /// Uniquely identifies this particular Naver Pay account.
                public var buyerId: String?

                public init(
                    buyerId: String? = nil
                ) {
                    self.buyerId = buyerId
                }
            }

            public struct NzBankAccount: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Paypal: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Payto: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Pix: Codable, Hashable, Sendable {
                /// Uniquely identifies this particular Pix account.
                public var fingerprint: String?

                public init(
                    fingerprint: String? = nil
                ) {
                    self.fingerprint = fingerprint
                }
            }

            public struct RevolutPay: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Satispay: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct SepaDebit: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Sofort: Codable, Hashable, Sendable {
                /// Bank code of bank associated with the bank account.
                public var bankCode: String?
                /// Name of the bank associated with the bank account.
                public var bankName: String?
                /// Bank Identifier Code of the bank associated with the bank account.
                public var bic: String?
                /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
                @Expandable<Stripe.PaymentMethods.PaymentMethod, String> public var generatedSepaDebit: String?
                /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
                @Expandable<Stripe.Mandates.Mandate, String> public var generatedSepaDebitMandate: String?
                /// Last four characters of the IBAN.
                public var ibanLast4: String?
                /// Preferred language of the Sofort authorization page that the customer is redirected to.
                public var preferredLanguage: PreferredLanguage?
                /// Owner's verified full name.
                public var verifiedName: String?

                public init(
                    bankCode: String? = nil,
                    bankName: String? = nil,
                    bic: String? = nil,
                    generatedSepaDebit: String? = nil,
                    generatedSepaDebitMandate: String? = nil,
                    ibanLast4: String? = nil,
                    preferredLanguage: PreferredLanguage? = nil,
                    verifiedName: String? = nil
                ) {
                    self.bankCode = bankCode
                    self.bankName = bankName
                    self.bic = bic
                    self._generatedSepaDebit = Expandable(id: generatedSepaDebit)
                    self._generatedSepaDebitMandate = Expandable(id: generatedSepaDebitMandate)
                    self.ibanLast4 = ibanLast4
                    self.preferredLanguage = preferredLanguage
                    self.verifiedName = verifiedName
                }

                /// Preferred language of the Sofort authorization page that the customer is redirected to.
                public enum PreferredLanguage: String, Codable, Hashable, Sendable {
                    case de
                    case en
                    case fr
                    case nl
                }
            }

            public struct Twint: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Upi: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct UsBankAccount: Codable, Hashable, Sendable {
                public init() {}
            }

            /// The payload `type` selects; `unknown` carries a type this package does not model.
            public indirect enum Details: Hashable, Sendable {
                case acssDebit(AcssDebit)
                case amazonPay(AmazonPay)
                case auBecsDebit(AuBecsDebit)
                case bacsDebit(BacsDebit)
                case bancontact(Bancontact)
                case boleto(Boleto)
                case card(Card)
                case cardPresent(CardPresent)
                case cashapp(Cashapp)
                case ideal(Ideal)
                case kakaoPay(KakaoPay)
                case klarna(Klarna)
                case krCard(KrCard)
                case link(Link)
                case naverPay(NaverPay)
                case nzBankAccount(NzBankAccount)
                case paypal(Paypal)
                case payto(Payto)
                case pix(Pix)
                case revolutPay(RevolutPay)
                case satispay(Satispay)
                case sepaDebit(SepaDebit)
                case sofort(Sofort)
                case twint(Twint)
                case upi(Upi)
                case usBankAccount(UsBankAccount)
                case unknown(type: String)

                public var acssDebit: AcssDebit? { if case .acssDebit(let value) = self { return value }; return nil }
                public var amazonPay: AmazonPay? { if case .amazonPay(let value) = self { return value }; return nil }
                public var auBecsDebit: AuBecsDebit? { if case .auBecsDebit(let value) = self { return value }; return nil }
                public var bacsDebit: BacsDebit? { if case .bacsDebit(let value) = self { return value }; return nil }
                public var bancontact: Bancontact? { if case .bancontact(let value) = self { return value }; return nil }
                public var boleto: Boleto? { if case .boleto(let value) = self { return value }; return nil }
                public var card: Card? { if case .card(let value) = self { return value }; return nil }
                public var cardPresent: CardPresent? { if case .cardPresent(let value) = self { return value }; return nil }
                public var cashapp: Cashapp? { if case .cashapp(let value) = self { return value }; return nil }
                public var ideal: Ideal? { if case .ideal(let value) = self { return value }; return nil }
                public var kakaoPay: KakaoPay? { if case .kakaoPay(let value) = self { return value }; return nil }
                public var klarna: Klarna? { if case .klarna(let value) = self { return value }; return nil }
                public var krCard: KrCard? { if case .krCard(let value) = self { return value }; return nil }
                public var link: Link? { if case .link(let value) = self { return value }; return nil }
                public var naverPay: NaverPay? { if case .naverPay(let value) = self { return value }; return nil }
                public var nzBankAccount: NzBankAccount? { if case .nzBankAccount(let value) = self { return value }; return nil }
                public var paypal: Paypal? { if case .paypal(let value) = self { return value }; return nil }
                public var payto: Payto? { if case .payto(let value) = self { return value }; return nil }
                public var pix: Pix? { if case .pix(let value) = self { return value }; return nil }
                public var revolutPay: RevolutPay? { if case .revolutPay(let value) = self { return value }; return nil }
                public var satispay: Satispay? { if case .satispay(let value) = self { return value }; return nil }
                public var sepaDebit: SepaDebit? { if case .sepaDebit(let value) = self { return value }; return nil }
                public var sofort: Sofort? { if case .sofort(let value) = self { return value }; return nil }
                public var twint: Twint? { if case .twint(let value) = self { return value }; return nil }
                public var upi: Upi? { if case .upi(let value) = self { return value }; return nil }
                public var usBankAccount: UsBankAccount? { if case .usBankAccount(let value) = self { return value }; return nil }

                fileprivate init(type: String, from container: KeyedDecodingContainer<CodingKeys>) throws {
                    switch type {
                    case "acss_debit":
                        if let value = try container.decodeIfPresent(AcssDebit.self, forKey: .acssDebit) { self = .acssDebit(value) } else { self = .unknown(type: type) }
                    case "amazon_pay":
                        if let value = try container.decodeIfPresent(AmazonPay.self, forKey: .amazonPay) { self = .amazonPay(value) } else { self = .unknown(type: type) }
                    case "au_becs_debit":
                        if let value = try container.decodeIfPresent(AuBecsDebit.self, forKey: .auBecsDebit) { self = .auBecsDebit(value) } else { self = .unknown(type: type) }
                    case "bacs_debit":
                        if let value = try container.decodeIfPresent(BacsDebit.self, forKey: .bacsDebit) { self = .bacsDebit(value) } else { self = .unknown(type: type) }
                    case "bancontact":
                        if let value = try container.decodeIfPresent(Bancontact.self, forKey: .bancontact) { self = .bancontact(value) } else { self = .unknown(type: type) }
                    case "boleto":
                        if let value = try container.decodeIfPresent(Boleto.self, forKey: .boleto) { self = .boleto(value) } else { self = .unknown(type: type) }
                    case "card":
                        if let value = try container.decodeIfPresent(Card.self, forKey: .card) { self = .card(value) } else { self = .unknown(type: type) }
                    case "card_present":
                        if let value = try container.decodeIfPresent(CardPresent.self, forKey: .cardPresent) { self = .cardPresent(value) } else { self = .unknown(type: type) }
                    case "cashapp":
                        if let value = try container.decodeIfPresent(Cashapp.self, forKey: .cashapp) { self = .cashapp(value) } else { self = .unknown(type: type) }
                    case "ideal":
                        if let value = try container.decodeIfPresent(Ideal.self, forKey: .ideal) { self = .ideal(value) } else { self = .unknown(type: type) }
                    case "kakao_pay":
                        if let value = try container.decodeIfPresent(KakaoPay.self, forKey: .kakaoPay) { self = .kakaoPay(value) } else { self = .unknown(type: type) }
                    case "klarna":
                        if let value = try container.decodeIfPresent(Klarna.self, forKey: .klarna) { self = .klarna(value) } else { self = .unknown(type: type) }
                    case "kr_card":
                        if let value = try container.decodeIfPresent(KrCard.self, forKey: .krCard) { self = .krCard(value) } else { self = .unknown(type: type) }
                    case "link":
                        if let value = try container.decodeIfPresent(Link.self, forKey: .link) { self = .link(value) } else { self = .unknown(type: type) }
                    case "naver_pay":
                        if let value = try container.decodeIfPresent(NaverPay.self, forKey: .naverPay) { self = .naverPay(value) } else { self = .unknown(type: type) }
                    case "nz_bank_account":
                        if let value = try container.decodeIfPresent(NzBankAccount.self, forKey: .nzBankAccount) { self = .nzBankAccount(value) } else { self = .unknown(type: type) }
                    case "paypal":
                        if let value = try container.decodeIfPresent(Paypal.self, forKey: .paypal) { self = .paypal(value) } else { self = .unknown(type: type) }
                    case "payto":
                        if let value = try container.decodeIfPresent(Payto.self, forKey: .payto) { self = .payto(value) } else { self = .unknown(type: type) }
                    case "pix":
                        if let value = try container.decodeIfPresent(Pix.self, forKey: .pix) { self = .pix(value) } else { self = .unknown(type: type) }
                    case "revolut_pay":
                        if let value = try container.decodeIfPresent(RevolutPay.self, forKey: .revolutPay) { self = .revolutPay(value) } else { self = .unknown(type: type) }
                    case "satispay":
                        if let value = try container.decodeIfPresent(Satispay.self, forKey: .satispay) { self = .satispay(value) } else { self = .unknown(type: type) }
                    case "sepa_debit":
                        if let value = try container.decodeIfPresent(SepaDebit.self, forKey: .sepaDebit) { self = .sepaDebit(value) } else { self = .unknown(type: type) }
                    case "sofort":
                        if let value = try container.decodeIfPresent(Sofort.self, forKey: .sofort) { self = .sofort(value) } else { self = .unknown(type: type) }
                    case "twint":
                        if let value = try container.decodeIfPresent(Twint.self, forKey: .twint) { self = .twint(value) } else { self = .unknown(type: type) }
                    case "upi":
                        if let value = try container.decodeIfPresent(Upi.self, forKey: .upi) { self = .upi(value) } else { self = .unknown(type: type) }
                    case "us_bank_account":
                        if let value = try container.decodeIfPresent(UsBankAccount.self, forKey: .usBankAccount) { self = .usBankAccount(value) } else { self = .unknown(type: type) }
                    default: self = .unknown(type: type)
                    }
                }

                fileprivate func encode(into container: inout KeyedEncodingContainer<CodingKeys>) throws {
                    switch self {
                    case .acssDebit(let value): try container.encode(value, forKey: .acssDebit)
                    case .amazonPay(let value): try container.encode(value, forKey: .amazonPay)
                    case .auBecsDebit(let value): try container.encode(value, forKey: .auBecsDebit)
                    case .bacsDebit(let value): try container.encode(value, forKey: .bacsDebit)
                    case .bancontact(let value): try container.encode(value, forKey: .bancontact)
                    case .boleto(let value): try container.encode(value, forKey: .boleto)
                    case .card(let value): try container.encode(value, forKey: .card)
                    case .cardPresent(let value): try container.encode(value, forKey: .cardPresent)
                    case .cashapp(let value): try container.encode(value, forKey: .cashapp)
                    case .ideal(let value): try container.encode(value, forKey: .ideal)
                    case .kakaoPay(let value): try container.encode(value, forKey: .kakaoPay)
                    case .klarna(let value): try container.encode(value, forKey: .klarna)
                    case .krCard(let value): try container.encode(value, forKey: .krCard)
                    case .link(let value): try container.encode(value, forKey: .link)
                    case .naverPay(let value): try container.encode(value, forKey: .naverPay)
                    case .nzBankAccount(let value): try container.encode(value, forKey: .nzBankAccount)
                    case .paypal(let value): try container.encode(value, forKey: .paypal)
                    case .payto(let value): try container.encode(value, forKey: .payto)
                    case .pix(let value): try container.encode(value, forKey: .pix)
                    case .revolutPay(let value): try container.encode(value, forKey: .revolutPay)
                    case .satispay(let value): try container.encode(value, forKey: .satispay)
                    case .sepaDebit(let value): try container.encode(value, forKey: .sepaDebit)
                    case .sofort(let value): try container.encode(value, forKey: .sofort)
                    case .twint(let value): try container.encode(value, forKey: .twint)
                    case .upi(let value): try container.encode(value, forKey: .upi)
                    case .usBankAccount(let value): try container.encode(value, forKey: .usBankAccount)
                    default: break
                    }
                }
            }
        }
    }
}
