//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-stripe open source project
//
// Copyright (c) 2026 the swift-stripe project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
// See NOTICE for attribution of derived work
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Setup {
    /// A SetupIntent guides you through the process of setting up and saving a customer's payment credentials for future.
    public struct Intent: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// The list of payment method types to allow for this SetupIntent.
        public var allowedPaymentMethodTypes: [AllowedPaymentMethodTypes]?
        /// ID of the Connect application that created the SetupIntent.
        @Expandable<Stripe.Shared.Application, String> public var application: String?
        /// If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
        public var attachToSelf: Bool?
        /// Settings for dynamic payment methods compatible with this Setup Intent.
        public var automaticPaymentMethods: AutomaticPaymentMethods?
        /// Reason for cancellation of this SetupIntent, one of `abandoned`, `requested_by_customer`, or `duplicate`.
        public var cancellationReason: CancellationReason?
        /// The client secret of this SetupIntent.
        public var clientSecret: String?
        /// Time at which the object was created.
        public var created: Date?
        /// ID of the Customer this SetupIntent belongs to, if one exists.
        @Expandable<Stripe.Customers.Customer, String> public var customer: String?
        /// ID of the Account this SetupIntent belongs to, if one exists.
        public var customerAccount: String?
        /// An arbitrary string attached to the object.
        public var description: String?
        /// Payment method types that are excluded from this SetupIntent.
        public var excludedPaymentMethodTypes: [ExcludedPaymentMethodTypes]?
        /// Indicates the directions of money movement for which this payment method is intended to be used.
        public var flowDirections: [FlowDirections]?
        /// The error encountered in the previous SetupIntent confirmation.
        public var lastSetupError: Stripe.Shared.ApiErrors?
        /// The most recent SetupAttempt for this SetupIntent.
        @Expandable<Stripe.Setup.Attempt, String> public var latestAttempt: String?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        public var managedPayments: Stripe.Shared.SmorResourceManagedPayments?
        /// ID of the multi use Mandate generated by the SetupIntent.
        @Expandable<Stripe.Mandates.Mandate, String> public var mandate: String?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?
        /// If present, this property tells you what actions you need to take in order for your customer to continue payment.
        public var nextAction: NextAction?
        /// The account (if any) for which the setup is intended.
        @Expandable<Stripe.Connect.Account, String> public var onBehalfOf: String?
        /// ID of the payment method used with this SetupIntent.
        @Expandable<Stripe.PaymentMethods.PaymentMethod, String> public var paymentMethod: String?
        /// Information about the payment method configuration used for this Setup Intent.
        public var paymentMethodConfigurationDetails: Stripe.Shared.PaymentMethodConfigurationDetails?
        /// Payment method-specific configuration for this SetupIntent.
        public var paymentMethodOptions: PaymentMethodOptions?
        /// The list of payment method types (e.g.
        public var paymentMethodTypes: [String]?
        /// ID of the single_use Mandate generated by the SetupIntent.
        @Expandable<Stripe.Mandates.Mandate, String> public var singleUseMandate: String?
        /// Status of this SetupIntent, one of `requires_payment_method`, `requires_confirmation`, `requires_action`.
        public var status: Status?
        /// Indicates how the payment method is intended to be used in the future.
        public var usage: String?

        public init(
            id: ID,
            object: String,
            allowedPaymentMethodTypes: [AllowedPaymentMethodTypes]? = nil,
            application: String? = nil,
            attachToSelf: Bool? = nil,
            automaticPaymentMethods: AutomaticPaymentMethods? = nil,
            cancellationReason: CancellationReason? = nil,
            clientSecret: String? = nil,
            created: Date? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            description: String? = nil,
            excludedPaymentMethodTypes: [ExcludedPaymentMethodTypes]? = nil,
            flowDirections: [FlowDirections]? = nil,
            lastSetupError: Stripe.Shared.ApiErrors? = nil,
            latestAttempt: String? = nil,
            livemode: Bool? = nil,
            managedPayments: Stripe.Shared.SmorResourceManagedPayments? = nil,
            mandate: String? = nil,
            metadata: [String: String]? = nil,
            nextAction: NextAction? = nil,
            onBehalfOf: String? = nil,
            paymentMethod: String? = nil,
            paymentMethodConfigurationDetails: Stripe.Shared.PaymentMethodConfigurationDetails? = nil,
            paymentMethodOptions: PaymentMethodOptions? = nil,
            paymentMethodTypes: [String]? = nil,
            singleUseMandate: String? = nil,
            status: Status? = nil,
            usage: String? = nil
        ) {
            self.id = id
            self.object = object
            self.allowedPaymentMethodTypes = allowedPaymentMethodTypes
            self._application = Expandable(id: application)
            self.attachToSelf = attachToSelf
            self.automaticPaymentMethods = automaticPaymentMethods
            self.cancellationReason = cancellationReason
            self.clientSecret = clientSecret
            self.created = created
            self._customer = Expandable(id: customer)
            self.customerAccount = customerAccount
            self.description = description
            self.excludedPaymentMethodTypes = excludedPaymentMethodTypes
            self.flowDirections = flowDirections
            self.lastSetupError = lastSetupError
            self._latestAttempt = Expandable(id: latestAttempt)
            self.livemode = livemode
            self.managedPayments = managedPayments
            self._mandate = Expandable(id: mandate)
            self.metadata = metadata
            self.nextAction = nextAction
            self._onBehalfOf = Expandable(id: onBehalfOf)
            self._paymentMethod = Expandable(id: paymentMethod)
            self.paymentMethodConfigurationDetails = paymentMethodConfigurationDetails
            self.paymentMethodOptions = paymentMethodOptions
            self.paymentMethodTypes = paymentMethodTypes
            self._singleUseMandate = Expandable(id: singleUseMandate)
            self.status = status
            self.usage = usage
        }

        public enum AllowedPaymentMethodTypes: String, Codable, Hashable, Sendable {
            case acssDebit = "acss_debit"
            case affirm
            case afterpayClearpay = "afterpay_clearpay"
            case alipay
            case alma
            case amazonPay = "amazon_pay"
            case auBecsDebit = "au_becs_debit"
            case bacsDebit = "bacs_debit"
            case bancontact
            case billie
            case bizum
            case blik
            case bokuPromptpay = "boku_promptpay"
            case boleto
            case capchasePay = "capchase_pay"
            case card
            case cashapp
            case checkScan = "check_scan"
            case clickToPay = "click_to_pay"
            case crypto
            case customerBalance = "customer_balance"
            case demoPay = "demo_pay"
            case duitnow
            case dummyAuthPush = "dummy_auth_push"
            case dummyPassthroughCard = "dummy_passthrough_card"
            case edenred
            case eps
            case fpx
            case gcash
            case getbalance
            case giftCard = "gift_card"
            case giropay
            case gopay
            case grabpay
            case idBankTransfer = "id_bank_transfer"
            case ideal
            case kakaoPay = "kakao_pay"
            case klarna
            case knet
            case konbini
            case krCard = "kr_card"
            case krMarket = "kr_market"
            case kriya
            case link
            case mbWay = "mb_way"
            case mobilepay
            case momo
            case mondu
            case multibanco
            case naverPay = "naver_pay"
            case netbanking
            case ngBank = "ng_bank"
            case ngBankTransfer = "ng_bank_transfer"
            case ngCard = "ng_card"
            case ngMarket = "ng_market"
            case ngUssd = "ng_ussd"
            case ngWallet = "ng_wallet"
            case nzBankAccount = "nz_bank_account"
            case octopus
            case oxxo
            case p24
            case paperCheck = "paper_check"
            case payByBank = "pay_by_bank"
            case payco
            case paynow
            case paypal
            case paypay
            case payto
            case pix
            case promptpay
            case qris
            case rechnung
            case revolutPay = "revolut_pay"
            case samsungPay = "samsung_pay"
            case satispay
            case scalapay
            case sepaDebit = "sepa_debit"
            case sequra
            case shopPay = "shop_pay"
            case shopeepay
            case sofort
            case southKoreaMarket = "south_korea_market"
            case stripeBalance = "stripe_balance"
            case sunbit
            case swish
            case tamara
            case testPay = "test_pay"
            case truemoney
            case twint
            case upi
            case usBankAccount = "us_bank_account"
            case usCashVoucher = "us_cash_voucher"
            case vipps
            case wechatPay = "wechat_pay"
            case wero
            case zip
        }

        /// Reason for cancellation of this SetupIntent, one of `abandoned`, `requested_by_customer`, or `duplicate`.
        public enum CancellationReason: String, Codable, Hashable, Sendable {
            case abandoned
            case duplicate
            case requestedByCustomer = "requested_by_customer"
        }

        public enum ExcludedPaymentMethodTypes: String, Codable, Hashable, Sendable {
            case acssDebit = "acss_debit"
            case affirm
            case afterpayClearpay = "afterpay_clearpay"
            case alipay
            case alma
            case amazonPay = "amazon_pay"
            case auBecsDebit = "au_becs_debit"
            case bacsDebit = "bacs_debit"
            case bancontact
            case billie
            case bizum
            case blik
            case boleto
            case card
            case cashapp
            case crypto
            case customerBalance = "customer_balance"
            case eps
            case fpx
            case giropay
            case grabpay
            case ideal
            case kakaoPay = "kakao_pay"
            case klarna
            case konbini
            case krCard = "kr_card"
            case mbWay = "mb_way"
            case mobilepay
            case multibanco
            case naverPay = "naver_pay"
            case nzBankAccount = "nz_bank_account"
            case oxxo
            case p24
            case payByBank = "pay_by_bank"
            case payco
            case paynow
            case paypal
            case payto
            case pix
            case promptpay
            case revolutPay = "revolut_pay"
            case samsungPay = "samsung_pay"
            case satispay
            case scalapay
            case sepaDebit = "sepa_debit"
            case sofort
            case sunbit
            case swish
            case twint
            case upi
            case usBankAccount = "us_bank_account"
            case wechatPay = "wechat_pay"
            case zip
        }

        public enum FlowDirections: String, Codable, Hashable, Sendable {
            case inbound
            case outbound
        }

        /// Status of this SetupIntent, one of `requires_payment_method`, `requires_confirmation`, `requires_action`.
        public enum Status: String, Codable, Hashable, Sendable {
            case canceled
            case processing
            case requiresAction = "requires_action"
            case requiresConfirmation = "requires_confirmation"
            case requiresPaymentMethod = "requires_payment_method"
            case succeeded
        }

        public struct AutomaticPaymentMethods: Codable, Hashable, Sendable {
            /// Controls whether this SetupIntent will accept redirect-based payment methods.
            public var allowRedirects: AllowRedirects?
            /// Automatically calculates compatible payment methods.
            public var enabled: Bool?

            public init(
                allowRedirects: AllowRedirects? = nil,
                enabled: Bool? = nil
            ) {
                self.allowRedirects = allowRedirects
                self.enabled = enabled
            }

            /// Controls whether this SetupIntent will accept redirect-based payment methods.
            public enum AllowRedirects: String, Codable, Hashable, Sendable {
                case always
                case never
            }
        }

        public struct NextAction: Codable, Hashable, Sendable {
            /// Type of the next action to perform.
            public var `type`: String?
            /// The payload `type` selects.
            public var details: Details

            fileprivate enum CodingKeys: String, CodingKey {
                case `type`
                case blikAuthorize
                case cashappHandleRedirectOrDisplayQrCode
                case pixDisplayQrCode
                case redirectToUrl
                case upiHandleRedirectOrDisplayQrCode
                case useStripeSdk
                case verifyWithMicrodeposits
            }

            public init(
                `type`: String? = nil,
                details: Details
            ) {
                self.`type` = `type`
                self.details = details
            }

            public init(from decoder: any Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.`type` = try container.decodeIfPresent(String.self, forKey: .`type`)
                self.details = try Details(type: try container.decodeIfPresent(String.self, forKey: .type) ?? "", from: container)
            }

            public func encode(to encoder: any Encoder) throws {
                var container = encoder.container(keyedBy: CodingKeys.self)
                try container.encodeIfPresent(`type`, forKey: .`type`)
                try details.encode(into: &container)
            }

            public struct PixDisplayQrCode: Codable, Hashable, Sendable {
                /// The raw data string used to generate QR code, it should be used together with QR code library.
                public var data: String?
                /// The date (unix timestamp) when the PIX expires.
                public var expiresAt: Date?
                /// The URL to the hosted pix instructions page, which allows customers to view the pix QR code.
                public var hostedInstructionsUrl: String?
                /// The image_url_png string used to render png QR code.
                public var imageUrlPng: String?
                /// The image_url_svg string used to render svg QR code.
                public var imageUrlSvg: String?

                public init(
                    data: String? = nil,
                    expiresAt: Date? = nil,
                    hostedInstructionsUrl: String? = nil,
                    imageUrlPng: String? = nil,
                    imageUrlSvg: String? = nil
                ) {
                    self.data = data
                    self.expiresAt = expiresAt
                    self.hostedInstructionsUrl = hostedInstructionsUrl
                    self.imageUrlPng = imageUrlPng
                    self.imageUrlSvg = imageUrlSvg
                }
            }

            public struct RedirectToUrl: Codable, Hashable, Sendable {
                /// If the customer does not exit their browser while authenticating, they will be redirected to this specified URL after.
                public var returnUrl: String?
                /// The URL you must redirect your customer to in order to authenticate.
                public var url: String?

                public init(
                    returnUrl: String? = nil,
                    url: String? = nil
                ) {
                    self.returnUrl = returnUrl
                    self.url = url
                }
            }

            public struct VerifyWithMicrodeposits: Codable, Hashable, Sendable {
                /// The timestamp when the microdeposits are expected to land.
                public var arrivalDate: Date?
                /// The URL for the hosted verification page, which allows customers to verify their bank account.
                public var hostedVerificationUrl: String?
                /// The type of the microdeposit sent to the customer.
                public var microdepositType: MicrodepositType?

                public init(
                    arrivalDate: Date? = nil,
                    hostedVerificationUrl: String? = nil,
                    microdepositType: MicrodepositType? = nil
                ) {
                    self.arrivalDate = arrivalDate
                    self.hostedVerificationUrl = hostedVerificationUrl
                    self.microdepositType = microdepositType
                }

                /// The type of the microdeposit sent to the customer.
                public enum MicrodepositType: String, Codable, Hashable, Sendable {
                    case amounts
                    case descriptorCode = "descriptor_code"
                }
            }

            /// The payload `type` selects; `unknown` carries a type this package does not model.
            public indirect enum Details: Hashable, Sendable {
                case blikAuthorize(Stripe.Shared.BlikAuthorize)
                case cashappHandleRedirectOrDisplayQrCode(Stripe.Shared.CashappHandleRedirectOrDisplayQrCode)
                case pixDisplayQrCode(PixDisplayQrCode)
                case redirectToUrl(RedirectToUrl)
                case upiHandleRedirectOrDisplayQrCode(Stripe.Shared.UpiHandleRedirectOrDisplayQrCode)
                case useStripeSdk([String: String])
                case verifyWithMicrodeposits(VerifyWithMicrodeposits)
                case unknown(type: String)

                public var blikAuthorize: Stripe.Shared.BlikAuthorize? {
                    if case .blikAuthorize(let value) = self { return value }
                    return nil
                }
                public var cashappHandleRedirectOrDisplayQrCode: Stripe.Shared.CashappHandleRedirectOrDisplayQrCode? {
                    if case .cashappHandleRedirectOrDisplayQrCode(let value) = self { return value }
                    return nil
                }
                public var pixDisplayQrCode: PixDisplayQrCode? {
                    if case .pixDisplayQrCode(let value) = self { return value }
                    return nil
                }
                public var redirectToUrl: RedirectToUrl? {
                    if case .redirectToUrl(let value) = self { return value }
                    return nil
                }
                public var upiHandleRedirectOrDisplayQrCode: Stripe.Shared.UpiHandleRedirectOrDisplayQrCode? {
                    if case .upiHandleRedirectOrDisplayQrCode(let value) = self { return value }
                    return nil
                }
                public var useStripeSdk: [String: String]? {
                    if case .useStripeSdk(let value) = self { return value }
                    return nil
                }
                public var verifyWithMicrodeposits: VerifyWithMicrodeposits? {
                    if case .verifyWithMicrodeposits(let value) = self { return value }
                    return nil
                }

                fileprivate init(type: String, from container: KeyedDecodingContainer<CodingKeys>) throws {
                    switch type {
                    case "blik_authorize":
                        if let value = try container.decodeIfPresent(Stripe.Shared.BlikAuthorize.self, forKey: .blikAuthorize) {
                            self = .blikAuthorize(value)
                        } else {
                            self = .unknown(type: type)
                        }
                    case "cashapp_handle_redirect_or_display_qr_code":
                        if let value = try container.decodeIfPresent(
                            Stripe.Shared.CashappHandleRedirectOrDisplayQrCode.self,
                            forKey: .cashappHandleRedirectOrDisplayQrCode
                        ) {
                            self = .cashappHandleRedirectOrDisplayQrCode(value)
                        } else {
                            self = .unknown(type: type)
                        }
                    case "pix_display_qr_code":
                        if let value = try container.decodeIfPresent(PixDisplayQrCode.self, forKey: .pixDisplayQrCode) {
                            self = .pixDisplayQrCode(value)
                        } else {
                            self = .unknown(type: type)
                        }
                    case "redirect_to_url":
                        if let value = try container.decodeIfPresent(RedirectToUrl.self, forKey: .redirectToUrl) {
                            self = .redirectToUrl(value)
                        } else {
                            self = .unknown(type: type)
                        }
                    case "upi_handle_redirect_or_display_qr_code":
                        if let value = try container.decodeIfPresent(
                            Stripe.Shared.UpiHandleRedirectOrDisplayQrCode.self,
                            forKey: .upiHandleRedirectOrDisplayQrCode
                        ) {
                            self = .upiHandleRedirectOrDisplayQrCode(value)
                        } else {
                            self = .unknown(type: type)
                        }
                    case "use_stripe_sdk":
                        if let value = try container.decodeIfPresent([String: String].self, forKey: .useStripeSdk) {
                            self = .useStripeSdk(value)
                        } else {
                            self = .unknown(type: type)
                        }
                    case "verify_with_microdeposits":
                        if let value = try container.decodeIfPresent(VerifyWithMicrodeposits.self, forKey: .verifyWithMicrodeposits) {
                            self = .verifyWithMicrodeposits(value)
                        } else {
                            self = .unknown(type: type)
                        }
                    default: self = .unknown(type: type)
                    }
                }

                fileprivate func encode(into container: inout KeyedEncodingContainer<CodingKeys>) throws {
                    switch self {
                    case .blikAuthorize(let value): try container.encode(value, forKey: .blikAuthorize)
                    case .cashappHandleRedirectOrDisplayQrCode(let value): try container.encode(value, forKey: .cashappHandleRedirectOrDisplayQrCode)
                    case .pixDisplayQrCode(let value): try container.encode(value, forKey: .pixDisplayQrCode)
                    case .redirectToUrl(let value): try container.encode(value, forKey: .redirectToUrl)
                    case .upiHandleRedirectOrDisplayQrCode(let value): try container.encode(value, forKey: .upiHandleRedirectOrDisplayQrCode)
                    case .useStripeSdk(let value): try container.encode(value, forKey: .useStripeSdk)
                    case .verifyWithMicrodeposits(let value): try container.encode(value, forKey: .verifyWithMicrodeposits)
                    default: break
                    }
                }
            }
        }

        public struct PaymentMethodOptions: Codable, Hashable, Sendable {
            public var acssDebit: AcssDebit?
            public var amazonPay: AmazonPay?
            public var bacsDebit: BacsDebit?
            public var bizum: Bizum?
            @Boxed public var card: Card?
            public var cardPresent: CardPresent?
            public var klarna: Klarna?
            public var link: Link?
            public var paypal: Paypal?
            public var payto: Payto?
            public var pix: Pix?
            public var sepaDebit: SepaDebit?
            public var upi: Upi?
            public var usBankAccount: UsBankAccount?

            public init(
                acssDebit: AcssDebit? = nil,
                amazonPay: AmazonPay? = nil,
                bacsDebit: BacsDebit? = nil,
                bizum: Bizum? = nil,
                card: Card? = nil,
                cardPresent: CardPresent? = nil,
                klarna: Klarna? = nil,
                link: Link? = nil,
                paypal: Paypal? = nil,
                payto: Payto? = nil,
                pix: Pix? = nil,
                sepaDebit: SepaDebit? = nil,
                upi: Upi? = nil,
                usBankAccount: UsBankAccount? = nil
            ) {
                self.acssDebit = acssDebit
                self.amazonPay = amazonPay
                self.bacsDebit = bacsDebit
                self.bizum = bizum
                self._card = Boxed(wrappedValue: card)
                self.cardPresent = cardPresent
                self.klarna = klarna
                self.link = link
                self.paypal = paypal
                self.payto = payto
                self.pix = pix
                self.sepaDebit = sepaDebit
                self.upi = upi
                self.usBankAccount = usBankAccount
            }

            public struct AcssDebit: Codable, Hashable, Sendable {
                /// Currency supported by the bank account.
                public var currency: Currency?
                public var mandateOptions: MandateOptions?
                /// Bank account verification method.
                public var verificationMethod: VerificationMethod?

                public init(
                    currency: Currency? = nil,
                    mandateOptions: MandateOptions? = nil,
                    verificationMethod: VerificationMethod? = nil
                ) {
                    self.currency = currency
                    self.mandateOptions = mandateOptions
                    self.verificationMethod = verificationMethod
                }

                /// Currency supported by the bank account.
                public enum Currency: String, Codable, Hashable, Sendable {
                    case cad
                    case usd
                }

                /// Bank account verification method.
                public enum VerificationMethod: String, Codable, Hashable, Sendable {
                    case automatic
                    case instant
                    case microdeposits
                }

                public struct MandateOptions: Codable, Hashable, Sendable {
                    /// A URL for custom mandate text.
                    public var customMandateUrl: String?
                    /// List of Stripe products where this mandate can be selected automatically.
                    public var defaultFor: [DefaultFor]?
                    /// Description of the interval.
                    public var intervalDescription: String?
                    /// Payment schedule for the mandate.
                    public var paymentSchedule: PaymentSchedule?
                    /// Transaction type of the mandate.
                    public var transactionType: TransactionType?

                    public init(
                        customMandateUrl: String? = nil,
                        defaultFor: [DefaultFor]? = nil,
                        intervalDescription: String? = nil,
                        paymentSchedule: PaymentSchedule? = nil,
                        transactionType: TransactionType? = nil
                    ) {
                        self.customMandateUrl = customMandateUrl
                        self.defaultFor = defaultFor
                        self.intervalDescription = intervalDescription
                        self.paymentSchedule = paymentSchedule
                        self.transactionType = transactionType
                    }

                    public enum DefaultFor: String, Codable, Hashable, Sendable {
                        case invoice
                        case subscription
                    }

                    /// Payment schedule for the mandate.
                    public enum PaymentSchedule: String, Codable, Hashable, Sendable {
                        case combined
                        case interval
                        case sporadic
                    }

                    /// Transaction type of the mandate.
                    public enum TransactionType: String, Codable, Hashable, Sendable {
                        case business
                        case personal
                    }
                }
            }

            public struct AmazonPay: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct BacsDebit: Codable, Hashable, Sendable {
                public var mandateOptions: MandateOptions?

                public init(
                    mandateOptions: MandateOptions? = nil
                ) {
                    self.mandateOptions = mandateOptions
                }

                public struct MandateOptions: Codable, Hashable, Sendable {
                    /// Prefix used to generate the Mandate reference.
                    public var referencePrefix: String?

                    public init(
                        referencePrefix: String? = nil
                    ) {
                        self.referencePrefix = referencePrefix
                    }
                }
            }

            public struct Bizum: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Card: Codable, Hashable, Sendable {
                /// Configuration options for setting up an eMandate for cards issued in India.
                public var mandateOptions: MandateOptions?
                /// Selected network to process this SetupIntent on.
                public var network: Network?
                /// We strongly recommend that you rely on our SCA Engine to automatically prompt your customers for authentication based.
                public var requestThreeDSecure: RequestThreeDSecure?

                public init(
                    mandateOptions: MandateOptions? = nil,
                    network: Network? = nil,
                    requestThreeDSecure: RequestThreeDSecure? = nil
                ) {
                    self.mandateOptions = mandateOptions
                    self.network = network
                    self.requestThreeDSecure = requestThreeDSecure
                }

                /// Selected network to process this SetupIntent on.
                public enum Network: String, Codable, Hashable, Sendable {
                    case amex
                    case cartesBancaires = "cartes_bancaires"
                    case diners
                    case discover
                    case eftposAu = "eftpos_au"
                    case girocard
                    case interac
                    case jcb
                    case link
                    case mastercard
                    case unionpay
                    case unknown
                    case visa
                }

                /// We strongly recommend that you rely on our SCA Engine to automatically prompt your customers for authentication based.
                public enum RequestThreeDSecure: String, Codable, Hashable, Sendable {
                    case `any`
                    case automatic
                    case challenge
                }

                public struct MandateOptions: Codable, Hashable, Sendable {
                    /// Amount to be charged for future payments, specified in the presentment currency.
                    public var amount: Int?
                    /// One of `fixed` or `maximum`.
                    public var amountType: AmountType?
                    /// Three-letter ISO currency code, in lowercase.
                    public var currency: Stripe.Currency?
                    /// A description of the mandate or subscription that is meant to be displayed to the customer.
                    public var description: String?
                    /// End date of the mandate or subscription.
                    public var endDate: Date?
                    /// Specifies payment frequency.
                    public var interval: Interval?
                    /// The number of intervals between payments.
                    public var intervalCount: Int?
                    /// Unique identifier for the mandate or subscription.
                    public var reference: String?
                    /// Start date of the mandate or subscription.
                    public var startDate: Date?
                    /// Specifies the type of mandates supported.
                    public var supportedTypes: [String]?

                    public init(
                        amount: Int? = nil,
                        amountType: AmountType? = nil,
                        currency: Stripe.Currency? = nil,
                        description: String? = nil,
                        endDate: Date? = nil,
                        interval: Interval? = nil,
                        intervalCount: Int? = nil,
                        reference: String? = nil,
                        startDate: Date? = nil,
                        supportedTypes: [String]? = nil
                    ) {
                        self.amount = amount
                        self.amountType = amountType
                        self.currency = currency
                        self.description = description
                        self.endDate = endDate
                        self.interval = interval
                        self.intervalCount = intervalCount
                        self.reference = reference
                        self.startDate = startDate
                        self.supportedTypes = supportedTypes
                    }

                    /// One of `fixed` or `maximum`.
                    public enum AmountType: String, Codable, Hashable, Sendable {
                        case fixed
                        case maximum
                    }

                    /// Specifies payment frequency.
                    public enum Interval: String, Codable, Hashable, Sendable {
                        case day
                        case month
                        case sporadic
                        case week
                        case year
                    }
                }
            }

            public struct CardPresent: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Klarna: Codable, Hashable, Sendable {
                /// The currency of the setup intent.
                public var currency: Stripe.Currency?
                /// Preferred locale of the Klarna checkout page that the customer is redirected to.
                public var preferredLocale: String?

                public init(
                    currency: Stripe.Currency? = nil,
                    preferredLocale: String? = nil
                ) {
                    self.currency = currency
                    self.preferredLocale = preferredLocale
                }
            }

            public struct Link: Codable, Hashable, Sendable {
                /// [Deprecated] This is a legacy parameter that no longer has any function.
                public var persistentToken: String?

                public init(
                    persistentToken: String? = nil
                ) {
                    self.persistentToken = persistentToken
                }
            }

            public struct Paypal: Codable, Hashable, Sendable {
                /// The PayPal Billing Agreement ID (BAID).
                public var billingAgreementId: String?

                public init(
                    billingAgreementId: String? = nil
                ) {
                    self.billingAgreementId = billingAgreementId
                }
            }

            public struct Payto: Codable, Hashable, Sendable {
                public var mandateOptions: MandateOptions?

                public init(
                    mandateOptions: MandateOptions? = nil
                ) {
                    self.mandateOptions = mandateOptions
                }

                public struct MandateOptions: Codable, Hashable, Sendable {
                    /// Amount that will be collected.
                    public var amount: Int?
                    /// The type of amount that will be collected.
                    public var amountType: AmountType?
                    /// Date, in YYYY-MM-DD format, after which payments will not be collected.
                    public var endDate: String?
                    /// The periodicity at which payments will be collected.
                    public var paymentSchedule: PaymentSchedule?
                    /// The number of payments that will be made during a payment period.
                    public var paymentsPerPeriod: Int?
                    /// The purpose for which payments are made.
                    public var purpose: Purpose?
                    /// Date, in YYYY-MM-DD format, from which payments will be collected.
                    public var startDate: String?

                    public init(
                        amount: Int? = nil,
                        amountType: AmountType? = nil,
                        endDate: String? = nil,
                        paymentSchedule: PaymentSchedule? = nil,
                        paymentsPerPeriod: Int? = nil,
                        purpose: Purpose? = nil,
                        startDate: String? = nil
                    ) {
                        self.amount = amount
                        self.amountType = amountType
                        self.endDate = endDate
                        self.paymentSchedule = paymentSchedule
                        self.paymentsPerPeriod = paymentsPerPeriod
                        self.purpose = purpose
                        self.startDate = startDate
                    }

                    /// The type of amount that will be collected.
                    public enum AmountType: String, Codable, Hashable, Sendable {
                        case fixed
                        case maximum
                    }

                    /// The periodicity at which payments will be collected.
                    public enum PaymentSchedule: String, Codable, Hashable, Sendable {
                        case adhoc
                        case annual
                        case daily
                        case fortnightly
                        case monthly
                        case quarterly
                        case semiAnnual = "semi_annual"
                        case weekly
                    }

                    /// The purpose for which payments are made.
                    public enum Purpose: String, Codable, Hashable, Sendable {
                        case dependantSupport = "dependant_support"
                        case government
                        case loan
                        case mortgage
                        case other
                        case pension
                        case personal
                        case retail
                        case salary
                        case tax
                        case utility
                    }
                }
            }

            public struct Pix: Codable, Hashable, Sendable {
                public var mandateOptions: Stripe.Shared.MandateOptions?

                public init(
                    mandateOptions: Stripe.Shared.MandateOptions? = nil
                ) {
                    self.mandateOptions = mandateOptions
                }
            }

            public struct SepaDebit: Codable, Hashable, Sendable {
                public var mandateOptions: MandateOptions?

                public init(
                    mandateOptions: MandateOptions? = nil
                ) {
                    self.mandateOptions = mandateOptions
                }

                public struct MandateOptions: Codable, Hashable, Sendable {
                    /// Prefix used to generate the Mandate reference.
                    public var referencePrefix: String?

                    public init(
                        referencePrefix: String? = nil
                    ) {
                        self.referencePrefix = referencePrefix
                    }
                }
            }

            public struct Upi: Codable, Hashable, Sendable {
                public var mandateOptions: MandateOptions?

                public init(
                    mandateOptions: MandateOptions? = nil
                ) {
                    self.mandateOptions = mandateOptions
                }

                public struct MandateOptions: Codable, Hashable, Sendable {
                    /// Amount to be charged for future payments.
                    public var amount: Int?
                    /// One of `fixed` or `maximum`.
                    public var amountType: AmountType?
                    /// A description of the mandate or subscription that is meant to be displayed to the customer.
                    public var description: String?
                    /// End date of the mandate or subscription.
                    public var endDate: Date?

                    public init(
                        amount: Int? = nil,
                        amountType: AmountType? = nil,
                        description: String? = nil,
                        endDate: Date? = nil
                    ) {
                        self.amount = amount
                        self.amountType = amountType
                        self.description = description
                        self.endDate = endDate
                    }

                    /// One of `fixed` or `maximum`.
                    public enum AmountType: String, Codable, Hashable, Sendable {
                        case fixed
                        case maximum
                    }
                }
            }

            public struct UsBankAccount: Codable, Hashable, Sendable {
                public var financialConnections: Stripe.Shared.FinancialConnections?
                public var mandateOptions: Stripe.Shared.PaymentMethodOptionsUsBankAccountMandateOptions?
                /// Bank account verification method.
                public var verificationMethod: VerificationMethod?

                public init(
                    financialConnections: Stripe.Shared.FinancialConnections? = nil,
                    mandateOptions: Stripe.Shared.PaymentMethodOptionsUsBankAccountMandateOptions? = nil,
                    verificationMethod: VerificationMethod? = nil
                ) {
                    self.financialConnections = financialConnections
                    self.mandateOptions = mandateOptions
                    self.verificationMethod = verificationMethod
                }

                /// Bank account verification method.
                public enum VerificationMethod: String, Codable, Hashable, Sendable {
                    case automatic
                    case instant
                    case microdeposits
                }
            }
        }
    }
}
