//
//  Billing/Alert+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing.Alert {
    public enum Activate {}
    public enum Archive {}
    public enum Create {}
    public enum Deactivate {}
    public enum List {}
    public enum Retrieve {}
}

// POST /v1/billing/alerts/{id}/activate
extension Stripe.Billing.Alert.Activate {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        private enum CodingKeys: String, CodingKey {
            case expand
        }

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Billing.Alert
}

// POST /v1/billing/alerts/{id}/archive
extension Stripe.Billing.Alert.Archive {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        private enum CodingKeys: String, CodingKey {
            case expand
        }

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Billing.Alert
}

// POST /v1/billing/alerts
extension Stripe.Billing.Alert.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// The type of alert to create.
        public var alertType: String
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// The title of the alert.
        public var title: String
        /// The configuration of the usage threshold.
        public var usageThreshold: UsageThreshold?

        private enum CodingKeys: String, CodingKey {
            case alertType
            case expand
            case title
            case usageThreshold
        }

        public init(
            alertType: String,
            expand: [String]? = nil,
            title: String,
            usageThreshold: UsageThreshold? = nil
        ) {
            self.alertType = alertType
            self.expand = expand
            self.title = title
            self.usageThreshold = usageThreshold
        }

        /// The configuration of the usage threshold.
        public struct UsageThreshold: Codable, Hashable, Sendable {
            /// The filters allows limiting the scope of this usage alert.
            public var filters: [Filters]?
            /// Defines the threshold value that triggers the alert.
            public var gte: Int
            /// The Billing Meter ID whose usage is monitored.
            public var meter: String
            /// Defines how the alert will behave.
            public var recurrence: String

            private enum CodingKeys: String, CodingKey {
                case filters
                case gte
                case meter
                case recurrence
            }

            public init(
                filters: [Filters]? = nil,
                gte: Int,
                meter: String,
                recurrence: String
            ) {
                self.filters = filters
                self.gte = gte
                self.meter = meter
                self.recurrence = recurrence
            }

            public struct Filters: Codable, Hashable, Sendable {
                /// Limit the scope to this usage alert only to this customer.
                public var customer: String?
                /// What type of filter is being applied to this usage alert.
                public var `type`: String

                private enum CodingKeys: String, CodingKey {
                    case customer
                    case `type`
                }

                public init(
                    customer: String? = nil,
                    `type`: String
                ) {
                    self.customer = customer
                    self.`type` = `type`
                }
            }
        }
    }

    public typealias Response = Stripe.Billing.Alert
}

// POST /v1/billing/alerts/{id}/deactivate
extension Stripe.Billing.Alert.Deactivate {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        private enum CodingKeys: String, CodingKey {
            case expand
        }

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Billing.Alert
}

// GET /v1/billing/alerts
extension Stripe.Billing.Alert.List {
    public struct Request: Codable, Hashable, Sendable {
        /// Filter results to only include this type of alert.
        public var alertType: String?
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// Filter results to only include alerts with the given meter.
        public var meter: String?
        /// A cursor for use in pagination.
        public var startingAfter: String?

        private enum CodingKeys: String, CodingKey {
            case alertType
            case endingBefore
            case expand
            case limit
            case meter
            case startingAfter
        }

        public init(
            alertType: String? = nil,
            endingBefore: String? = nil,
            expand: [String]? = nil,
            limit: Int? = nil,
            meter: String? = nil,
            startingAfter: String? = nil
        ) {
            self.alertType = alertType
            self.endingBefore = endingBefore
            self.expand = expand
            self.limit = limit
            self.meter = meter
            self.startingAfter = startingAfter
        }
    }

    public typealias Response = Stripe.Page<Stripe.Billing.Alert>
}

// GET /v1/billing/alerts/{id}
extension Stripe.Billing.Alert.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        private enum CodingKeys: String, CodingKey {
            case expand
        }

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Billing.Alert
}
