//
//  Billing/MeterEvent+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing.MeterEvent {
    public enum Create {}
}

// POST /v1/billing/meter_events
extension Stripe.Billing.MeterEvent.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// The name of the meter event.
        public var eventName: String
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A unique identifier for the event.
        public var identifier: String?
        /// The payload of the event.
        public var payload: [String: String]
        /// The time of the event.
        public var timestamp: Date?

        private enum CodingKeys: String, CodingKey {
            case eventName
            case expand
            case identifier
            case payload
            case timestamp
        }

        public init(
            eventName: String,
            expand: [String]? = nil,
            identifier: String? = nil,
            payload: [String: String],
            timestamp: Date? = nil
        ) {
            self.eventName = eventName
            self.expand = expand
            self.identifier = identifier
            self.payload = payload
            self.timestamp = timestamp
        }
    }

    public typealias Response = Stripe.Billing.MeterEvent
}
