//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: tax_id
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Tax {
    /// You can add one or multiple tax IDs to a customer or account.
    public struct ID: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Two-letter ISO code representing the country of the tax ID.
        public var country: String?
        /// Time at which the object was created.
        public var created: Date?
        /// ID of the customer.
        @Expandable<Stripe.Customers.Customer, String> public var customer: String?
        /// ID of the Account representing the customer.
        public var customerAccount: String?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// The account or customer the tax ID belongs to.
        public var owner: Owner?
        /// Type of the tax ID, one of `ad_nrt`, `ae_trn`, `al_tin`, `am_tin`, `ao_tin`, `ar_cuit`, `au_abn`, `au_arn`, `aw_tin`, …
        public var `type`: Type?
        /// Value of the tax ID.
        public var value: String?
        /// Tax ID verification information.
        public var verification: Verification?

        public init(
            id: ID,
            object: String,
            country: String? = nil,
            created: Date? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            livemode: Bool? = nil,
            owner: Owner? = nil,
            `type`: Type? = nil,
            value: String? = nil,
            verification: Verification? = nil
        ) {
            self.id = id
            self.object = object
            self.country = country
            self.created = created
            self._customer = Expandable(id: customer)
            self.customerAccount = customerAccount
            self.livemode = livemode
            self.owner = owner
            self.`type` = `type`
            self.value = value
            self.verification = verification
        }

        /// Type of the tax ID, one of `ad_nrt`, `ae_trn`, `al_tin`, `am_tin`, `ao_tin`, `ar_cuit`, `au_abn`, `au_arn`, `aw_tin`, …
        public enum `Type`: String, Codable, Hashable, Sendable {
            case adNrt = "ad_nrt"
            case aeTrn = "ae_trn"
            case alTin = "al_tin"
            case amTin = "am_tin"
            case aoTin = "ao_tin"
            case arCuit = "ar_cuit"
            case auAbn = "au_abn"
            case auArn = "au_arn"
            case awTin = "aw_tin"
            case azTin = "az_tin"
            case baTin = "ba_tin"
            case bbTin = "bb_tin"
            case bdBin = "bd_bin"
            case bfIfu = "bf_ifu"
            case bgUic = "bg_uic"
            case bhVat = "bh_vat"
            case bjIfu = "bj_ifu"
            case boTin = "bo_tin"
            case brCnpj = "br_cnpj"
            case brCpf = "br_cpf"
            case bsTin = "bs_tin"
            case byTin = "by_tin"
            case caBn = "ca_bn"
            case caGstHst = "ca_gst_hst"
            case caPstBc = "ca_pst_bc"
            case caPstMb = "ca_pst_mb"
            case caPstSk = "ca_pst_sk"
            case caQst = "ca_qst"
            case cdNif = "cd_nif"
            case chUid = "ch_uid"
            case chVat = "ch_vat"
            case clTin = "cl_tin"
            case cmNiu = "cm_niu"
            case cnTin = "cn_tin"
            case coNit = "co_nit"
            case crTin = "cr_tin"
            case cvNif = "cv_nif"
            case deStn = "de_stn"
            case doRcn = "do_rcn"
            case ecRuc = "ec_ruc"
            case egTin = "eg_tin"
            case esCif = "es_cif"
            case etTin = "et_tin"
            case euOssVat = "eu_oss_vat"
            case euVat = "eu_vat"
            case foVat = "fo_vat"
            case gbVat = "gb_vat"
            case geVat = "ge_vat"
            case giTin = "gi_tin"
            case gnNif = "gn_nif"
            case hkBr = "hk_br"
            case hrOib = "hr_oib"
            case huTin = "hu_tin"
            case icNif = "ic_nif"
            case idNpwp = "id_npwp"
            case ilVat = "il_vat"
            case inGst = "in_gst"
            case isVat = "is_vat"
            case itCf = "it_cf"
            case jpCn = "jp_cn"
            case jpRn = "jp_rn"
            case jpTrn = "jp_trn"
            case kePin = "ke_pin"
            case kgTin = "kg_tin"
            case khTin = "kh_tin"
            case krBrn = "kr_brn"
            case kzBin = "kz_bin"
            case laTin = "la_tin"
            case liUid = "li_uid"
            case liVat = "li_vat"
            case lkVat = "lk_vat"
            case maVat = "ma_vat"
            case mdVat = "md_vat"
            case mePib = "me_pib"
            case mkVat = "mk_vat"
            case mrNif = "mr_nif"
            case mxRfc = "mx_rfc"
            case myFrp = "my_frp"
            case myItn = "my_itn"
            case mySst = "my_sst"
            case ngTin = "ng_tin"
            case noVat = "no_vat"
            case noVoec = "no_voec"
            case npPan = "np_pan"
            case nzGst = "nz_gst"
            case omVat = "om_vat"
            case peRuc = "pe_ruc"
            case phTin = "ph_tin"
            case plNip = "pl_nip"
            case pyRuc = "py_ruc"
            case roTin = "ro_tin"
            case rsPib = "rs_pib"
            case ruInn = "ru_inn"
            case ruKpp = "ru_kpp"
            case saVat = "sa_vat"
            case sgGst = "sg_gst"
            case sgUen = "sg_uen"
            case siTin = "si_tin"
            case snNinea = "sn_ninea"
            case srFin = "sr_fin"
            case svNit = "sv_nit"
            case thVat = "th_vat"
            case tjTin = "tj_tin"
            case trTin = "tr_tin"
            case twVat = "tw_vat"
            case tzVat = "tz_vat"
            case uaVat = "ua_vat"
            case ugTin = "ug_tin"
            case unknown
            case usEin = "us_ein"
            case uyRuc = "uy_ruc"
            case uzTin = "uz_tin"
            case uzVat = "uz_vat"
            case veRif = "ve_rif"
            case vnTin = "vn_tin"
            case zaVat = "za_vat"
            case zmTin = "zm_tin"
            case zwTin = "zw_tin"
        }

        public struct Owner: Codable, Hashable, Sendable {
            /// The Account representing the customer being referenced when `type` is `customer`.
            public var customerAccount: String?
            /// Type of owner referenced.
            public var `type`: Type?
            /// The payload `type` selects.
            public var details: Details

            fileprivate enum CodingKeys: String, CodingKey {
                case customerAccount
                case `type`
                case account
                case application
                case customer
            }

            public init(
                customerAccount: String? = nil,
                `type`: Type? = nil,
                details: Details
            ) {
                self.customerAccount = customerAccount
                self.`type` = `type`
                self.details = details
            }

            public init(from decoder: any Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.customerAccount = try container.decodeIfPresent(String.self, forKey: .customerAccount)
                self.`type` = try container.decodeIfPresent(Type.self, forKey: .`type`)
                self.details = try Details(type: try container.decodeIfPresent(String.self, forKey: .type) ?? "", from: container)
            }

            public func encode(to encoder: any Encoder) throws {
                var container = encoder.container(keyedBy: CodingKeys.self)
                try container.encodeIfPresent(customerAccount, forKey: .customerAccount)
                try container.encodeIfPresent(`type`, forKey: .`type`)
                try details.encode(into: &container)
            }

            /// Type of owner referenced.
            public enum `Type`: String, Codable, Hashable, Sendable {
                case account
                case application
                case customer
                case `self`
            }

            /// The payload `type` selects; `unknown` carries a type this package does not model.
            public indirect enum Details: Hashable, Sendable {
                case account(Expandable<Stripe.Connect.Account, String>)
                case application(Expandable<Stripe.Shared.Application, String>)
                case customer(Expandable<Stripe.Customers.Customer, String>)
                case `self`
                case unknown(type: String)

                public var account: Expandable<Stripe.Connect.Account, String>? { if case .account(let value) = self { return value }; return nil }
                public var application: Expandable<Stripe.Shared.Application, String>? { if case .application(let value) = self { return value }; return nil }
                public var customer: Expandable<Stripe.Customers.Customer, String>? { if case .customer(let value) = self { return value }; return nil }

                fileprivate init(type: String, from container: KeyedDecodingContainer<CodingKeys>) throws {
                    switch type {
                    case "account":
                        let value = try container.decode(Expandable<Stripe.Connect.Account, String>.self, forKey: .account)
                        if value.wrappedValue != nil || value.projectedValue != nil { self = .account(value) } else { self = .unknown(type: type) }
                    case "application":
                        let value = try container.decode(Expandable<Stripe.Shared.Application, String>.self, forKey: .application)
                        if value.wrappedValue != nil || value.projectedValue != nil { self = .application(value) } else { self = .unknown(type: type) }
                    case "customer":
                        let value = try container.decode(Expandable<Stripe.Customers.Customer, String>.self, forKey: .customer)
                        if value.wrappedValue != nil || value.projectedValue != nil { self = .customer(value) } else { self = .unknown(type: type) }
                    case "self": self = .`self`
                    default: self = .unknown(type: type)
                    }
                }

                fileprivate func encode(into container: inout KeyedEncodingContainer<CodingKeys>) throws {
                    switch self {
                    case .account(let value): try container.encode(value, forKey: .account)
                    case .application(let value): try container.encode(value, forKey: .application)
                    case .customer(let value): try container.encode(value, forKey: .customer)
                    default: break
                    }
                }
            }
        }

        public struct Verification: Codable, Hashable, Sendable {
            /// Verification status, one of `pending`, `verified`, `unverified`, or `unavailable`.
            public var status: Status?
            /// Verified address.
            public var verifiedAddress: String?
            /// Verified name.
            public var verifiedName: String?

            public init(
                status: Status? = nil,
                verifiedAddress: String? = nil,
                verifiedName: String? = nil
            ) {
                self.status = status
                self.verifiedAddress = verifiedAddress
                self.verifiedName = verifiedName
            }

            /// Verification status, one of `pending`, `verified`, `unverified`, or `unavailable`.
            public enum Status: String, Codable, Hashable, Sendable {
                case pending
                case unavailable
                case unverified
                case verified
            }
        }
    }
}
