//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: tax.settings
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Tax {
    /// You can use Tax `Settings` to manage configurations used by Stripe Tax calculations.
    public struct Settings: Codable, Hashable, Sendable {
        /// String representing the object's type.
        public let object: String
        public var defaults: Defaults?
        /// The place where your business is located.
        public var headOffice: HeadOffice?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// The status of the Tax `Settings`.
        public var status: Status?
        public var statusDetails: StatusDetails?

        public init(
            object: String,
            defaults: Defaults? = nil,
            headOffice: HeadOffice? = nil,
            livemode: Bool? = nil,
            status: Status? = nil,
            statusDetails: StatusDetails? = nil
        ) {
            self.object = object
            self.defaults = defaults
            self.headOffice = headOffice
            self.livemode = livemode
            self.status = status
            self.statusDetails = statusDetails
        }

        /// The status of the Tax `Settings`.
        public enum Status: String, Codable, Hashable, Sendable {
            case active
            case pending
        }

        public struct Defaults: Codable, Hashable, Sendable {
            /// The tax calculation provider this account uses.
            public var provider: Provider?
            /// Default tax behavior used to specify whether the price is considered inclusive of taxes or exclusive of taxes.
            public var taxBehavior: TaxBehavior?
            /// Default tax code used to classify your products and prices.
            public var taxCode: String?

            public init(
                provider: Provider? = nil,
                taxBehavior: TaxBehavior? = nil,
                taxCode: String? = nil
            ) {
                self.provider = provider
                self.taxBehavior = taxBehavior
                self.taxCode = taxCode
            }

            /// The tax calculation provider this account uses.
            public enum Provider: String, Codable, Hashable, Sendable {
                case anrok
                case avalara
                case sphere
                case stripe
            }

            /// Default tax behavior used to specify whether the price is considered inclusive of taxes or exclusive of taxes.
            public enum TaxBehavior: String, Codable, Hashable, Sendable {
                case exclusive
                case inclusive
                case inferredByCurrency = "inferred_by_currency"
            }
        }

        public struct HeadOffice: Codable, Hashable, Sendable {
            public var address: Address?

            public init(
                address: Address? = nil
            ) {
                self.address = address
            }
        }

        public struct StatusDetails: Codable, Hashable, Sendable {
            public var active: Active?
            public var pending: Pending?

            public init(
                active: Active? = nil,
                pending: Pending? = nil
            ) {
                self.active = active
                self.pending = pending
            }

            public struct Active: Codable, Hashable, Sendable {
                public init() {}
            }

            public struct Pending: Codable, Hashable, Sendable {
                /// The list of missing fields that are required to perform calculations.
                public var missingFields: [String]?

                public init(
                    missingFields: [String]? = nil
                ) {
                    self.missingFields = missingFields
                }
            }
        }
    }
}
