//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: tax_code
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Tax {
    /// Tax codes classify goods and services for tax purposes.
    public struct Code: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// A detailed description of which types of products the tax code represents.
        public var description: String?
        /// A short name for the tax code.
        public var name: String?

        public init(
            id: ID,
            object: String,
            description: String? = nil,
            name: String? = nil
        ) {
            self.id = id
            self.object = object
            self.description = description
            self.name = name
        }
    }
}
