//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: treasury.inbound_transfer
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Treasury {
    /// Use InboundTransfers to add funds to your FinancialAccount via a PaymentMethod that is owned by you.
    public struct InboundTransfer: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Amount (in cents) transferred.
        public var amount: Int?
        /// Returns `true` if the InboundTransfer is able to be canceled.
        public var cancelable: Bool?
        /// Time at which the object was created.
        public var created: Date?
        /// Three-letter ISO currency code, in lowercase.
        public var currency: Stripe.Currency?
        /// An arbitrary string attached to the object.
        public var description: String?
        /// Details about this InboundTransfer's failure.
        public var failureDetails: FailureDetails?
        /// The FinancialAccount that received the funds.
        public var financialAccount: String?
        /// A hosted transaction receipt URL that is provided when money movement is considered regulated under Stripe's money tra…
        public var hostedRegulatoryReceiptUrl: String?
        public var linkedFlows: LinkedFlows?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?
        /// The origin payment method to be debited for an InboundTransfer.
        public var originPaymentMethod: String?
        /// Details about the PaymentMethod for an InboundTransfer.
        public var originPaymentMethodDetails: OriginPaymentMethodDetails?
        /// Returns `true` if the funds for an InboundTransfer were returned after the InboundTransfer went to the `succeeded` sta…
        public var returned: Bool?
        /// Statement descriptor shown when funds are debited from the source.
        public var statementDescriptor: String?
        /// Status of the InboundTransfer: `processing`, `succeeded`, `failed`, and `canceled`.
        public var status: Status?
        public var statusTransitions: StatusTransitions?
        /// The Transaction associated with this object.
        @Expandable<Stripe.Treasury.Transaction, String> public var transaction: String?

        public init(
            id: ID,
            object: String,
            amount: Int? = nil,
            cancelable: Bool? = nil,
            created: Date? = nil,
            currency: Stripe.Currency? = nil,
            description: String? = nil,
            failureDetails: FailureDetails? = nil,
            financialAccount: String? = nil,
            hostedRegulatoryReceiptUrl: String? = nil,
            linkedFlows: LinkedFlows? = nil,
            livemode: Bool? = nil,
            metadata: [String: String]? = nil,
            originPaymentMethod: String? = nil,
            originPaymentMethodDetails: OriginPaymentMethodDetails? = nil,
            returned: Bool? = nil,
            statementDescriptor: String? = nil,
            status: Status? = nil,
            statusTransitions: StatusTransitions? = nil,
            transaction: String? = nil
        ) {
            self.id = id
            self.object = object
            self.amount = amount
            self.cancelable = cancelable
            self.created = created
            self.currency = currency
            self.description = description
            self.failureDetails = failureDetails
            self.financialAccount = financialAccount
            self.hostedRegulatoryReceiptUrl = hostedRegulatoryReceiptUrl
            self.linkedFlows = linkedFlows
            self.livemode = livemode
            self.metadata = metadata
            self.originPaymentMethod = originPaymentMethod
            self.originPaymentMethodDetails = originPaymentMethodDetails
            self.returned = returned
            self.statementDescriptor = statementDescriptor
            self.status = status
            self.statusTransitions = statusTransitions
            self._transaction = Expandable(id: transaction)
        }

        /// Status of the InboundTransfer: `processing`, `succeeded`, `failed`, and `canceled`.
        public enum Status: String, Codable, Hashable, Sendable {
            case canceled
            case failed
            case processing
            case succeeded
        }

        public struct FailureDetails: Codable, Hashable, Sendable {
            /// Reason for the failure.
            public var code: Code?

            public init(
                code: Code? = nil
            ) {
                self.code = code
            }

            /// Reason for the failure.
            public enum Code: String, Codable, Hashable, Sendable {
                case accountClosed = "account_closed"
                case accountFrozen = "account_frozen"
                case bankAccountRestricted = "bank_account_restricted"
                case bankOwnershipChanged = "bank_ownership_changed"
                case debitNotAuthorized = "debit_not_authorized"
                case incorrectAccountHolderAddress = "incorrect_account_holder_address"
                case incorrectAccountHolderName = "incorrect_account_holder_name"
                case incorrectAccountHolderTaxId = "incorrect_account_holder_tax_id"
                case insufficientFunds = "insufficient_funds"
                case invalidAccountNumber = "invalid_account_number"
                case invalidCurrency = "invalid_currency"
                case noAccount = "no_account"
                case other
            }
        }

        public struct LinkedFlows: Codable, Hashable, Sendable {
            /// If funds for this flow were returned after the flow went to the `succeeded` state, this field contains a reference to …
            public var receivedDebit: String?

            public init(
                receivedDebit: String? = nil
            ) {
                self.receivedDebit = receivedDebit
            }
        }

        public struct OriginPaymentMethodDetails: Codable, Hashable, Sendable {
            public var billingDetails: Stripe.Shared.TreasurySharedResourceBillingDetails?
            /// The type of the payment method used in the InboundTransfer.
            public var `type`: String?
            public var usBankAccount: UsBankAccount?

            public init(
                billingDetails: Stripe.Shared.TreasurySharedResourceBillingDetails? = nil,
                `type`: String? = nil,
                usBankAccount: UsBankAccount? = nil
            ) {
                self.billingDetails = billingDetails
                self.`type` = `type`
                self.usBankAccount = usBankAccount
            }

            public struct UsBankAccount: Codable, Hashable, Sendable {
                /// Account holder type: individual or company.
                public var accountHolderType: AccountHolderType?
                /// Account type: checkings or savings.
                public var accountType: AccountType?
                /// Name of the bank associated with the bank account.
                public var bankName: String?
                /// Uniquely identifies this particular bank account.
                public var fingerprint: String?
                /// Last four digits of the bank account number.
                public var last4: String?
                /// ID of the mandate used to make this payment.
                @Expandable<Stripe.Mandates.Mandate, String> public var mandate: String?
                /// The network rails used.
                public var network: String?
                /// Routing number of the bank account.
                public var routingNumber: String?

                public init(
                    accountHolderType: AccountHolderType? = nil,
                    accountType: AccountType? = nil,
                    bankName: String? = nil,
                    fingerprint: String? = nil,
                    last4: String? = nil,
                    mandate: String? = nil,
                    network: String? = nil,
                    routingNumber: String? = nil
                ) {
                    self.accountHolderType = accountHolderType
                    self.accountType = accountType
                    self.bankName = bankName
                    self.fingerprint = fingerprint
                    self.last4 = last4
                    self._mandate = Expandable(id: mandate)
                    self.network = network
                    self.routingNumber = routingNumber
                }

                /// Account holder type: individual or company.
                public enum AccountHolderType: String, Codable, Hashable, Sendable {
                    case company
                    case individual
                }

                /// Account type: checkings or savings.
                public enum AccountType: String, Codable, Hashable, Sendable {
                    case checking
                    case savings
                }
            }
        }

        public struct StatusTransitions: Codable, Hashable, Sendable {
            /// Timestamp describing when an InboundTransfer changed status to `canceled`.
            public var canceledAt: Date?
            /// Timestamp describing when an InboundTransfer changed status to `failed`.
            public var failedAt: Date?
            /// Timestamp describing when an InboundTransfer changed status to `succeeded`.
            public var succeededAt: Date?

            public init(
                canceledAt: Date? = nil,
                failedAt: Date? = nil,
                succeededAt: Date? = nil
            ) {
                self.canceledAt = canceledAt
                self.failedAt = failedAt
                self.succeededAt = succeededAt
            }
        }
    }
}
