//
//  Billing/Customer/Portal/Portal.Session+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing.Customer.Portal.Session {
    public enum Create {}
}

// POST /v1/billing_portal/sessions
extension Stripe.Billing.Customer.Portal.Session.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// The ID of an existing configuration to use for this session, describing its functionality and features.
        public var configuration: String?
        /// The ID of an existing customer.
        public var customer: String?
        /// The ID of an existing account.
        public var customerAccount: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Information about a specific flow for the customer to go through.
        public var flowData: FlowData?
        /// The IETF language tag of the locale customer portal is displayed in.
        public var locale: Locale?
        /// The `on_behalf_of` account to use for this session.
        public var onBehalfOf: String?
        /// The default URL to redirect customers to when they click on the portal's link to return to your website.
        public var returnUrl: String?

        private enum CodingKeys: String, CodingKey {
            case configuration
            case customer
            case customerAccount
            case expand
            case flowData
            case locale
            case onBehalfOf
            case returnUrl
        }

        public init(
            configuration: String? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            expand: [String]? = nil,
            flowData: FlowData? = nil,
            locale: Locale? = nil,
            onBehalfOf: String? = nil,
            returnUrl: String? = nil
        ) {
            self.configuration = configuration
            self.customer = customer
            self.customerAccount = customerAccount
            self.expand = expand
            self.flowData = flowData
            self.locale = locale
            self.onBehalfOf = onBehalfOf
            self.returnUrl = returnUrl
        }

        public enum Locale: String, Codable, Hashable, Sendable {
            case auto
            case bg
            case cs
            case da
            case de
            case el
            case en
            case enAU = "en-AU"
            case enCA = "en-CA"
            case enGB = "en-GB"
            case enIE = "en-IE"
            case enIN = "en-IN"
            case enNZ = "en-NZ"
            case enSG = "en-SG"
            case es
            case es419 = "es-419"
            case et
            case fi
            case fil
            case fr
            case frCA = "fr-CA"
            case hr
            case hu
            case id
            case it
            case ja
            case ko
            case lt
            case lv
            case ms
            case mt
            case nb
            case nl
            case pl
            case pt
            case ptBR = "pt-BR"
            case ro
            case ru
            case sk
            case sl
            case sv
            case th
            case tr
            case vi
            case zh
            case zhHK = "zh-HK"
            case zhTW = "zh-TW"
        }

        /// Information about a specific flow for the customer to go through.
        public struct FlowData: Codable, Hashable, Sendable {
            /// Behavior after the flow is completed.
            public var afterCompletion: AfterCompletion?
            /// Configuration when `flow_data.type=subscription_cancel`.
            public var subscriptionCancel: SubscriptionCancel?
            /// Configuration when `flow_data.type=subscription_update`.
            public var subscriptionUpdate: SubscriptionUpdate?
            /// Configuration when `flow_data.type=subscription_update_confirm`.
            public var subscriptionUpdateConfirm: SubscriptionUpdateConfirm?
            /// Type of flow that the customer will go through.
            public var `type`: Type

            private enum CodingKeys: String, CodingKey {
                case afterCompletion
                case subscriptionCancel
                case subscriptionUpdate
                case subscriptionUpdateConfirm
                case `type`
            }

            public init(
                afterCompletion: AfterCompletion? = nil,
                subscriptionCancel: SubscriptionCancel? = nil,
                subscriptionUpdate: SubscriptionUpdate? = nil,
                subscriptionUpdateConfirm: SubscriptionUpdateConfirm? = nil,
                `type`: Type
            ) {
                self.afterCompletion = afterCompletion
                self.subscriptionCancel = subscriptionCancel
                self.subscriptionUpdate = subscriptionUpdate
                self.subscriptionUpdateConfirm = subscriptionUpdateConfirm
                self.`type` = `type`
            }

            public enum `Type`: String, Codable, Hashable, Sendable {
                case paymentMethodUpdate = "payment_method_update"
                case subscriptionCancel = "subscription_cancel"
                case subscriptionUpdate = "subscription_update"
                case subscriptionUpdateConfirm = "subscription_update_confirm"
            }

            /// Behavior after the flow is completed.
            public struct AfterCompletion: Codable, Hashable, Sendable {
                /// Configuration when `after_completion.type=hosted_confirmation`.
                public var hostedConfirmation: HostedConfirmation?
                /// Configuration when `after_completion.type=redirect`.
                public var redirect: Redirect?
                /// The specified behavior after the flow is completed.
                public var `type`: Type

                private enum CodingKeys: String, CodingKey {
                    case hostedConfirmation
                    case redirect
                    case `type`
                }

                public init(
                    hostedConfirmation: HostedConfirmation? = nil,
                    redirect: Redirect? = nil,
                    `type`: Type
                ) {
                    self.hostedConfirmation = hostedConfirmation
                    self.redirect = redirect
                    self.`type` = `type`
                }

                public enum `Type`: String, Codable, Hashable, Sendable {
                    case hostedConfirmation = "hosted_confirmation"
                    case portalHomepage = "portal_homepage"
                    case redirect
                }

                /// Configuration when `after_completion.type=hosted_confirmation`.
                public struct HostedConfirmation: Codable, Hashable, Sendable {
                    /// A custom message to display to the customer after the flow is completed.
                    public var customMessage: String?

                    private enum CodingKeys: String, CodingKey {
                        case customMessage
                    }

                    public init(
                        customMessage: String? = nil
                    ) {
                        self.customMessage = customMessage
                    }
                }

                /// Configuration when `after_completion.type=redirect`.
                public struct Redirect: Codable, Hashable, Sendable {
                    /// The URL the customer will be redirected to after the flow is completed.
                    public var returnUrl: String

                    private enum CodingKeys: String, CodingKey {
                        case returnUrl
                    }

                    public init(
                        returnUrl: String
                    ) {
                        self.returnUrl = returnUrl
                    }
                }
            }

            /// Configuration when `flow_data.type=subscription_cancel`.
            public struct SubscriptionCancel: Codable, Hashable, Sendable {
                /// Specify a retention strategy to be used in the cancellation flow.
                public var retention: Retention?
                /// The ID of the subscription to be canceled.
                public var subscription: String

                private enum CodingKeys: String, CodingKey {
                    case retention
                    case subscription
                }

                public init(
                    retention: Retention? = nil,
                    subscription: String
                ) {
                    self.retention = retention
                    self.subscription = subscription
                }

                /// Specify a retention strategy to be used in the cancellation flow.
                public struct Retention: Codable, Hashable, Sendable {
                    /// Configuration when `retention.type=coupon_offer`.
                    public var couponOffer: CouponOffer
                    /// Type of retention strategy to use with the customer.
                    public var `type`: String

                    private enum CodingKeys: String, CodingKey {
                        case couponOffer
                        case `type`
                    }

                    public init(
                        couponOffer: CouponOffer,
                        `type`: String
                    ) {
                        self.couponOffer = couponOffer
                        self.`type` = `type`
                    }

                    /// Configuration when `retention.type=coupon_offer`.
                    public struct CouponOffer: Codable, Hashable, Sendable {
                        /// The ID of the coupon to be offered.
                        public var coupon: String

                        private enum CodingKeys: String, CodingKey {
                            case coupon
                        }

                        public init(
                            coupon: String
                        ) {
                            self.coupon = coupon
                        }
                    }
                }
            }

            /// Configuration when `flow_data.type=subscription_update`.
            public struct SubscriptionUpdate: Codable, Hashable, Sendable {
                /// The ID of the subscription to be updated.
                public var subscription: String

                private enum CodingKeys: String, CodingKey {
                    case subscription
                }

                public init(
                    subscription: String
                ) {
                    self.subscription = subscription
                }
            }

            /// Configuration when `flow_data.type=subscription_update_confirm`.
            public struct SubscriptionUpdateConfirm: Codable, Hashable, Sendable {
                /// The coupon or promotion code to apply to this subscription update.
                public var discounts: [Discounts]?
                /// The subscription item to be updated through this flow.
                public var items: [Items]
                /// The ID of the subscription to be updated.
                public var subscription: String

                private enum CodingKeys: String, CodingKey {
                    case discounts
                    case items
                    case subscription
                }

                public init(
                    discounts: [Discounts]? = nil,
                    items: [Items],
                    subscription: String
                ) {
                    self.discounts = discounts
                    self.items = items
                    self.subscription = subscription
                }

                public struct Discounts: Codable, Hashable, Sendable {
                    /// The ID of the coupon to apply to this subscription update.
                    public var coupon: String?
                    /// The ID of a promotion code to apply to this subscription update.
                    public var promotionCode: String?

                    private enum CodingKeys: String, CodingKey {
                        case coupon
                        case promotionCode
                    }

                    public init(
                        coupon: String? = nil,
                        promotionCode: String? = nil
                    ) {
                        self.coupon = coupon
                        self.promotionCode = promotionCode
                    }
                }

                public struct Items: Codable, Hashable, Sendable {
                    /// The ID of the subscription item to be updated.
                    public var id: String
                    /// The price the customer should subscribe to through this flow.
                    public var price: String?
                    /// Quantity for this item that the customer should subscribe to through this flow.
                    public var quantity: Int?

                    private enum CodingKeys: String, CodingKey {
                        case id
                        case price
                        case quantity
                    }

                    public init(
                        id: String,
                        price: String? = nil,
                        quantity: Int? = nil
                    ) {
                        self.id = id
                        self.price = price
                        self.quantity = quantity
                    }
                }
            }
        }
    }

    public typealias Response = Stripe.Billing.Customer.Portal.Session
}
