//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: credit_note
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing.Credit {
    /// Issue a credit note to adjust an invoice's amount after the invoice is finalized.
    public struct Note: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax.
        public var amount: Int?
        /// This is the sum of all the shipping amounts.
        public var amountShipping: Int?
        /// Time at which the object was created.
        public var created: Date?
        /// Three-letter ISO currency code, in lowercase.
        public var currency: Stripe.Currency?
        /// ID of the customer.
        @Expandable<Stripe.Customers.Customer, String> public var customer: String?
        /// ID of the account representing the customer.
        public var customerAccount: String?
        /// Customer balance transaction related to this credit note.
        @Expandable<Stripe.Billing.Customer.Balance.Transaction, String> public var customerBalanceTransaction: String?
        /// The integer amount in cents (or local equivalent) representing the total amount of discount that was credited.
        public var discountAmount: Int?
        /// The aggregate amounts calculated per discount for all line items.
        public var discountAmounts: [Stripe.Shared.DiscountsResourceDiscountAmount]?
        /// The date when this credit note is in effect.
        public var effectiveAt: Date?
        /// ID of the invoice.
        @Expandable<Stripe.Billing.Invoice, String> public var invoice: String?
        /// Line items that make up the credit note
        public var lines: Lines?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// Customer-facing text that appears on the credit note PDF.
        public var memo: String?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?
        /// A unique number that identifies this particular credit note and appears on the PDF of the credit note and its associat…
        public var number: String?
        /// Amount that was credited outside of Stripe.
        public var outOfBandAmount: Int?
        /// The link to download the PDF of the credit note.
        public var pdf: String?
        /// The amount of the credit note that was refunded to the customer, credited to the customer's balance, credited outside …
        public var postPaymentAmount: Int?
        /// The amount of the credit note by which the invoice's `amount_remaining` and `amount_due` were reduced.
        public var prePaymentAmount: Int?
        /// The pretax credit amounts (ex: discount, credit grants, etc) for all line items.
        public var pretaxCreditAmounts: [Stripe.Shared.PretaxCreditAmounts]?
        /// Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
        public var reason: Reason?
        /// Refunds related to this credit note.
        public var refunds: [Refunds]?
        /// The details of the cost of shipping, including the ShippingRate applied to the invoice.
        public var shippingCost: Stripe.Shared.ShippingCost?
        /// Status of this credit note, one of `issued` or `void`.
        public var status: Status?
        /// The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding exclusive tax …
        public var subtotal: Int?
        /// The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding all tax and in…
        public var subtotalExcludingTax: Int?
        /// The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax and …
        public var total: Int?
        /// The integer amount in cents (or local equivalent) representing the total amount of the credit note, excluding tax, but…
        public var totalExcludingTax: Int?
        /// The aggregate tax information for all line items.
        public var totalTaxes: [Stripe.Shared.BillingBillResourceInvoicingTaxesTax]?
        /// Type of this credit note, one of `pre_payment` or `post_payment`.
        public var `type`: Type?
        /// The time that the credit note was voided.
        public var voidedAt: Date?

        public init(
            id: ID,
            object: String,
            amount: Int? = nil,
            amountShipping: Int? = nil,
            created: Date? = nil,
            currency: Stripe.Currency? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            customerBalanceTransaction: String? = nil,
            discountAmount: Int? = nil,
            discountAmounts: [Stripe.Shared.DiscountsResourceDiscountAmount]? = nil,
            effectiveAt: Date? = nil,
            invoice: String? = nil,
            lines: Lines? = nil,
            livemode: Bool? = nil,
            memo: String? = nil,
            metadata: [String: String]? = nil,
            number: String? = nil,
            outOfBandAmount: Int? = nil,
            pdf: String? = nil,
            postPaymentAmount: Int? = nil,
            prePaymentAmount: Int? = nil,
            pretaxCreditAmounts: [Stripe.Shared.PretaxCreditAmounts]? = nil,
            reason: Reason? = nil,
            refunds: [Refunds]? = nil,
            shippingCost: Stripe.Shared.ShippingCost? = nil,
            status: Status? = nil,
            subtotal: Int? = nil,
            subtotalExcludingTax: Int? = nil,
            total: Int? = nil,
            totalExcludingTax: Int? = nil,
            totalTaxes: [Stripe.Shared.BillingBillResourceInvoicingTaxesTax]? = nil,
            `type`: Type? = nil,
            voidedAt: Date? = nil
        ) {
            self.id = id
            self.object = object
            self.amount = amount
            self.amountShipping = amountShipping
            self.created = created
            self.currency = currency
            self._customer = Expandable(id: customer)
            self.customerAccount = customerAccount
            self._customerBalanceTransaction = Expandable(id: customerBalanceTransaction)
            self.discountAmount = discountAmount
            self.discountAmounts = discountAmounts
            self.effectiveAt = effectiveAt
            self._invoice = Expandable(id: invoice)
            self.lines = lines
            self.livemode = livemode
            self.memo = memo
            self.metadata = metadata
            self.number = number
            self.outOfBandAmount = outOfBandAmount
            self.pdf = pdf
            self.postPaymentAmount = postPaymentAmount
            self.prePaymentAmount = prePaymentAmount
            self.pretaxCreditAmounts = pretaxCreditAmounts
            self.reason = reason
            self.refunds = refunds
            self.shippingCost = shippingCost
            self.status = status
            self.subtotal = subtotal
            self.subtotalExcludingTax = subtotalExcludingTax
            self.total = total
            self.totalExcludingTax = totalExcludingTax
            self.totalTaxes = totalTaxes
            self.`type` = `type`
            self.voidedAt = voidedAt
        }

        /// Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
        public enum Reason: String, Codable, Hashable, Sendable {
            case duplicate
            case fraudulent
            case orderChange = "order_change"
            case productUnsatisfactory = "product_unsatisfactory"
        }

        /// Status of this credit note, one of `issued` or `void`.
        public enum Status: String, Codable, Hashable, Sendable {
            case issued
            case void
        }

        /// Type of this credit note, one of `pre_payment` or `post_payment`.
        public enum `Type`: String, Codable, Hashable, Sendable {
            case mixed
            case postPayment = "post_payment"
            case prePayment = "pre_payment"
        }

        /// Line items that make up the credit note
        public struct Lines: Codable, Hashable, Sendable {
            /// String representing the object's type.
            public let object: String
            /// Details about each object.
            public var data: [Stripe.Billing.CreditNoteLineItem]?
            /// True if this list has another page of items after this one that can be fetched.
            public var hasMore: Bool?
            /// The URL where this list can be accessed.
            public var url: String?

            public init(
                object: String,
                data: [Stripe.Billing.CreditNoteLineItem]? = nil,
                hasMore: Bool? = nil,
                url: String? = nil
            ) {
                self.object = object
                self.data = data
                self.hasMore = hasMore
                self.url = url
            }
        }

        public struct Refunds: Codable, Hashable, Sendable {
            /// Amount of the refund that applies to this credit note, in cents (or local equivalent).
            public var amountRefunded: Int?
            /// The PaymentRecord refund details associated with this credit note refund.
            public var paymentRecordRefund: PaymentRecordRefund?
            /// ID of the refund.
            @Expandable<Stripe.Refunds.Refund, String> public var refund: String?
            /// Type of the refund, one of `refund` or `payment_record_refund`.
            public var `type`: Type?

            public init(
                amountRefunded: Int? = nil,
                paymentRecordRefund: PaymentRecordRefund? = nil,
                refund: String? = nil,
                `type`: Type? = nil
            ) {
                self.amountRefunded = amountRefunded
                self.paymentRecordRefund = paymentRecordRefund
                self._refund = Expandable(id: refund)
                self.`type` = `type`
            }

            /// Type of the refund, one of `refund` or `payment_record_refund`.
            public enum `Type`: String, Codable, Hashable, Sendable {
                case paymentRecordRefund = "payment_record_refund"
                case refund
            }

            public struct PaymentRecordRefund: Codable, Hashable, Sendable {
                /// ID of the payment record.
                public var paymentRecord: String?
                /// ID of the refund group.
                public var refundGroup: String?

                public init(
                    paymentRecord: String? = nil,
                    refundGroup: String? = nil
                ) {
                    self.paymentRecord = paymentRecord
                    self.refundGroup = refundGroup
                }
            }
        }
    }
}
