//
//  FinancialConnections/FinancialConnections.Transaction+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension FinancialConnections.Transaction {
    public enum List {}
    public enum Retrieve {}
}

// GET /v1/financial_connections/transactions
extension FinancialConnections.Transaction.List {
    public struct Request: Codable, Hashable, Sendable {
        /// The ID of the Financial Connections Account whose transactions will be retrieved.
        public var account: String
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// A cursor for use in pagination.
        public var startingAfter: String?
        /// A filter on the list based on the object `transacted_at` field.
        public var transactedAt: Stripe.RangeQuery?
        /// A filter on the list based on the object `transaction_refresh` field.
        public var transactionRefresh: TransactionRefresh?

        public init(
            account: String,
            endingBefore: String? = nil,
            expand: [String]? = nil,
            limit: Int? = nil,
            startingAfter: String? = nil,
            transactedAt: Stripe.RangeQuery? = nil,
            transactionRefresh: TransactionRefresh? = nil
        ) {
            self.account = account
            self.endingBefore = endingBefore
            self.expand = expand
            self.limit = limit
            self.startingAfter = startingAfter
            self.transactedAt = transactedAt
            self.transactionRefresh = transactionRefresh
        }

        /// A filter on the list based on the object `transaction_refresh` field.
        public struct TransactionRefresh: Codable, Hashable, Sendable {
            /// Return results where the transactions were created or updated by a refresh that took place after this refresh (non-inc…
            public var after: String

            public init(
                after: String
            ) {
                self.after = after
            }
        }
    }

    public typealias Response = Stripe.Page<FinancialConnections.Transaction>
}

// GET /v1/financial_connections/transactions/{transaction}
extension FinancialConnections.Transaction.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = FinancialConnections.Transaction
}
