//
//  FinancialConnections/FinancialConnections.Session+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension FinancialConnections.Session {
    public enum Create {}
    public enum Retrieve {}
}

// POST /v1/financial_connections/sessions
extension FinancialConnections.Session.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// The account holder to link accounts for.
        public var accountHolder: AccountHolder
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Filters to restrict the kinds of accounts to collect.
        public var filters: Filters?
        /// Settings for configuring Session-specific limits.
        public var limits: Limits?
        /// Customize manual entry behavior
        public var manualEntry: ManualEntry?
        /// List of data features that you would like to request access to.
        public var permissions: [Permissions]
        /// List of data features that you would like to retrieve upon account creation.
        public var prefetch: [Prefetch]?
        /// For webview integrations only.
        public var returnUrl: String?

        public init(
            accountHolder: AccountHolder,
            expand: [String]? = nil,
            filters: Filters? = nil,
            limits: Limits? = nil,
            manualEntry: ManualEntry? = nil,
            permissions: [Permissions],
            prefetch: [Prefetch]? = nil,
            returnUrl: String? = nil
        ) {
            self.accountHolder = accountHolder
            self.expand = expand
            self.filters = filters
            self.limits = limits
            self.manualEntry = manualEntry
            self.permissions = permissions
            self.prefetch = prefetch
            self.returnUrl = returnUrl
        }

        public enum Permissions: String, Codable, Hashable, Sendable {
            case balances
            case ownership
            case paymentMethod = "payment_method"
            case transactions
        }

        public enum Prefetch: String, Codable, Hashable, Sendable {
            case balances
            case ownership
            case transactions
        }

        /// The account holder to link accounts for.
        public struct AccountHolder: Codable, Hashable, Sendable {
            /// The ID of the Stripe account whose accounts you will retrieve.
            public var account: String?
            /// The ID of the Stripe customer whose accounts you will retrieve.
            public var customer: String?
            /// The ID of Account representing a customer whose accounts you will retrieve.
            public var customerAccount: String?
            /// Type of account holder to collect accounts for.
            public var `type`: Type

            public init(
                account: String? = nil,
                customer: String? = nil,
                customerAccount: String? = nil,
                `type`: Type
            ) {
                self.account = account
                self.customer = customer
                self.customerAccount = customerAccount
                self.`type` = `type`
            }

            public enum `Type`: String, Codable, Hashable, Sendable {
                case account
                case customer
            }
        }

        /// Filters to restrict the kinds of accounts to collect.
        public struct Filters: Codable, Hashable, Sendable {
            /// Restricts the Session to subcategories of accounts that can be linked.
            public var accountSubcategories: [AccountSubcategories]?
            /// List of countries from which to collect accounts.
            public var countries: [String]?
            /// Whether the session should require payment method support and successful account number retrieval before completion.
            public var requirePaymentMethodSupport: RequirePaymentMethodSupport?

            public init(
                accountSubcategories: [AccountSubcategories]? = nil,
                countries: [String]? = nil,
                requirePaymentMethodSupport: RequirePaymentMethodSupport? = nil
            ) {
                self.accountSubcategories = accountSubcategories
                self.countries = countries
                self.requirePaymentMethodSupport = requirePaymentMethodSupport
            }

            public enum AccountSubcategories: String, Codable, Hashable, Sendable {
                case checking
                case creditCard = "credit_card"
                case lineOfCredit = "line_of_credit"
                case mortgage
                case savings
            }

            public enum RequirePaymentMethodSupport: String, Codable, Hashable, Sendable {
                case all
                case atLeastOne = "at_least_one"
                case none
            }
        }

        /// Settings for configuring Session-specific limits.
        public struct Limits: Codable, Hashable, Sendable {
            /// The number of accounts that can be linked in this Session.
            public var accounts: Stripe.Clearable<Int>

            public init(
                accounts: Stripe.Clearable<Int>
            ) {
                self.accounts = accounts
            }
        }

        /// Customize manual entry behavior
        public struct ManualEntry: Codable, Hashable, Sendable {
            /// How manual entry should be handled.
            public var mode: Mode?

            public init(
                mode: Mode? = nil
            ) {
                self.mode = mode
            }

            public enum Mode: String, Codable, Hashable, Sendable {
                case automatic
                case disabled
            }
        }
    }

    public typealias Response = FinancialConnections.Session
}

// GET /v1/financial_connections/sessions/{session}
extension FinancialConnections.Session.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = FinancialConnections.Session
}
