//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: cash_balance
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Customers {
    /// A customer's `Cash balance` represents real funds.
    public struct CustomerCashBalance: Codable, Hashable, Sendable {
        /// String representing the object's type.
        public let object: String
        /// A hash of all cash balances available to this customer.
        public var available: [String: Int]?
        /// The ID of the customer whose cash balance this object represents.
        public var customer: String?
        /// The ID of an Account representing a customer whose cash balance this object represents.
        public var customerAccount: String?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        public var settings: Settings?

        public init(
            object: String,
            available: [String: Int]? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            livemode: Bool? = nil,
            settings: Settings? = nil
        ) {
            self.object = object
            self.available = available
            self.customer = customer
            self.customerAccount = customerAccount
            self.livemode = livemode
            self.settings = settings
        }

        public struct Settings: Codable, Hashable, Sendable {
            /// The configuration for how funds that land in the customer cash balance are reconciled.
            public var reconciliationMode: ReconciliationMode?
            /// A flag to indicate if reconciliation mode returned is the user's default or is specific to this customer cash balance
            public var usingMerchantDefault: Bool?

            public init(
                reconciliationMode: ReconciliationMode? = nil,
                usingMerchantDefault: Bool? = nil
            ) {
                self.reconciliationMode = reconciliationMode
                self.usingMerchantDefault = usingMerchantDefault
            }

            /// The configuration for how funds that land in the customer cash balance are reconciled.
            public enum ReconciliationMode: String, Codable, Hashable, Sendable {
                case automatic
                case manual
            }
        }
    }
}
