//
//  ExternalAccount+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.ExternalAccount {
    public enum Create {}
    public enum Delete {}
    public enum List {}
    public enum Retrieve {}
    public enum Update {}
}

// POST /v1/accounts/{account}/external_accounts
extension Stripe.ExternalAccount.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// When set to true, or if this is the first external account added in this currency, this account becomes the default ex…
        public var defaultForCurrency: Bool?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A token, like the ones returned by Stripe.js or a dictionary containing a user's external account details (with the op…
        public var externalAccount: String
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?

        public init(
            defaultForCurrency: Bool? = nil,
            expand: [String]? = nil,
            externalAccount: String,
            metadata: [String: String]? = nil
        ) {
            self.defaultForCurrency = defaultForCurrency
            self.expand = expand
            self.externalAccount = externalAccount
            self.metadata = metadata
        }
    }

    public typealias Response = Stripe.ExternalAccount
}

// DELETE /v1/accounts/{account}/external_accounts/{id}
extension Stripe.ExternalAccount.Delete {
    public typealias Response = DeletedObject<Stripe.ExternalAccount>
}

// GET /v1/accounts/{account}/external_accounts
extension Stripe.ExternalAccount.List {
    public struct Request: Codable, Hashable, Sendable {
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// Filter external accounts according to a particular object type.
        public var object: Object?
        /// A cursor for use in pagination.
        public var startingAfter: String?

        public init(
            endingBefore: String? = nil,
            expand: [String]? = nil,
            limit: Int? = nil,
            object: Object? = nil,
            startingAfter: String? = nil
        ) {
            self.endingBefore = endingBefore
            self.expand = expand
            self.limit = limit
            self.object = object
            self.startingAfter = startingAfter
        }

        public enum Object: String, Codable, Hashable, Sendable {
            case bankAccount = "bank_account"
            case card
        }
    }

    public typealias Response = Stripe.Page<Stripe.ExternalAccount>
}

// GET /v1/accounts/{account}/external_accounts/{id}
extension Stripe.ExternalAccount.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.ExternalAccount
}

// POST /v1/accounts/{account}/external_accounts/{id}
extension Stripe.ExternalAccount.Update {
    public struct Request: Codable, Hashable, Sendable {
        /// The name of the person or business that owns the bank account.
        public var accountHolderName: String?
        /// The type of entity that holds the account.
        public var accountHolderType: AccountHolderType?
        /// The bank account type.
        public var accountType: AccountType?
        /// City/District/Suburb/Town/Village.
        public var addressCity: String?
        /// Billing address country, if provided when creating card.
        public var addressCountry: String?
        /// Address line 1 (Street address/PO Box/Company name).
        public var addressLine1: String?
        /// Address line 2 (Apartment/Suite/Unit/Building).
        public var addressLine2: String?
        /// State/County/Province/Region.
        public var addressState: String?
        /// ZIP or postal code.
        public var addressZip: String?
        /// When set to true, this becomes the default external account for its currency.
        public var defaultForCurrency: Bool?
        /// Documents that may be submitted to satisfy various informational requests.
        public var documents: Documents?
        /// Two digit number representing the card’s expiration month.
        public var expMonth: String?
        /// Four digit number representing the card’s expiration year.
        public var expYear: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// Cardholder name.
        public var name: String?

        public init(
            accountHolderName: String? = nil,
            accountHolderType: AccountHolderType? = nil,
            accountType: AccountType? = nil,
            addressCity: String? = nil,
            addressCountry: String? = nil,
            addressLine1: String? = nil,
            addressLine2: String? = nil,
            addressState: String? = nil,
            addressZip: String? = nil,
            defaultForCurrency: Bool? = nil,
            documents: Documents? = nil,
            expMonth: String? = nil,
            expYear: String? = nil,
            expand: [String]? = nil,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            name: String? = nil
        ) {
            self.accountHolderName = accountHolderName
            self.accountHolderType = accountHolderType
            self.accountType = accountType
            self.addressCity = addressCity
            self.addressCountry = addressCountry
            self.addressLine1 = addressLine1
            self.addressLine2 = addressLine2
            self.addressState = addressState
            self.addressZip = addressZip
            self.defaultForCurrency = defaultForCurrency
            self.documents = documents
            self.expMonth = expMonth
            self.expYear = expYear
            self.expand = expand
            self.metadata = metadata
            self.name = name
        }

        public enum AccountHolderType: String, Codable, Hashable, Sendable {
            case value = ""
            case company
            case individual
        }

        public enum AccountType: String, Codable, Hashable, Sendable {
            case checking
            case futsu
            case savings
            case toza
        }

        /// Documents that may be submitted to satisfy various informational requests.
        public struct Documents: Codable, Hashable, Sendable {
            /// One or more documents that support the Bank account ownership verification requirement.
            public var bankAccountOwnershipVerification: BankAccountOwnershipVerification?

            public init(
                bankAccountOwnershipVerification: BankAccountOwnershipVerification? = nil
            ) {
                self.bankAccountOwnershipVerification = bankAccountOwnershipVerification
            }

            /// One or more documents that support the Bank account ownership verification requirement.
            public struct BankAccountOwnershipVerification: Codable, Hashable, Sendable {
                /// One or more document ids returned by a file upload with a `purpose` value of `account_requirement`.
                public var files: [String]?

                public init(
                    files: [String]? = nil
                ) {
                    self.files = files
                }
            }
        }
    }

    public typealias Response = Stripe.ExternalAccount
}
