//
//  PaymentRecord+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.PaymentRecord {
    public enum List {}
    public enum ReportPayment {}
    public enum ReportPaymentAttempt {}
    public enum ReportPaymentAttemptCanceled {}
    public enum ReportPaymentAttemptFailed {}
    public enum ReportPaymentAttemptGuaranteed {}
    public enum ReportPaymentAttemptInformational {}
    public enum ReportRefund {}
    public enum Retrieve {}
}

// GET /v1/payment_records
extension Stripe.PaymentRecord.List {
    public struct Request: Codable, Hashable, Sendable {
        /// Only return Payment Records that were created after this unix timestamp.
        public var createdAfter: Date?
        /// Only return Payment Records that were created before this unix timestamp.
        public var createdBefore: Date?
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// A cursor for use in pagination.
        public var startingAfter: String?

        private enum CodingKeys: String, CodingKey {
            case createdAfter
            case createdBefore
            case endingBefore
            case expand
            case limit
            case startingAfter
        }

        public init(
            createdAfter: Date? = nil,
            createdBefore: Date? = nil,
            endingBefore: String? = nil,
            expand: [String]? = nil,
            limit: Int? = nil,
            startingAfter: String? = nil
        ) {
            self.createdAfter = createdAfter
            self.createdBefore = createdBefore
            self.endingBefore = endingBefore
            self.expand = expand
            self.limit = limit
            self.startingAfter = startingAfter
        }
    }

    public typealias Response = Stripe.Page<Stripe.PaymentRecord>
}

// POST /v1/payment_records/report_payment
extension Stripe.PaymentRecord.ReportPayment {
    public struct Request: Codable, Hashable, Sendable {
        /// The amount you initially requested for this payment.
        public var amountRequested: AmountRequested
        /// Customer information for this payment.
        public var customerDetails: CustomerDetails?
        /// Indicates whether the customer was present in your checkout flow during this payment.
        public var customerPresence: CustomerPresence?
        /// An arbitrary string attached to the object.
        public var description: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Information about the payment attempt failure.
        public var failed: Failed?
        /// Information about the payment attempt guarantee.
        public var guaranteed: Guaranteed?
        /// When the reported payment was initiated.
        public var initiatedAt: Date
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// The outcome of the reported payment.
        public var outcome: Outcome?
        /// Information about the Payment Method debited for this payment.
        public var paymentMethodDetails: PaymentMethodDetails
        /// Processor information for this payment.
        public var processorDetails: ProcessorDetails?
        /// Shipping information for this payment.
        public var shippingDetails: ShippingDetails?

        private enum CodingKeys: String, CodingKey {
            case amountRequested
            case customerDetails
            case customerPresence
            case description
            case expand
            case failed
            case guaranteed
            case initiatedAt
            case metadata
            case outcome
            case paymentMethodDetails
            case processorDetails
            case shippingDetails
        }

        public init(
            amountRequested: AmountRequested,
            customerDetails: CustomerDetails? = nil,
            customerPresence: CustomerPresence? = nil,
            description: String? = nil,
            expand: [String]? = nil,
            failed: Failed? = nil,
            guaranteed: Guaranteed? = nil,
            initiatedAt: Date,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            outcome: Outcome? = nil,
            paymentMethodDetails: PaymentMethodDetails,
            processorDetails: ProcessorDetails? = nil,
            shippingDetails: ShippingDetails? = nil
        ) {
            self.amountRequested = amountRequested
            self.customerDetails = customerDetails
            self.customerPresence = customerPresence
            self.description = description
            self.expand = expand
            self.failed = failed
            self.guaranteed = guaranteed
            self.initiatedAt = initiatedAt
            self.metadata = metadata
            self.outcome = outcome
            self.paymentMethodDetails = paymentMethodDetails
            self.processorDetails = processorDetails
            self.shippingDetails = shippingDetails
        }

        public enum CustomerPresence: String, Codable, Hashable, Sendable {
            case offSession = "off_session"
            case onSession = "on_session"
        }

        public enum Outcome: String, Codable, Hashable, Sendable {
            case failed
            case guaranteed
        }

        /// The amount you initially requested for this payment.
        public struct AmountRequested: Codable, Hashable, Sendable {
            /// Three-letter ISO currency code, in lowercase.
            public var currency: Stripe.Currency
            /// A positive integer representing the amount in the currency's minor unit.
            public var value: Int

            private enum CodingKeys: String, CodingKey {
                case currency
                case value
            }

            public init(
                currency: Stripe.Currency,
                value: Int
            ) {
                self.currency = currency
                self.value = value
            }
        }

        /// Customer information for this payment.
        public struct CustomerDetails: Codable, Hashable, Sendable {
            /// The customer who made the payment.
            public var customer: String?
            /// The customer's phone number.
            public var email: String?
            /// The customer's name.
            public var name: String?
            /// The customer's phone number.
            public var phone: String?

            private enum CodingKeys: String, CodingKey {
                case customer
                case email
                case name
                case phone
            }

            public init(
                customer: String? = nil,
                email: String? = nil,
                name: String? = nil,
                phone: String? = nil
            ) {
                self.customer = customer
                self.email = email
                self.name = name
                self.phone = phone
            }
        }

        /// Information about the payment attempt failure.
        public struct Failed: Codable, Hashable, Sendable {
            /// When the reported payment failed.
            public var failedAt: Date

            private enum CodingKeys: String, CodingKey {
                case failedAt
            }

            public init(
                failedAt: Date
            ) {
                self.failedAt = failedAt
            }
        }

        /// Information about the payment attempt guarantee.
        public struct Guaranteed: Codable, Hashable, Sendable {
            /// When the reported payment was guaranteed.
            public var guaranteedAt: Date

            private enum CodingKeys: String, CodingKey {
                case guaranteedAt
            }

            public init(
                guaranteedAt: Date
            ) {
                self.guaranteedAt = guaranteedAt
            }
        }

        /// Information about the Payment Method debited for this payment.
        public struct PaymentMethodDetails: Codable, Hashable, Sendable {
            /// The billing details associated with the method of payment.
            public var billingDetails: BillingDetails?
            /// Information about the custom (user-defined) payment method used to make this payment.
            public var custom: Custom?
            /// ID of the Stripe Payment Method used to make this payment.
            public var paymentMethod: String?
            /// The type of the payment method details.
            public var `type`: String?

            private enum CodingKeys: String, CodingKey {
                case billingDetails
                case custom
                case paymentMethod
                case `type`
            }

            public init(
                billingDetails: BillingDetails? = nil,
                custom: Custom? = nil,
                paymentMethod: String? = nil,
                `type`: String? = nil
            ) {
                self.billingDetails = billingDetails
                self.custom = custom
                self.paymentMethod = paymentMethod
                self.`type` = `type`
            }

            /// The billing details associated with the method of payment.
            public struct BillingDetails: Codable, Hashable, Sendable {
                /// The billing address associated with the method of payment.
                public var address: Address?
                /// The billing email associated with the method of payment.
                public var email: String?
                /// The billing name associated with the method of payment.
                public var name: String?
                /// The billing phone number associated with the method of payment.
                public var phone: String?

                private enum CodingKeys: String, CodingKey {
                    case address
                    case email
                    case name
                    case phone
                }

                public init(
                    address: Address? = nil,
                    email: String? = nil,
                    name: String? = nil,
                    phone: String? = nil
                ) {
                    self.address = address
                    self.email = email
                    self.name = name
                    self.phone = phone
                }

                /// The billing address associated with the method of payment.
                public struct Address: Codable, Hashable, Sendable {
                    /// City, district, suburb, town, or village.
                    public var city: String?
                    /// Two-letter country code (ISO 3166-1 alpha-2).
                    public var country: String?
                    /// Address line 1, such as the street, PO Box, or company name.
                    public var line1: String?
                    /// Address line 2, such as the apartment, suite, unit, or building.
                    public var line2: String?
                    /// ZIP or postal code.
                    public var postalCode: String?
                    /// State, county, province, or region (ISO 3166-2).
                    public var state: String?

                    private enum CodingKeys: String, CodingKey {
                        case city
                        case country
                        case line1
                        case line2
                        case postalCode
                        case state
                    }

                    public init(
                        city: String? = nil,
                        country: String? = nil,
                        line1: String? = nil,
                        line2: String? = nil,
                        postalCode: String? = nil,
                        state: String? = nil
                    ) {
                        self.city = city
                        self.country = country
                        self.line1 = line1
                        self.line2 = line2
                        self.postalCode = postalCode
                        self.state = state
                    }
                }
            }

            /// Information about the custom (user-defined) payment method used to make this payment.
            public struct Custom: Codable, Hashable, Sendable {
                /// Display name for the custom (user-defined) payment method type used to make this payment.
                public var displayName: String?
                /// The custom payment method type associated with this payment.
                public var `type`: String?

                private enum CodingKeys: String, CodingKey {
                    case displayName
                    case `type`
                }

                public init(
                    displayName: String? = nil,
                    `type`: String? = nil
                ) {
                    self.displayName = displayName
                    self.`type` = `type`
                }
            }
        }

        /// Processor information for this payment.
        public struct ProcessorDetails: Codable, Hashable, Sendable {
            /// Information about the custom processor used to make this payment.
            public var custom: Custom?
            /// The type of the processor details.
            public var `type`: String

            private enum CodingKeys: String, CodingKey {
                case custom
                case `type`
            }

            public init(
                custom: Custom? = nil,
                `type`: String
            ) {
                self.custom = custom
                self.`type` = `type`
            }

            /// Information about the custom processor used to make this payment.
            public struct Custom: Codable, Hashable, Sendable {
                /// An opaque string for manual reconciliation of this payment, for example a check number or a payment processor ID.
                public var paymentReference: String

                private enum CodingKeys: String, CodingKey {
                    case paymentReference
                }

                public init(
                    paymentReference: String
                ) {
                    self.paymentReference = paymentReference
                }
            }
        }

        /// Shipping information for this payment.
        public struct ShippingDetails: Codable, Hashable, Sendable {
            /// The physical shipping address.
            public var address: Address?
            /// The shipping recipient's name.
            public var name: String?
            /// The shipping recipient's phone number.
            public var phone: String?

            private enum CodingKeys: String, CodingKey {
                case address
                case name
                case phone
            }

            public init(
                address: Address? = nil,
                name: String? = nil,
                phone: String? = nil
            ) {
                self.address = address
                self.name = name
                self.phone = phone
            }

            /// The physical shipping address.
            public struct Address: Codable, Hashable, Sendable {
                /// City, district, suburb, town, or village.
                public var city: String?
                /// Two-letter country code (ISO 3166-1 alpha-2).
                public var country: String?
                /// Address line 1, such as the street, PO Box, or company name.
                public var line1: String?
                /// Address line 2, such as the apartment, suite, unit, or building.
                public var line2: String?
                /// ZIP or postal code.
                public var postalCode: String?
                /// State, county, province, or region (ISO 3166-2).
                public var state: String?

                private enum CodingKeys: String, CodingKey {
                    case city
                    case country
                    case line1
                    case line2
                    case postalCode
                    case state
                }

                public init(
                    city: String? = nil,
                    country: String? = nil,
                    line1: String? = nil,
                    line2: String? = nil,
                    postalCode: String? = nil,
                    state: String? = nil
                ) {
                    self.city = city
                    self.country = country
                    self.line1 = line1
                    self.line2 = line2
                    self.postalCode = postalCode
                    self.state = state
                }
            }
        }
    }

    public typealias Response = Stripe.PaymentRecord
}

// POST /v1/payment_records/{id}/report_payment_attempt
extension Stripe.PaymentRecord.ReportPaymentAttempt {
    public struct Request: Codable, Hashable, Sendable {
        /// An arbitrary string attached to the object.
        public var description: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Information about the payment attempt failure.
        public var failed: Failed?
        /// Information about the payment attempt guarantee.
        public var guaranteed: Guaranteed?
        /// When the reported payment was initiated.
        public var initiatedAt: Date
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// The outcome of the reported payment.
        public var outcome: Outcome?
        /// Information about the Payment Method debited for this payment.
        public var paymentMethodDetails: PaymentMethodDetails?
        /// Shipping information for this payment.
        public var shippingDetails: ShippingDetails?

        private enum CodingKeys: String, CodingKey {
            case description
            case expand
            case failed
            case guaranteed
            case initiatedAt
            case metadata
            case outcome
            case paymentMethodDetails
            case shippingDetails
        }

        public init(
            description: String? = nil,
            expand: [String]? = nil,
            failed: Failed? = nil,
            guaranteed: Guaranteed? = nil,
            initiatedAt: Date,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            outcome: Outcome? = nil,
            paymentMethodDetails: PaymentMethodDetails? = nil,
            shippingDetails: ShippingDetails? = nil
        ) {
            self.description = description
            self.expand = expand
            self.failed = failed
            self.guaranteed = guaranteed
            self.initiatedAt = initiatedAt
            self.metadata = metadata
            self.outcome = outcome
            self.paymentMethodDetails = paymentMethodDetails
            self.shippingDetails = shippingDetails
        }

        public enum Outcome: String, Codable, Hashable, Sendable {
            case failed
            case guaranteed
        }

        /// Information about the payment attempt failure.
        public struct Failed: Codable, Hashable, Sendable {
            /// When the reported payment failed.
            public var failedAt: Date

            private enum CodingKeys: String, CodingKey {
                case failedAt
            }

            public init(
                failedAt: Date
            ) {
                self.failedAt = failedAt
            }
        }

        /// Information about the payment attempt guarantee.
        public struct Guaranteed: Codable, Hashable, Sendable {
            /// When the reported payment was guaranteed.
            public var guaranteedAt: Date

            private enum CodingKeys: String, CodingKey {
                case guaranteedAt
            }

            public init(
                guaranteedAt: Date
            ) {
                self.guaranteedAt = guaranteedAt
            }
        }

        /// Information about the Payment Method debited for this payment.
        public struct PaymentMethodDetails: Codable, Hashable, Sendable {
            /// The billing details associated with the method of payment.
            public var billingDetails: BillingDetails?
            /// Information about the custom (user-defined) payment method used to make this payment.
            public var custom: Custom?
            /// ID of the Stripe Payment Method used to make this payment.
            public var paymentMethod: String?
            /// The type of the payment method details.
            public var `type`: String?

            private enum CodingKeys: String, CodingKey {
                case billingDetails
                case custom
                case paymentMethod
                case `type`
            }

            public init(
                billingDetails: BillingDetails? = nil,
                custom: Custom? = nil,
                paymentMethod: String? = nil,
                `type`: String? = nil
            ) {
                self.billingDetails = billingDetails
                self.custom = custom
                self.paymentMethod = paymentMethod
                self.`type` = `type`
            }

            /// The billing details associated with the method of payment.
            public struct BillingDetails: Codable, Hashable, Sendable {
                /// The billing address associated with the method of payment.
                public var address: Address?
                /// The billing email associated with the method of payment.
                public var email: String?
                /// The billing name associated with the method of payment.
                public var name: String?
                /// The billing phone number associated with the method of payment.
                public var phone: String?

                private enum CodingKeys: String, CodingKey {
                    case address
                    case email
                    case name
                    case phone
                }

                public init(
                    address: Address? = nil,
                    email: String? = nil,
                    name: String? = nil,
                    phone: String? = nil
                ) {
                    self.address = address
                    self.email = email
                    self.name = name
                    self.phone = phone
                }

                /// The billing address associated with the method of payment.
                public struct Address: Codable, Hashable, Sendable {
                    /// City, district, suburb, town, or village.
                    public var city: String?
                    /// Two-letter country code (ISO 3166-1 alpha-2).
                    public var country: String?
                    /// Address line 1, such as the street, PO Box, or company name.
                    public var line1: String?
                    /// Address line 2, such as the apartment, suite, unit, or building.
                    public var line2: String?
                    /// ZIP or postal code.
                    public var postalCode: String?
                    /// State, county, province, or region (ISO 3166-2).
                    public var state: String?

                    private enum CodingKeys: String, CodingKey {
                        case city
                        case country
                        case line1
                        case line2
                        case postalCode
                        case state
                    }

                    public init(
                        city: String? = nil,
                        country: String? = nil,
                        line1: String? = nil,
                        line2: String? = nil,
                        postalCode: String? = nil,
                        state: String? = nil
                    ) {
                        self.city = city
                        self.country = country
                        self.line1 = line1
                        self.line2 = line2
                        self.postalCode = postalCode
                        self.state = state
                    }
                }
            }

            /// Information about the custom (user-defined) payment method used to make this payment.
            public struct Custom: Codable, Hashable, Sendable {
                /// Display name for the custom (user-defined) payment method type used to make this payment.
                public var displayName: String?
                /// The custom payment method type associated with this payment.
                public var `type`: String?

                private enum CodingKeys: String, CodingKey {
                    case displayName
                    case `type`
                }

                public init(
                    displayName: String? = nil,
                    `type`: String? = nil
                ) {
                    self.displayName = displayName
                    self.`type` = `type`
                }
            }
        }

        /// Shipping information for this payment.
        public struct ShippingDetails: Codable, Hashable, Sendable {
            /// The physical shipping address.
            public var address: Address?
            /// The shipping recipient's name.
            public var name: String?
            /// The shipping recipient's phone number.
            public var phone: String?

            private enum CodingKeys: String, CodingKey {
                case address
                case name
                case phone
            }

            public init(
                address: Address? = nil,
                name: String? = nil,
                phone: String? = nil
            ) {
                self.address = address
                self.name = name
                self.phone = phone
            }

            /// The physical shipping address.
            public struct Address: Codable, Hashable, Sendable {
                /// City, district, suburb, town, or village.
                public var city: String?
                /// Two-letter country code (ISO 3166-1 alpha-2).
                public var country: String?
                /// Address line 1, such as the street, PO Box, or company name.
                public var line1: String?
                /// Address line 2, such as the apartment, suite, unit, or building.
                public var line2: String?
                /// ZIP or postal code.
                public var postalCode: String?
                /// State, county, province, or region (ISO 3166-2).
                public var state: String?

                private enum CodingKeys: String, CodingKey {
                    case city
                    case country
                    case line1
                    case line2
                    case postalCode
                    case state
                }

                public init(
                    city: String? = nil,
                    country: String? = nil,
                    line1: String? = nil,
                    line2: String? = nil,
                    postalCode: String? = nil,
                    state: String? = nil
                ) {
                    self.city = city
                    self.country = country
                    self.line1 = line1
                    self.line2 = line2
                    self.postalCode = postalCode
                    self.state = state
                }
            }
        }
    }

    public typealias Response = Stripe.PaymentRecord
}

// POST /v1/payment_records/{id}/report_payment_attempt_canceled
extension Stripe.PaymentRecord.ReportPaymentAttemptCanceled {
    public struct Request: Codable, Hashable, Sendable {
        /// When the reported payment was canceled.
        public var canceledAt: Date
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?

        private enum CodingKeys: String, CodingKey {
            case canceledAt
            case expand
            case metadata
        }

        public init(
            canceledAt: Date,
            expand: [String]? = nil,
            metadata: Stripe.Clearable<[String: String]>? = nil
        ) {
            self.canceledAt = canceledAt
            self.expand = expand
            self.metadata = metadata
        }
    }

    public typealias Response = Stripe.PaymentRecord
}

// POST /v1/payment_records/{id}/report_payment_attempt_failed
extension Stripe.PaymentRecord.ReportPaymentAttemptFailed {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// When the reported payment failed.
        public var failedAt: Date
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?

        private enum CodingKeys: String, CodingKey {
            case expand
            case failedAt
            case metadata
        }

        public init(
            expand: [String]? = nil,
            failedAt: Date,
            metadata: Stripe.Clearable<[String: String]>? = nil
        ) {
            self.expand = expand
            self.failedAt = failedAt
            self.metadata = metadata
        }
    }

    public typealias Response = Stripe.PaymentRecord
}

// POST /v1/payment_records/{id}/report_payment_attempt_guaranteed
extension Stripe.PaymentRecord.ReportPaymentAttemptGuaranteed {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// When the reported payment was guaranteed.
        public var guaranteedAt: Date
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?

        private enum CodingKeys: String, CodingKey {
            case expand
            case guaranteedAt
            case metadata
        }

        public init(
            expand: [String]? = nil,
            guaranteedAt: Date,
            metadata: Stripe.Clearable<[String: String]>? = nil
        ) {
            self.expand = expand
            self.guaranteedAt = guaranteedAt
            self.metadata = metadata
        }
    }

    public typealias Response = Stripe.PaymentRecord
}

// POST /v1/payment_records/{id}/report_payment_attempt_informational
extension Stripe.PaymentRecord.ReportPaymentAttemptInformational {
    public struct Request: Codable, Hashable, Sendable {
        /// Customer information for this payment.
        public var customerDetails: CustomerDetails?
        /// An arbitrary string attached to the object.
        public var description: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// Shipping information for this payment.
        public var shippingDetails: Stripe.Clearable<ShippingDetails>?

        private enum CodingKeys: String, CodingKey {
            case customerDetails
            case description
            case expand
            case metadata
            case shippingDetails
        }

        public init(
            customerDetails: CustomerDetails? = nil,
            description: String? = nil,
            expand: [String]? = nil,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            shippingDetails: Stripe.Clearable<ShippingDetails>? = nil
        ) {
            self.customerDetails = customerDetails
            self.description = description
            self.expand = expand
            self.metadata = metadata
            self.shippingDetails = shippingDetails
        }

        /// Customer information for this payment.
        public struct CustomerDetails: Codable, Hashable, Sendable {
            /// The customer who made the payment.
            public var customer: String?
            /// The customer's phone number.
            public var email: String?
            /// The customer's name.
            public var name: String?
            /// The customer's phone number.
            public var phone: String?

            private enum CodingKeys: String, CodingKey {
                case customer
                case email
                case name
                case phone
            }

            public init(
                customer: String? = nil,
                email: String? = nil,
                name: String? = nil,
                phone: String? = nil
            ) {
                self.customer = customer
                self.email = email
                self.name = name
                self.phone = phone
            }
        }

        public struct ShippingDetails: Codable, Hashable, Sendable {
            /// The physical shipping address.
            public var address: Address?
            /// The shipping recipient's name.
            public var name: String?
            /// The shipping recipient's phone number.
            public var phone: String?

            private enum CodingKeys: String, CodingKey {
                case address
                case name
                case phone
            }

            public init(
                address: Address? = nil,
                name: String? = nil,
                phone: String? = nil
            ) {
                self.address = address
                self.name = name
                self.phone = phone
            }

            /// The physical shipping address.
            public struct Address: Codable, Hashable, Sendable {
                /// City, district, suburb, town, or village.
                public var city: String?
                /// Two-letter country code (ISO 3166-1 alpha-2).
                public var country: String?
                /// Address line 1, such as the street, PO Box, or company name.
                public var line1: String?
                /// Address line 2, such as the apartment, suite, unit, or building.
                public var line2: String?
                /// ZIP or postal code.
                public var postalCode: String?
                /// State, county, province, or region (ISO 3166-2).
                public var state: String?

                private enum CodingKeys: String, CodingKey {
                    case city
                    case country
                    case line1
                    case line2
                    case postalCode
                    case state
                }

                public init(
                    city: String? = nil,
                    country: String? = nil,
                    line1: String? = nil,
                    line2: String? = nil,
                    postalCode: String? = nil,
                    state: String? = nil
                ) {
                    self.city = city
                    self.country = country
                    self.line1 = line1
                    self.line2 = line2
                    self.postalCode = postalCode
                    self.state = state
                }
            }
        }
    }

    public typealias Response = Stripe.PaymentRecord
}

// POST /v1/payment_records/{id}/report_refund
extension Stripe.PaymentRecord.ReportRefund {
    public struct Request: Codable, Hashable, Sendable {
        /// A positive integer in the smallest currency unit representing how much of this payment to refund.
        public var amount: Amount?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// When the reported refund was initiated.
        public var initiatedAt: Date?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// The outcome of the reported refund.
        public var outcome: String
        /// Processor information for this refund.
        public var processorDetails: ProcessorDetails
        /// Information about the payment attempt refund.
        public var refunded: Refunded?

        private enum CodingKeys: String, CodingKey {
            case amount
            case expand
            case initiatedAt
            case metadata
            case outcome
            case processorDetails
            case refunded
        }

        public init(
            amount: Amount? = nil,
            expand: [String]? = nil,
            initiatedAt: Date? = nil,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            outcome: String,
            processorDetails: ProcessorDetails,
            refunded: Refunded? = nil
        ) {
            self.amount = amount
            self.expand = expand
            self.initiatedAt = initiatedAt
            self.metadata = metadata
            self.outcome = outcome
            self.processorDetails = processorDetails
            self.refunded = refunded
        }

        /// A positive integer in the smallest currency unit representing how much of this payment to refund.
        public struct Amount: Codable, Hashable, Sendable {
            /// Three-letter ISO currency code, in lowercase.
            public var currency: Stripe.Currency
            /// A positive integer representing the amount in the currency's minor unit.
            public var value: Int

            private enum CodingKeys: String, CodingKey {
                case currency
                case value
            }

            public init(
                currency: Stripe.Currency,
                value: Int
            ) {
                self.currency = currency
                self.value = value
            }
        }

        /// Processor information for this refund.
        public struct ProcessorDetails: Codable, Hashable, Sendable {
            /// Information about the custom processor used to make this refund.
            public var custom: Custom?
            /// The type of the processor details.
            public var `type`: String

            private enum CodingKeys: String, CodingKey {
                case custom
                case `type`
            }

            public init(
                custom: Custom? = nil,
                `type`: String
            ) {
                self.custom = custom
                self.`type` = `type`
            }

            /// Information about the custom processor used to make this refund.
            public struct Custom: Codable, Hashable, Sendable {
                /// A reference to the external refund.
                public var refundReference: String

                private enum CodingKeys: String, CodingKey {
                    case refundReference
                }

                public init(
                    refundReference: String
                ) {
                    self.refundReference = refundReference
                }
            }
        }

        /// Information about the payment attempt refund.
        public struct Refunded: Codable, Hashable, Sendable {
            /// When the reported refund completed.
            public var refundedAt: Date

            private enum CodingKeys: String, CodingKey {
                case refundedAt
            }

            public init(
                refundedAt: Date
            ) {
                self.refundedAt = refundedAt
            }
        }
    }

    public typealias Response = Stripe.PaymentRecord
}

// GET /v1/payment_records/{id}
extension Stripe.PaymentRecord.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        private enum CodingKeys: String, CodingKey {
            case expand
        }

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.PaymentRecord
}
