//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: issuing.physical_bundle
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Issuing {
    /// A Physical Bundle represents the bundle of physical items - card stock, carrier letter, and envelope - that is shipped…
    public struct PhysicalBundle: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        public var features: Features?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// Friendly display name.
        public var name: String?
        /// Whether this physical bundle can be used to create cards.
        public var status: Status?
        /// Whether this physical bundle is a standard Stripe offering or custom-made for you.
        public var `type`: Type?

        public init(
            id: ID,
            object: String,
            features: Features? = nil,
            livemode: Bool? = nil,
            name: String? = nil,
            status: Status? = nil,
            `type`: Type? = nil
        ) {
            self.id = id
            self.object = object
            self.features = features
            self.livemode = livemode
            self.name = name
            self.status = status
            self.`type` = `type`
        }

        /// Whether this physical bundle can be used to create cards.
        public enum Status: String, Codable, Hashable, Sendable {
            case active
            case inactive
            case review
        }

        /// Whether this physical bundle is a standard Stripe offering or custom-made for you.
        public enum `Type`: String, Codable, Hashable, Sendable {
            case custom
            case standard
        }

        public struct Features: Codable, Hashable, Sendable {
            /// The policy for how to use card logo images in a card design with this physical bundle.
            public var cardLogo: CardLogo?
            /// The policy for how to use carrier letter text in a card design with this physical bundle.
            public var carrierText: CarrierText?
            /// The policy for how to use a second line on a card with this physical bundle.
            public var secondLine: SecondLine?

            public init(
                cardLogo: CardLogo? = nil,
                carrierText: CarrierText? = nil,
                secondLine: SecondLine? = nil
            ) {
                self.cardLogo = cardLogo
                self.carrierText = carrierText
                self.secondLine = secondLine
            }

            /// The policy for how to use card logo images in a card design with this physical bundle.
            public enum CardLogo: String, Codable, Hashable, Sendable {
                case optional
                case required
                case unsupported
            }

            /// The policy for how to use carrier letter text in a card design with this physical bundle.
            public enum CarrierText: String, Codable, Hashable, Sendable {
                case optional
                case required
                case unsupported
            }

            /// The policy for how to use a second line on a card with this physical bundle.
            public enum SecondLine: String, Codable, Hashable, Sendable {
                case optional
                case required
                case unsupported
            }
        }
    }
}
