//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: capability
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Connect {
    /// This is an object representing a capability for a Stripe account.
    public struct Capability: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// The account for which the capability enables functionality.
        @Expandable<Stripe.Connect.Account, String> public var account: String?
        public var futureRequirements: FutureRequirements?
        /// Whether the capability has been requested.
        public var requested: Bool?
        /// Time at which the capability was requested.
        public var requestedAt: Date?
        public var requirements: Requirements?
        /// The status of the capability.
        public var status: Status?

        public init(
            id: ID,
            object: String,
            account: String? = nil,
            futureRequirements: FutureRequirements? = nil,
            requested: Bool? = nil,
            requestedAt: Date? = nil,
            requirements: Requirements? = nil,
            status: Status? = nil
        ) {
            self.id = id
            self.object = object
            self._account = Expandable(id: account)
            self.futureRequirements = futureRequirements
            self.requested = requested
            self.requestedAt = requestedAt
            self.requirements = requirements
            self.status = status
        }

        /// The status of the capability.
        public enum Status: String, Codable, Hashable, Sendable {
            case active
            case inactive
            case pending
            case unrequested
        }

        public struct FutureRequirements: Codable, Hashable, Sendable {
            /// Fields that are due and can be resolved by providing the corresponding alternative fields instead.
            public var alternatives: [Stripe.Shared.Alternatives]?
            /// Date on which `future_requirements` becomes the main `requirements` hash and `future_requirements` becomes empty.
            public var currentDeadline: Date?
            /// Fields that need to be resolved to keep the capability enabled.
            public var currentlyDue: [String]?
            /// This is typed as an enum for consistency with `requirements.disabled_reason`, but it safe to assume `future_requiremen…
            public var disabledReason: DisabledReason?
            /// Fields that are `currently_due` and need to be collected again because validation or verification failed.
            public var errors: [Stripe.Shared.Errors]?
            /// Fields you must collect when all thresholds are reached.
            public var eventuallyDue: [String]?
            /// Fields that haven't been resolved by `requirements.current_deadline`.
            public var pastDue: [String]?
            /// Fields that are being reviewed, or might become required depending on the results of a review.
            public var pendingVerification: [String]?

            public init(
                alternatives: [Stripe.Shared.Alternatives]? = nil,
                currentDeadline: Date? = nil,
                currentlyDue: [String]? = nil,
                disabledReason: DisabledReason? = nil,
                errors: [Stripe.Shared.Errors]? = nil,
                eventuallyDue: [String]? = nil,
                pastDue: [String]? = nil,
                pendingVerification: [String]? = nil
            ) {
                self.alternatives = alternatives
                self.currentDeadline = currentDeadline
                self.currentlyDue = currentlyDue
                self.disabledReason = disabledReason
                self.errors = errors
                self.eventuallyDue = eventuallyDue
                self.pastDue = pastDue
                self.pendingVerification = pendingVerification
            }

            /// This is typed as an enum for consistency with `requirements.disabled_reason`, but it safe to assume `future_requiremen…
            public enum DisabledReason: String, Codable, Hashable, Sendable {
                case other
                case pausedInactivity = "paused.inactivity"
                case pendingOnboarding = "pending.onboarding"
                case pendingReview = "pending.review"
                case platformDisabled = "platform_disabled"
                case platformPaused = "platform_paused"
                case rejectedInactivity = "rejected.inactivity"
                case rejectedOther = "rejected.other"
                case rejectedUnsupportedBusiness = "rejected.unsupported_business"
                case requirementsFieldsNeeded = "requirements.fields_needed"
            }
        }

        public struct Requirements: Codable, Hashable, Sendable {
            /// Fields that are due and can be resolved by providing the corresponding alternative fields instead.
            public var alternatives: [Stripe.Shared.Alternatives]?
            /// The date by which all required account information must be both submitted and verified.
            public var currentDeadline: Date?
            /// Fields that need to be resolved to keep the capability enabled.
            public var currentlyDue: [String]?
            /// Description of why the capability is disabled.
            public var disabledReason: DisabledReason?
            /// Fields that are `currently_due` and need to be collected again because validation or verification failed.
            public var errors: [Stripe.Shared.Errors]?
            /// Fields you must collect when all thresholds are reached.
            public var eventuallyDue: [String]?
            /// Fields that haven't been resolved by `current_deadline`.
            public var pastDue: [String]?
            /// Fields that are being reviewed, or might become required depending on the results of a review.
            public var pendingVerification: [String]?

            public init(
                alternatives: [Stripe.Shared.Alternatives]? = nil,
                currentDeadline: Date? = nil,
                currentlyDue: [String]? = nil,
                disabledReason: DisabledReason? = nil,
                errors: [Stripe.Shared.Errors]? = nil,
                eventuallyDue: [String]? = nil,
                pastDue: [String]? = nil,
                pendingVerification: [String]? = nil
            ) {
                self.alternatives = alternatives
                self.currentDeadline = currentDeadline
                self.currentlyDue = currentlyDue
                self.disabledReason = disabledReason
                self.errors = errors
                self.eventuallyDue = eventuallyDue
                self.pastDue = pastDue
                self.pendingVerification = pendingVerification
            }

            /// Description of why the capability is disabled.
            public enum DisabledReason: String, Codable, Hashable, Sendable {
                case other
                case pausedInactivity = "paused.inactivity"
                case pendingOnboarding = "pending.onboarding"
                case pendingReview = "pending.review"
                case platformDisabled = "platform_disabled"
                case platformPaused = "platform_paused"
                case rejectedInactivity = "rejected.inactivity"
                case rejectedOther = "rejected.other"
                case rejectedUnsupportedBusiness = "rejected.unsupported_business"
                case requirementsFieldsNeeded = "requirements.fields_needed"
            }
        }
    }
}
