//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: transfer
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Connect {
    /// A `Transfer` object is created when you move funds between Stripe accounts as part of Connect.
    public struct Transfer: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Amount in cents (or local equivalent) to be transferred.
        public var amount: Int?
        /// Amount in cents (or local equivalent) reversed (can be less than the amount attribute on the transfer if a partial rev…
        public var amountReversed: Int?
        /// Balance transaction that describes the impact of this transfer on your account balance.
        @Expandable<Stripe.Balance.Transaction, String> public var balanceTransaction: String?
        /// Time that this record of the transfer was first created.
        public var created: Date?
        /// Three-letter ISO currency code, in lowercase.
        public var currency: Stripe.Currency?
        /// An arbitrary string attached to the object.
        public var description: String?
        /// ID of the Stripe account the transfer was sent to.
        @Expandable<Stripe.Connect.Account, String> public var destination: String?
        /// If the destination is a Stripe account, this will be the ID of the payment that the destination account received for t…
        @Expandable<Stripe.Charges.Charge, String> public var destinationPayment: String?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?
        /// A list of reversals that have been applied to the transfer.
        public var reversals: Reversals?
        /// Whether the transfer has been fully reversed.
        public var reversed: Bool?
        /// ID of the charge that was used to fund the transfer.
        @Expandable<Stripe.Charges.Charge, String> public var sourceTransaction: String?
        /// The source balance this transfer came from.
        public var sourceType: String?
        /// A string that identifies this transaction as part of a group.
        public var transferGroup: String?

        public init(
            id: ID,
            object: String,
            amount: Int? = nil,
            amountReversed: Int? = nil,
            balanceTransaction: String? = nil,
            created: Date? = nil,
            currency: Stripe.Currency? = nil,
            description: String? = nil,
            destination: String? = nil,
            destinationPayment: String? = nil,
            livemode: Bool? = nil,
            metadata: [String: String]? = nil,
            reversals: Reversals? = nil,
            reversed: Bool? = nil,
            sourceTransaction: String? = nil,
            sourceType: String? = nil,
            transferGroup: String? = nil
        ) {
            self.id = id
            self.object = object
            self.amount = amount
            self.amountReversed = amountReversed
            self._balanceTransaction = Expandable(id: balanceTransaction)
            self.created = created
            self.currency = currency
            self.description = description
            self._destination = Expandable(id: destination)
            self._destinationPayment = Expandable(id: destinationPayment)
            self.livemode = livemode
            self.metadata = metadata
            self.reversals = reversals
            self.reversed = reversed
            self._sourceTransaction = Expandable(id: sourceTransaction)
            self.sourceType = sourceType
            self.transferGroup = transferGroup
        }

        /// A list of reversals that have been applied to the transfer.
        public struct Reversals: Codable, Hashable, Sendable {
            /// String representing the object's type.
            public let object: String
            /// Details about each object.
            public var data: [Stripe.Connect.Transfer.Reversal]?
            /// True if this list has another page of items after this one that can be fetched.
            public var hasMore: Bool?
            /// The URL where this list can be accessed.
            public var url: String?

            public init(
                object: String,
                data: [Stripe.Connect.Transfer.Reversal]? = nil,
                hasMore: Bool? = nil,
                url: String? = nil
            ) {
                self.object = object
                self.data = data
                self.hasMore = hasMore
                self.url = url
            }
        }
    }
}
