//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: test_helpers.test_clock
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing.TestClocks {
    /// A test clock enables deterministic control over objects in testmode.
    public struct TestClock: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Time at which the object was created.
        public var created: Date?
        /// Time at which this clock is scheduled to auto delete.
        public var deletesAfter: Date?
        /// Time at which all objects belonging to this clock are frozen.
        public var frozenTime: Date?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// The custom name supplied at creation.
        public var name: String?
        /// The status of the Test Clock.
        public var status: Status?
        public var statusDetails: StatusDetails?

        private enum CodingKeys: String, CodingKey {
            case id
            case object
            case created
            case deletesAfter
            case frozenTime
            case livemode
            case name
            case status
            case statusDetails
        }

        public init(
            id: ID,
            object: String,
            created: Date? = nil,
            deletesAfter: Date? = nil,
            frozenTime: Date? = nil,
            livemode: Bool? = nil,
            name: String? = nil,
            status: Status? = nil,
            statusDetails: StatusDetails? = nil
        ) {
            self.id = id
            self.object = object
            self.created = created
            self.deletesAfter = deletesAfter
            self.frozenTime = frozenTime
            self.livemode = livemode
            self.name = name
            self.status = status
            self.statusDetails = statusDetails
        }

        /// The status of the Test Clock.
        public enum Status: String, Codable, Hashable, Sendable {
            case advancing
            case internalFailure = "internal_failure"
            case ready
        }

        public struct StatusDetails: Codable, Hashable, Sendable {
            public var advancing: Advancing?

            private enum CodingKeys: String, CodingKey {
                case advancing
            }

            public init(
                advancing: Advancing? = nil
            ) {
                self.advancing = advancing
            }

            public struct Advancing: Codable, Hashable, Sendable {
                /// The `frozen_time` that the Test Clock is advancing towards.
                public var targetFrozenTime: Date?

                private enum CodingKeys: String, CodingKey {
                    case targetFrozenTime
                }

                public init(
                    targetFrozenTime: Date? = nil
                ) {
                    self.targetFrozenTime = targetFrozenTime
                }
            }
        }
    }
}
