//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: entitlements.active_entitlement_summary
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Entitlements {
    /// A summary of a customer's active entitlements.
    public struct ActiveEntitlementSummary: Codable, Hashable, Sendable {
        /// String representing the object's type.
        public let object: String
        /// The customer that is entitled to this feature.
        public var customer: String?
        /// The list of entitlements this customer has.
        public var entitlements: Entitlements?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?

        public init(
            object: String,
            customer: String? = nil,
            entitlements: Entitlements? = nil,
            livemode: Bool? = nil
        ) {
            self.object = object
            self.customer = customer
            self.entitlements = entitlements
            self.livemode = livemode
        }

        /// The list of entitlements this customer has.
        public struct Entitlements: Codable, Hashable, Sendable {
            /// String representing the object's type.
            public let object: String
            public var data: [Stripe.Entitlements.ActiveEntitlement]?
            /// True if this list has another page of items after this one that can be fetched.
            public var hasMore: Bool?
            /// The URL where this list can be accessed.
            public var url: String?

            public init(
                object: String,
                data: [Stripe.Entitlements.ActiveEntitlement]? = nil,
                hasMore: Bool? = nil,
                url: String? = nil
            ) {
                self.object = object
                self.data = data
                self.hasMore = hasMore
                self.url = url
            }
        }
    }
}
