//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-stripe open source project
//
// Copyright (c) 2026 the swift-stripe project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
// See NOTICE for attribution of derived work
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import StripeCheckout
import StripeCore
import StripeIssuing
import StripeModels
import StripeProducts

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing.Plan {
    public enum Create {}
    public enum Delete {}
    public enum List {}
    public enum Retrieve {}
    public enum Update {}
}

// POST /v1/plans
extension Stripe.Billing.Plan.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// Whether the plan is currently available for new subscriptions.
        public var active: Bool?
        /// A positive integer in cents (or local equivalent) (or 0 for a free plan) representing how much to charge on a.
        public var amount: Int?
        /// Same as `amount`, but accepts a decimal value with at most 12 decimal places.
        public var amountDecimal: String?
        /// Describes how to compute the price per period.
        public var billingScheme: BillingScheme?
        /// Three-letter ISO currency code, in lowercase.
        public var currency: Stripe.Currency
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// An identifier randomly generated by Stripe.
        public var id: String?
        /// Specifies billing frequency.
        public var interval: Interval
        /// The number of intervals between subscription billings.
        public var intervalCount: Int?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// The meter tracking the usage of a metered price.
        public var meter: String?
        /// A brief description of the plan, hidden from customers.
        public var nickname: String?
        public var product: String?
        /// Each element represents a pricing tier.
        public var tiers: [Tiers]?
        /// Defines if the tiering price should be `graduated` or `volume` based.
        public var tiersMode: TiersMode?
        /// Apply a transformation to the reported usage or set quantity before computing the billed price.
        public var transformUsage: TransformUsage?
        /// Default number of trial days when subscribing a customer to this plan using `trial_from_plan=true`.
        public var trialPeriodDays: Int?
        /// Configures how the quantity per period should be determined.
        public var usageType: UsageType?

        public init(
            active: Bool? = nil,
            amount: Int? = nil,
            amountDecimal: String? = nil,
            billingScheme: BillingScheme? = nil,
            currency: Stripe.Currency,
            expand: [String]? = nil,
            id: String? = nil,
            interval: Interval,
            intervalCount: Int? = nil,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            meter: String? = nil,
            nickname: String? = nil,
            product: String? = nil,
            tiers: [Tiers]? = nil,
            tiersMode: TiersMode? = nil,
            transformUsage: TransformUsage? = nil,
            trialPeriodDays: Int? = nil,
            usageType: UsageType? = nil
        ) {
            self.active = active
            self.amount = amount
            self.amountDecimal = amountDecimal
            self.billingScheme = billingScheme
            self.currency = currency
            self.expand = expand
            self.id = id
            self.interval = interval
            self.intervalCount = intervalCount
            self.metadata = metadata
            self.meter = meter
            self.nickname = nickname
            self.product = product
            self.tiers = tiers
            self.tiersMode = tiersMode
            self.transformUsage = transformUsage
            self.trialPeriodDays = trialPeriodDays
            self.usageType = usageType
        }

        public enum BillingScheme: String, Codable, Hashable, Sendable {
            case perUnit = "per_unit"
            case tiered
        }

        public enum Interval: String, Codable, Hashable, Sendable {
            case day
            case month
            case week
            case year
        }

        public enum TiersMode: String, Codable, Hashable, Sendable {
            case graduated
            case volume
        }

        public enum UsageType: String, Codable, Hashable, Sendable {
            case licensed
            case metered
        }

        public struct Tiers: Codable, Hashable, Sendable {
            /// The flat billing amount for an entire tier, regardless of the number of units in the tier.
            public var flatAmount: Int?
            /// Same as `flat_amount`, but accepts a decimal value representing an integer in the minor units of the currency.
            public var flatAmountDecimal: String?
            /// The per unit billing amount for each individual unit for which this tier applies.
            public var unitAmount: Int?
            /// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places.
            public var unitAmountDecimal: String?
            /// Specifies the upper bound of this tier.
            public var upTo: UpTo

            public init(
                flatAmount: Int? = nil,
                flatAmountDecimal: String? = nil,
                unitAmount: Int? = nil,
                unitAmountDecimal: String? = nil,
                upTo: UpTo
            ) {
                self.flatAmount = flatAmount
                self.flatAmountDecimal = flatAmountDecimal
                self.unitAmount = unitAmount
                self.unitAmountDecimal = unitAmountDecimal
                self.upTo = upTo
            }

            /// Specifies the upper bound of this tier.
            public enum UpTo: Codable, Hashable, Sendable {
                case value(Int)
                case inf

                public init(from decoder: any Decoder) throws {
                    let container = try decoder.singleValueContainer()
                    if let value = try? container.decode(Int.self) {
                        self = .value(value)
                        return
                    }
                    switch try container.decode(String.self) {
                    case "inf": self = .inf
                    case let other: throw DecodingError.dataCorruptedError(in: container, debugDescription: "unknown keyword \(other)")
                    }
                }

                public func encode(to encoder: any Encoder) throws {
                    var container = encoder.singleValueContainer()
                    switch self {
                    case .value(let value): try container.encode(value)
                    case .inf: try container.encode("inf")
                    }
                }
            }
        }

        /// Apply a transformation to the reported usage or set quantity before computing the billed price.
        public struct TransformUsage: Codable, Hashable, Sendable {
            /// Divide usage by this number.
            public var divideBy: Int
            /// After division, either round the result `up` or `down`.
            public var round: Round

            public init(
                divideBy: Int,
                round: Round
            ) {
                self.divideBy = divideBy
                self.round = round
            }

            public enum Round: String, Codable, Hashable, Sendable {
                case down
                case up
            }
        }
    }

    public typealias Response = Stripe.Billing.Plan
}

// DELETE /v1/plans/{plan}
extension Stripe.Billing.Plan.Delete {
    public typealias Response = DeletedObject<Stripe.Billing.Plan>
}

// GET /v1/plans
extension Stripe.Billing.Plan.List {
    public struct Request: Codable, Hashable, Sendable {
        /// Only return plans that are active or inactive (e.g., pass `false` to list all inactive plans).
        public var active: Bool?
        /// A filter on the list, based on the object `created` field.
        public var created: Stripe.RangeQuery?
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// Only return plans for the given product.
        public var product: String?
        /// A cursor for use in pagination.
        public var startingAfter: String?

        public init(
            active: Bool? = nil,
            created: Stripe.RangeQuery? = nil,
            endingBefore: String? = nil,
            expand: [String]? = nil,
            limit: Int? = nil,
            product: String? = nil,
            startingAfter: String? = nil
        ) {
            self.active = active
            self.created = created
            self.endingBefore = endingBefore
            self.expand = expand
            self.limit = limit
            self.product = product
            self.startingAfter = startingAfter
        }
    }

    public typealias Response = Stripe.Page<Stripe.Billing.Plan>
}

// GET /v1/plans/{plan}
extension Stripe.Billing.Plan.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Billing.Plan
}

// POST /v1/plans/{plan}
extension Stripe.Billing.Plan.Update {
    public struct Request: Codable, Hashable, Sendable {
        /// Whether the plan is currently available for new subscriptions.
        public var active: Bool?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// A brief description of the plan, hidden from customers.
        public var nickname: String?
        /// The product the plan belongs to.
        public var product: String?
        /// Default number of trial days when subscribing a customer to this plan using `trial_from_plan=true`.
        public var trialPeriodDays: Int?

        public init(
            active: Bool? = nil,
            expand: [String]? = nil,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            nickname: String? = nil,
            product: String? = nil,
            trialPeriodDays: Int? = nil
        ) {
            self.active = active
            self.expand = expand
            self.metadata = metadata
            self.nickname = nickname
            self.product = product
            self.trialPeriodDays = trialPeriodDays
        }
    }

    public typealias Response = Stripe.Billing.Plan
}
