//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: billing.meter_event_summary
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing {
    /// A billing meter event summary represents an aggregated view of a customer's billing meter events within a specified ti…
    public struct MeterEventSummary: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Aggregated value of all the events within `start_time` (inclusive) and `end_time` (inclusive).
        public var aggregatedValue: Double?
        /// End timestamp for this event summary (exclusive).
        public var endTime: Date?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// The meter associated with this event summary.
        public var meter: String?
        /// Start timestamp for this event summary (inclusive).
        public var startTime: Date?

        public init(
            id: ID,
            object: String,
            aggregatedValue: Double? = nil,
            endTime: Date? = nil,
            livemode: Bool? = nil,
            meter: String? = nil,
            startTime: Date? = nil
        ) {
            self.id = id
            self.object = object
            self.aggregatedValue = aggregatedValue
            self.endTime = endTime
            self.livemode = livemode
            self.meter = meter
            self.startTime = startTime
        }
    }
}
