//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: quote
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing {
    /// A Quote is a way to model prices that you'd like to provide to a customer.
    public struct Quote: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Total before any discounts or taxes are applied.
        public var amountSubtotal: Int?
        /// Total after discounts and taxes are applied.
        public var amountTotal: Int?
        /// ID of the Connect Application that created the quote.
        @Expandable<Stripe.Shared.Application, String> public var application: String?
        /// The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the …
        public var applicationFeeAmount: Int?
        /// A non-negative decimal between 0 and 100, with at most two decimal places.
        public var applicationFeePercent: Double?
        public var automaticTax: AutomaticTax?
        /// Either `charge_automatically`, or `send_invoice`.
        public var collectionMethod: CollectionMethod?
        public var computed: Computed?
        /// Time at which the object was created.
        public var created: Date?
        /// Three-letter ISO currency code, in lowercase.
        public var currency: String?
        /// The customer who received this quote.
        @Expandable<Stripe.Customers.Customer, String> public var customer: String?
        /// The account representing the customer who received this quote.
        public var customerAccount: String?
        /// The tax rates applied to this quote.
        @ExpandableCollection<Stripe.Tax.Rate> public var defaultTaxRates: [String]?
        /// A description that will be displayed on the quote PDF.
        public var description: String?
        /// The discounts applied to this quote.
        @ExpandableCollection<Stripe.Shared.Discount> public var discounts: [String]?
        /// The date on which the quote will be canceled if in `open` or `draft` status.
        public var expiresAt: Date?
        /// A footer that will be displayed on the quote PDF.
        public var footer: String?
        /// Details of the quote that was cloned.
        public var fromQuote: FromQuote?
        /// A header that will be displayed on the quote PDF.
        public var header: String?
        /// The invoice that was created from this quote.
        @Expandable<Stripe.Billing.Invoice, String> public var invoice: String?
        public var invoiceSettings: InvoiceSettings?
        /// A list of items the customer is being quoted for.
        public var lineItems: LineItems?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?
        /// A unique number that identifies this particular quote.
        public var number: String?
        /// The account on behalf of which to charge.
        @Expandable<Stripe.Connect.Account, String> public var onBehalfOf: String?
        /// The status of the quote.
        public var status: Status?
        public var statusTransitions: StatusTransitions?
        /// The subscription that was created or updated from this quote.
        @Expandable<Stripe.Billing.Subscription, String> public var subscription: String?
        public var subscriptionData: SubscriptionData?
        /// The subscription schedule that was created or updated from this quote.
        @Expandable<Stripe.Billing.Subscription.Schedule, String> public var subscriptionSchedule: String?
        /// ID of the test clock this quote belongs to.
        @Expandable<Stripe.Billing.TestClocks.TestClock, String> public var testClock: String?
        public var totalDetails: TotalDetails?
        /// The account (if any) the payments will be attributed to for tax reporting, and where funds from each payment will be t…
        public var transferData: TransferData?

        public init(
            id: ID,
            object: String,
            amountSubtotal: Int? = nil,
            amountTotal: Int? = nil,
            application: String? = nil,
            applicationFeeAmount: Int? = nil,
            applicationFeePercent: Double? = nil,
            automaticTax: AutomaticTax? = nil,
            collectionMethod: CollectionMethod? = nil,
            computed: Computed? = nil,
            created: Date? = nil,
            currency: String? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            defaultTaxRates: [String]? = nil,
            description: String? = nil,
            discounts: [String]? = nil,
            expiresAt: Date? = nil,
            footer: String? = nil,
            fromQuote: FromQuote? = nil,
            header: String? = nil,
            invoice: String? = nil,
            invoiceSettings: InvoiceSettings? = nil,
            lineItems: LineItems? = nil,
            livemode: Bool? = nil,
            metadata: [String: String]? = nil,
            number: String? = nil,
            onBehalfOf: String? = nil,
            status: Status? = nil,
            statusTransitions: StatusTransitions? = nil,
            subscription: String? = nil,
            subscriptionData: SubscriptionData? = nil,
            subscriptionSchedule: String? = nil,
            testClock: String? = nil,
            totalDetails: TotalDetails? = nil,
            transferData: TransferData? = nil
        ) {
            self.id = id
            self.object = object
            self.amountSubtotal = amountSubtotal
            self.amountTotal = amountTotal
            self._application = Expandable(id: application)
            self.applicationFeeAmount = applicationFeeAmount
            self.applicationFeePercent = applicationFeePercent
            self.automaticTax = automaticTax
            self.collectionMethod = collectionMethod
            self.computed = computed
            self.created = created
            self.currency = currency
            self._customer = Expandable(id: customer)
            self.customerAccount = customerAccount
            self._defaultTaxRates = ExpandableCollection(ids: defaultTaxRates)
            self.description = description
            self._discounts = ExpandableCollection(ids: discounts)
            self.expiresAt = expiresAt
            self.footer = footer
            self.fromQuote = fromQuote
            self.header = header
            self._invoice = Expandable(id: invoice)
            self.invoiceSettings = invoiceSettings
            self.lineItems = lineItems
            self.livemode = livemode
            self.metadata = metadata
            self.number = number
            self._onBehalfOf = Expandable(id: onBehalfOf)
            self.status = status
            self.statusTransitions = statusTransitions
            self._subscription = Expandable(id: subscription)
            self.subscriptionData = subscriptionData
            self._subscriptionSchedule = Expandable(id: subscriptionSchedule)
            self._testClock = Expandable(id: testClock)
            self.totalDetails = totalDetails
            self.transferData = transferData
        }

        /// Either `charge_automatically`, or `send_invoice`.
        public enum CollectionMethod: String, Codable, Hashable, Sendable {
            case chargeAutomatically = "charge_automatically"
            case sendInvoice = "send_invoice"
        }

        /// The status of the quote.
        public enum Status: String, Codable, Hashable, Sendable {
            case accepted
            case canceled
            case draft
            case open
        }

        public struct AutomaticTax: Codable, Hashable, Sendable {
            /// Automatically calculate taxes
            public var enabled: Bool?
            /// The account that's liable for tax.
            public var liability: Stripe.Shared.ConnectAccountReference?
            /// The tax provider powering automatic tax.
            public var provider: String?
            /// The status of the most recent automated tax calculation for this quote.
            public var status: Status?

            public init(
                enabled: Bool? = nil,
                liability: Stripe.Shared.ConnectAccountReference? = nil,
                provider: String? = nil,
                status: Status? = nil
            ) {
                self.enabled = enabled
                self.liability = liability
                self.provider = provider
                self.status = status
            }

            /// The status of the most recent automated tax calculation for this quote.
            public enum Status: String, Codable, Hashable, Sendable {
                case complete
                case failed
                case requiresLocationInputs = "requires_location_inputs"
            }
        }

        public struct Computed: Codable, Hashable, Sendable {
            /// The definitive totals and line items the customer will be charged on a recurring basis.
            public var recurring: Recurring?
            public var upfront: Upfront?

            public init(
                recurring: Recurring? = nil,
                upfront: Upfront? = nil
            ) {
                self.recurring = recurring
                self.upfront = upfront
            }

            public struct Recurring: Codable, Hashable, Sendable {
                /// Total before any discounts or taxes are applied.
                public var amountSubtotal: Int?
                /// Total after discounts and taxes are applied.
                public var amountTotal: Int?
                /// The frequency at which a subscription is billed.
                public var interval: Interval?
                /// The number of intervals (specified in the `interval` attribute) between subscription billings.
                public var intervalCount: Int?
                public var totalDetails: TotalDetails?

                public init(
                    amountSubtotal: Int? = nil,
                    amountTotal: Int? = nil,
                    interval: Interval? = nil,
                    intervalCount: Int? = nil,
                    totalDetails: TotalDetails? = nil
                ) {
                    self.amountSubtotal = amountSubtotal
                    self.amountTotal = amountTotal
                    self.interval = interval
                    self.intervalCount = intervalCount
                    self.totalDetails = totalDetails
                }

                /// The frequency at which a subscription is billed.
                public enum Interval: String, Codable, Hashable, Sendable {
                    case day
                    case month
                    case week
                    case year
                }

                public struct TotalDetails: Codable, Hashable, Sendable {
                    /// This is the sum of all the discounts.
                    public var amountDiscount: Int?
                    /// This is the sum of all the shipping amounts.
                    public var amountShipping: Int?
                    /// This is the sum of all the tax amounts.
                    public var amountTax: Int?
                    public var breakdown: Breakdown?

                    public init(
                        amountDiscount: Int? = nil,
                        amountShipping: Int? = nil,
                        amountTax: Int? = nil,
                        breakdown: Breakdown? = nil
                    ) {
                        self.amountDiscount = amountDiscount
                        self.amountShipping = amountShipping
                        self.amountTax = amountTax
                        self.breakdown = breakdown
                    }

                    public struct Breakdown: Codable, Hashable, Sendable {
                        /// The aggregated discounts.
                        public var discounts: [Stripe.Shared.Discounts]?
                        /// The aggregated tax amounts by rate.
                        public var taxes: [Stripe.Shared.Taxes]?

                        public init(
                            discounts: [Stripe.Shared.Discounts]? = nil,
                            taxes: [Stripe.Shared.Taxes]? = nil
                        ) {
                            self.discounts = discounts
                            self.taxes = taxes
                        }
                    }
                }
            }

            public struct Upfront: Codable, Hashable, Sendable {
                /// Total before any discounts or taxes are applied.
                public var amountSubtotal: Int?
                /// Total after discounts and taxes are applied.
                public var amountTotal: Int?
                /// The line items that will appear on the next invoice after this quote is accepted.
                public var lineItems: LineItems?
                public var totalDetails: TotalDetails?

                public init(
                    amountSubtotal: Int? = nil,
                    amountTotal: Int? = nil,
                    lineItems: LineItems? = nil,
                    totalDetails: TotalDetails? = nil
                ) {
                    self.amountSubtotal = amountSubtotal
                    self.amountTotal = amountTotal
                    self.lineItems = lineItems
                    self.totalDetails = totalDetails
                }

                /// The line items that will appear on the next invoice after this quote is accepted.
                public struct LineItems: Codable, Hashable, Sendable {
                    /// String representing the object's type.
                    public let object: String
                    /// Details about each object.
                    public var data: [Stripe.Checkout.Session.LineItem]?
                    /// True if this list has another page of items after this one that can be fetched.
                    public var hasMore: Bool?
                    /// The URL where this list can be accessed.
                    public var url: String?

                    public init(
                        object: String,
                        data: [Stripe.Checkout.Session.LineItem]? = nil,
                        hasMore: Bool? = nil,
                        url: String? = nil
                    ) {
                        self.object = object
                        self.data = data
                        self.hasMore = hasMore
                        self.url = url
                    }
                }

                public struct TotalDetails: Codable, Hashable, Sendable {
                    /// This is the sum of all the discounts.
                    public var amountDiscount: Int?
                    /// This is the sum of all the shipping amounts.
                    public var amountShipping: Int?
                    /// This is the sum of all the tax amounts.
                    public var amountTax: Int?
                    public var breakdown: Breakdown?

                    public init(
                        amountDiscount: Int? = nil,
                        amountShipping: Int? = nil,
                        amountTax: Int? = nil,
                        breakdown: Breakdown? = nil
                    ) {
                        self.amountDiscount = amountDiscount
                        self.amountShipping = amountShipping
                        self.amountTax = amountTax
                        self.breakdown = breakdown
                    }

                    public struct Breakdown: Codable, Hashable, Sendable {
                        /// The aggregated discounts.
                        public var discounts: [Stripe.Shared.Discounts]?
                        /// The aggregated tax amounts by rate.
                        public var taxes: [Stripe.Shared.Taxes]?

                        public init(
                            discounts: [Stripe.Shared.Discounts]? = nil,
                            taxes: [Stripe.Shared.Taxes]? = nil
                        ) {
                            self.discounts = discounts
                            self.taxes = taxes
                        }
                    }
                }
            }
        }

        public struct FromQuote: Codable, Hashable, Sendable {
            /// Whether this quote is a revision of a different quote.
            public var isRevision: Bool?
            /// The quote that was cloned.
            @Expandable<Stripe.Billing.Quote, String> public var quote: String?

            public init(
                isRevision: Bool? = nil,
                quote: String? = nil
            ) {
                self.isRevision = isRevision
                self._quote = Expandable(id: quote)
            }
        }

        public struct InvoiceSettings: Codable, Hashable, Sendable {
            /// A list of up to 4 custom fields to be displayed on the invoice.
            public var customFields: [Stripe.Shared.CustomFields]?
            /// Number of days within which a customer must pay invoices generated by this quote.
            public var daysUntilDue: Int?
            /// An arbitrary string attached to the object.
            public var description: String?
            /// Footer to be displayed on the invoice.
            public var footer: String?
            public var issuer: Stripe.Shared.ConnectAccountReference?

            public init(
                customFields: [Stripe.Shared.CustomFields]? = nil,
                daysUntilDue: Int? = nil,
                description: String? = nil,
                footer: String? = nil,
                issuer: Stripe.Shared.ConnectAccountReference? = nil
            ) {
                self.customFields = customFields
                self.daysUntilDue = daysUntilDue
                self.description = description
                self.footer = footer
                self.issuer = issuer
            }
        }

        /// A list of items the customer is being quoted for.
        public struct LineItems: Codable, Hashable, Sendable {
            /// String representing the object's type.
            public let object: String
            /// Details about each object.
            public var data: [Stripe.Checkout.Session.LineItem]?
            /// True if this list has another page of items after this one that can be fetched.
            public var hasMore: Bool?
            /// The URL where this list can be accessed.
            public var url: String?

            public init(
                object: String,
                data: [Stripe.Checkout.Session.LineItem]? = nil,
                hasMore: Bool? = nil,
                url: String? = nil
            ) {
                self.object = object
                self.data = data
                self.hasMore = hasMore
                self.url = url
            }
        }

        public struct StatusTransitions: Codable, Hashable, Sendable {
            /// The time that the quote was accepted.
            public var acceptedAt: Date?
            /// The time that the quote was canceled.
            public var canceledAt: Date?
            /// The time that the quote was finalized.
            public var finalizedAt: Date?

            public init(
                acceptedAt: Date? = nil,
                canceledAt: Date? = nil,
                finalizedAt: Date? = nil
            ) {
                self.acceptedAt = acceptedAt
                self.canceledAt = canceledAt
                self.finalizedAt = finalizedAt
            }
        }

        public struct SubscriptionData: Codable, Hashable, Sendable {
            public var billingMode: BillingMode?
            /// The subscription's description, meant to be displayable to the customer.
            public var description: String?
            /// When creating a new subscription, the date of which the subscription schedule will start after the quote is accepted.
            public var effectiveDate: Date?
            /// Set of key-value pairs that will set metadata on the subscription or subscription schedule when the quote is accepted.
            public var metadata: [String: String]?
            /// Integer representing the number of trial period days before the customer is charged for the first time.
            public var trialPeriodDays: Int?

            public init(
                billingMode: BillingMode? = nil,
                description: String? = nil,
                effectiveDate: Date? = nil,
                metadata: [String: String]? = nil,
                trialPeriodDays: Int? = nil
            ) {
                self.billingMode = billingMode
                self.description = description
                self.effectiveDate = effectiveDate
                self.metadata = metadata
                self.trialPeriodDays = trialPeriodDays
            }

            /// The billing mode of the quote.
            public struct BillingMode: Codable, Hashable, Sendable {
                public var flexible: Stripe.Shared.Flexible?
                /// Controls how prorations and invoices for subscriptions are calculated and orchestrated.
                public var `type`: Type?

                public init(
                    flexible: Stripe.Shared.Flexible? = nil,
                    `type`: Type? = nil
                ) {
                    self.flexible = flexible
                    self.`type` = `type`
                }

                /// Controls how prorations and invoices for subscriptions are calculated and orchestrated.
                public enum `Type`: String, Codable, Hashable, Sendable {
                    case classic
                    case flexible
                }
            }
        }

        public struct TotalDetails: Codable, Hashable, Sendable {
            /// This is the sum of all the discounts.
            public var amountDiscount: Int?
            /// This is the sum of all the shipping amounts.
            public var amountShipping: Int?
            /// This is the sum of all the tax amounts.
            public var amountTax: Int?
            public var breakdown: Breakdown?

            public init(
                amountDiscount: Int? = nil,
                amountShipping: Int? = nil,
                amountTax: Int? = nil,
                breakdown: Breakdown? = nil
            ) {
                self.amountDiscount = amountDiscount
                self.amountShipping = amountShipping
                self.amountTax = amountTax
                self.breakdown = breakdown
            }

            public struct Breakdown: Codable, Hashable, Sendable {
                /// The aggregated discounts.
                public var discounts: [Stripe.Shared.Discounts]?
                /// The aggregated tax amounts by rate.
                public var taxes: [Stripe.Shared.Taxes]?

                public init(
                    discounts: [Stripe.Shared.Discounts]? = nil,
                    taxes: [Stripe.Shared.Taxes]? = nil
                ) {
                    self.discounts = discounts
                    self.taxes = taxes
                }
            }
        }

        public struct TransferData: Codable, Hashable, Sendable {
            /// The amount in cents (or local equivalent) that will be transferred to the destination account when the invoice is paid…
            public var amount: Int?
            /// A non-negative decimal between 0 and 100, with at most two decimal places.
            public var amountPercent: Double?
            /// The account where funds from the payment will be transferred to upon payment success.
            @Expandable<Stripe.Connect.Account, String> public var destination: String?

            public init(
                amount: Int? = nil,
                amountPercent: Double? = nil,
                destination: String? = nil
            ) {
                self.amount = amount
                self.amountPercent = amountPercent
                self._destination = Expandable(id: destination)
            }
        }
    }
}
