//
//  swift
//
//
//  Created by Andrew Edwards on 1/2/20.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

// The Schedule struct is generated (Models/Generated). These are the nested types the
// request layer still names under `Stripe.Billing.Subscription.Schedule` that the generator spells differently.


// https://docs.stripe.com/api/subscriptionSchedules/object.md



extension Stripe.Billing.Subscription.Schedule {
    public struct DefaultSettingsAutomaticTax: Codable, Hashable, Sendable {
        /// Whether Stripe automatically computes tax on invoices created during this phase.
        public var enabled: Bool?

        public init(
            enabled: Bool? = nil
        ) {
            self.enabled = enabled
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public enum CollectionMethod: String, Codable, Sendable {
        case chargeAutomatically = "charge_automatically"
        case sendInvoice = "send_invoice"
    }
}


extension Stripe.Billing.Subscription.Schedule {
    public struct DefaultSettingsBillingThresholds: Codable, Hashable, Sendable {
        /// Monetary threshold that triggers the subscription to create an invoice
        public var amountGte: Int?
        /// Indicates if the `billing_cycle_anchor` should be reset when a threshold is reached. If true, `billing_cycle_anchor` will be updated to the date/time the threshold was last reached; otherwise, the value will remain unchanged. This value may not be `true` if the subscription contains items with plans that have `aggregate_usage=last_ever`.
        public var resetBillingCycleAnchor: Bool?

        public init(
            amountGte: Int? = nil,
            resetBillingCycleAnchor: Bool? = nil
        ) {
            self.amountGte = amountGte
            self.resetBillingCycleAnchor = resetBillingCycleAnchor
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct InvoiceSettings: Codable, Hashable, Sendable {
        /// Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
        public var daysUntilDue: Int?

        private enum CodingKeys: String, CodingKey {
            case daysUntilDue
        }

        public init(
            daysUntilDue: Int? = nil
        ) {
            self.daysUntilDue = daysUntilDue
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct TransferData: Codable, Hashable, Sendable {
        /// A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice subtotal that will be transferred to the destination account. By default, the entire amount is transferred to the destination.
        public var amountPercent: Int?
        /// The account where funds from the payment will be transferred to upon payment success.
        @ExpandableOf<Stripe.Connect.Account> public var destination: Stripe.Connect.Account.ID?

        public init(
            amountPercent: Int? = nil,
            destination: Stripe.Connect.Account.ID? = nil
        ) {
            self.amountPercent = amountPercent
            self._destination = Expandable(id: destination)
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct Phase: Codable, Hashable, Sendable {
        /// A list of prices and quantities that will generate invoice items appended to the first invoice for this phase.
        public var addInvoiceItems: [PhaseAddInvoiceItem]?
        /// A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice subtotal that will be transferred to the application owner’s Stripe account during this phase of the schedule.
        public var applicationFeePercent: Float?
        /// Automatic tax settings for this phase.
        public var automaticTax: PhaseAutomaticTax?
        /// Possible values are `phase_start` or `automatic`. If `phase_start` then billing cycle anchor of the subscription is set to the start of the phase when entering the phase. If automatic then the billing cycle anchor is automatically modified as needed when entering the phase. For more information, see the billing cycle documentation.
        public var billingCycleAnchor: BillingCycleAnchor?
        /// Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period
        public var billingThresholds: DefaultSettingsBillingThresholds?
        /// Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay the underlying subscription at the end of each billing cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions.
        public var collectionMethod: CollectionMethod?
        /// ID of the coupon to use during this phase of the subscription schedule.
        @ExpandableOf<Stripe.Products.Coupon> public var coupon
        /// Three-letter ISO currency code, in lowercase. Must be a supported currency.
        public var currency: Stripe.Currency?
        /// ID of the default payment method for the subscription schedule. It must belong to the customer associated with the subscription schedule. If not set, invoices will use the default payment method in the customer’s invoice settings.
        @ExpandableOf<Stripe.PaymentMethods.PaymentMethod> public var defaultPaymentMethod:
            Stripe.PaymentMethods.PaymentMethod.ID?
        /// The default tax rates to apply to the subscription during this phase of the subscription schedule.
        public var defaultTaxRates: [Stripe.Tax.Rate]?
        /// Subscription description, meant to be displayable to the customer. Use this field to optionally store an explanation of the subscription.
        public var description: String?
        /// The end of this phase of the subscription schedule.
        public var endDate: Date?
        /// The subscription schedule’s default invoice settings.
        public var invoiceSettings: InvoiceSettings?
        /// Subscription items to configure the subscription to during this phase of the subscription schedule.
        public var items: [PhaseItem]?
        /// Set of key-value pairs that you can attach to a phase. Metadata on a schedule’s phase will update the underlying subscription’s metadata when the phase is entered. Updating the underlying subscription’s metadata directly will not affect the current phase’s metadata.
        public var metadata: [String: String]?
        /// The account (if any) the charge was made on behalf of for charges associated with the schedule’s subscription. See the Connect documentation for details.
        @ExpandableOf<Stripe.Connect.Account> public var onBehalfOf: Stripe.Connect.Account.ID?
        /// Controls whether or not the subscription schedule will prorate when transitioning to this phase. Values are `create_prorations` and `none`.
        public var prorationBehavior: Phase.ProrationBehavior?
        /// The start of this phase of the subscription schedule.
        public var startDate: Date?
        /// The account (if any) the subscription’s payments will be attributed to for tax reporting, and where funds from each payment will be transferred to for each of the subscription’s invoices.
        public var transferData: PhaseTransferData?
        /// When the trial ends within the phase.
        public var trialEnd: Date?

        public init(
            addInvoiceItems: [PhaseAddInvoiceItem]? = nil,
            applicationFeePercent: Float? = nil,
            automaticTax: PhaseAutomaticTax? = nil,
            billingCycleAnchor: BillingCycleAnchor? = nil,
            billingThresholds: DefaultSettingsBillingThresholds? = nil,
            collectionMethod: CollectionMethod? = nil,
            coupon: Stripe.Products.Coupon.ID? = nil,
            currency: Stripe.Currency? = nil,
            defaultPaymentMethod: Stripe.PaymentMethods.PaymentMethod.ID? = nil,
            defaultTaxRates: [Stripe.Tax.Rate]? = nil,
            description: String? = nil,
            endDate: Date? = nil,
            invoiceSettings: InvoiceSettings? = nil,
            items: [PhaseItem]? = nil,
            metadata: [String: String]? = nil,
            onBehalfOf: Stripe.Connect.Account.ID? = nil,
            prorationBehavior: Phase.ProrationBehavior? = nil,
            startDate: Date? = nil,
            transferData: PhaseTransferData? = nil,
            trialEnd: Date? = nil
        ) {
            self.addInvoiceItems = addInvoiceItems
            self.applicationFeePercent = applicationFeePercent
            self.automaticTax = automaticTax
            self.billingCycleAnchor = billingCycleAnchor
            self.billingThresholds = billingThresholds
            self.collectionMethod = collectionMethod
            self._coupon = Expandable(id: coupon)
            self.currency = currency
            self._defaultPaymentMethod = Expandable(id: defaultPaymentMethod)
            self.defaultTaxRates = defaultTaxRates
            self.description = description
            self.endDate = endDate
            self.invoiceSettings = invoiceSettings
            self.items = items
            self.metadata = metadata
            self._onBehalfOf = Expandable(id: onBehalfOf)
            self.prorationBehavior = prorationBehavior
            self.startDate = startDate
            self.transferData = transferData
            self.trialEnd = trialEnd
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct PhaseAddInvoiceItem: Codable, Hashable, Sendable {
        /// ID of the price used to generate the invoice item.
        @ExpandableOf<Stripe.Products.Price> public var price: Stripe.Products.Price.ID?
        /// The quantity of the invoice item.
        public var quantity: Int?
        /// The tax rates which apply to the item. When set, the `default_tax_rates` do not apply to this item.
        public var taxRates: [Stripe.Tax.Rate]?

        public init(
            price: Stripe.Products.Price.ID? = nil,
            quantity: Int? = nil,
            taxRates: [Stripe.Tax.Rate]? = nil
        ) {
            self._price = Expandable(id: price)
            self.quantity = quantity
            self.taxRates = taxRates
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct PhaseAutomaticTax: Codable, Hashable, Sendable {
        /// Whether Stripe automatically computes tax on invoices created during this phase.
        public var enabled: Bool?

        public init(
            enabled: Bool? = nil
        ) {
            self.enabled = enabled
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct PhaseItem: Codable, Hashable, Sendable {
        /// Define thresholds at which an invoice will be sent, and the related subscription advanced to a new billing period.
        public var billingThresholds: PhaseItemBillingThresholds?
        /// Set of key-value pairs that you can attach to an item. Metadata on this item will update the underlying subscription item’s metadata when the phase is entered.
        public var metadata: [String: String]?
        /// ID of the price to which the customer should be subscribed.
        @ExpandableOf<Stripe.Products.Price> public var price: Stripe.Products.Price.ID?
        /// Quantity of the plan to which the customer should be subscribed.
        public var quantity: Int?
        /// The tax rates which apply to this `phase_item`. When set, the `default_tax_rates` on the phase do not apply to this `phase_item`.
        public var taxRates: [Stripe.Tax.Rate]?

        public init(
            billingThresholds: PhaseItemBillingThresholds? = nil,
            metadata: [String: String]? = nil,
            price: Stripe.Products.Price.ID? = nil,
            quantity: Int? = nil,
            taxRates: [Stripe.Tax.Rate]? = nil
        ) {
            self.billingThresholds = billingThresholds
            self.metadata = metadata
            self._price = Expandable(id: price)
            self.quantity = quantity
            self.taxRates = taxRates
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct PhaseItemBillingThresholds: Codable, Hashable, Sendable {
        /// Usage threshold that triggers the subscription to create an invoice
        public var usageGte: Int?

        public init(
            usageGte: Int? = nil
        ) {
            self.usageGte = usageGte
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct PhaseTransferData: Codable, Hashable, Sendable {
        /// A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice subtotal that will be transferred to the destination account. By default, the entire amount is transferred to the destination.
        public var amountPercent: Int?
        /// The account where funds from the payment will be transferred to upon payment success.
        @ExpandableOf<Stripe.Connect.Account> public var destination: Stripe.Connect.Account.ID?

        public init(
            amountPercent: Int? = nil,
            destination: Stripe.Connect.Account.ID? = nil
        ) {
            self.amountPercent = amountPercent
            self._destination = Expandable(id: destination)
        }
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public enum BillingCycleAnchor: String, Codable, Sendable {
        case phaseStart = "phase_start"
        case automatic
    }
}


extension Stripe.Billing.Subscription.Schedule.Phase {
    public enum ProrationBehavior: String, Codable, Sendable {
        case createProrations = "create_prorations"
        case alwaysInvoice = "always_invoice"
        case none
    }
}

extension Stripe.Billing.Subscription.Schedule {
    public struct List: Codable, Hashable, Sendable {
        public var object: String
        public var hasMore: Bool?
        public var url: String?
        public var data: [Stripe.Billing.Subscription.Schedule]?

        public init(
            object: String,
            hasMore: Bool? = nil,
            url: String? = nil,
            data: [Stripe.Billing.Subscription.Schedule]? = nil
        ) {
            self.object = object
            self.hasMore = hasMore
            self.url = url
            self.data = data
        }
    }
}
