//
//  CashBalancesClient.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import NIOHTTP1

/// Operations on Stripe.Customers.CustomerCashBalance.
///
/// A protocol so tests can substitute a double; ``CashBalancesClient`` is the implementation that
/// talks to Stripe.
public protocol CashBalancesAPI: Sendable {
    func retrieve(customer: String, _ request: Stripe.Customers.CustomerCashBalance.Retrieve.Request) async throws -> Stripe.Customers.CustomerCashBalance.Retrieve.Response
    func update(customer: String, _ request: Stripe.Customers.CustomerCashBalance.Update.Request, idempotencyKey: String?) async throws -> Stripe.Customers.CustomerCashBalance.Update.Response
}

public struct CashBalancesClient: CashBalancesAPI {
    private let api: StripeAPI

    public init(api: StripeAPI) { self.api = api }

    public func retrieve(customer: String, _ request: Stripe.Customers.CustomerCashBalance.Retrieve.Request) async throws -> Stripe.Customers.CustomerCashBalance.Retrieve.Response {
        try await api.list("v1/customers/\(customer)/cash_balance", parameters: request)
    }

    public func update(customer: String, _ request: Stripe.Customers.CustomerCashBalance.Update.Request, idempotencyKey: String?) async throws -> Stripe.Customers.CustomerCashBalance.Update.Response {
        try await api.send(.POST, "v1/customers/\(customer)/cash_balance", body: request, idempotencyKey: idempotencyKey)
    }
}

// A write with no explicit key behaves as it did before idempotency keys existed: no header,
// and no retry. See ``StripeAPI/isSafeToRetry(_:)``.
extension CashBalancesAPI {
    public func retrieve(customer: String) async throws -> Stripe.Customers.CustomerCashBalance.Retrieve.Response {
        try await retrieve(customer: customer, .init())
    }

    public func update(customer: String, _ request: Stripe.Customers.CustomerCashBalance.Update.Request) async throws -> Stripe.Customers.CustomerCashBalance.Update.Response {
        try await update(customer: customer, request, idempotencyKey: nil)
    }

    public func update(customer: String, idempotencyKey: String? = nil) async throws -> Stripe.Customers.CustomerCashBalance.Update.Response {
        try await update(customer: customer, .init(), idempotencyKey: idempotencyKey)
    }
}
