//
//  ReportingReportTypesClient.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import NIOHTTP1

/// Operations on ReportType.
///
/// A protocol so tests can substitute a double; ``ReportingReportTypesClient`` is the implementation that
/// talks to Stripe.
public protocol ReportingReportTypesAPI: Sendable {
    func list(_ request: ReportType.List.Request) async throws -> ReportType.List.Response
    func retrieve(id: ReportType.ID, _ request: ReportType.Retrieve.Request) async throws -> ReportType.Retrieve.Response
}

public struct ReportingReportTypesClient: ReportingReportTypesAPI {
    private let api: StripeAPI

    public init(api: StripeAPI) { self.api = api }

    public func list(_ request: ReportType.List.Request) async throws -> ReportType.List.Response {
        try await api.list("v1/reporting/report_types", parameters: request)
    }

    public func retrieve(id: ReportType.ID, _ request: ReportType.Retrieve.Request) async throws -> ReportType.Retrieve.Response {
        try await api.list("v1/reporting/report_types/\(id)", parameters: request)
    }
}

// A write with no explicit key behaves as it did before idempotency keys existed: no header,
// and no retry. See ``StripeAPI/isSafeToRetry(_:)``.
extension ReportingReportTypesAPI {
    public func list() async throws -> ReportType.List.Response {
        try await list(.init())
    }

    public func retrieve(id: ReportType.ID) async throws -> ReportType.Retrieve.Response {
        try await retrieve(id: id, .init())
    }
}
