//
//  WebhookEndpointsClient.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import NIOHTTP1

/// Operations on Webhook.
///
/// A protocol so tests can substitute a double; ``WebhookEndpointsClient`` is the implementation that
/// talks to Stripe.
public protocol WebhookEndpointsAPI: Sendable {
    func create(_ request: Webhook.Create.Request, idempotencyKey: String?) async throws -> Webhook.Create.Response
    func delete(id: Webhook.ID, idempotencyKey: String?) async throws -> Webhook.Delete.Response
    func list(_ request: Webhook.List.Request) async throws -> Webhook.List.Response
    func retrieve(id: Webhook.ID, _ request: Webhook.Retrieve.Request) async throws -> Webhook.Retrieve.Response
    func update(id: Webhook.ID, _ request: Webhook.Update.Request, idempotencyKey: String?) async throws -> Webhook.Update.Response
}

public struct WebhookEndpointsClient: WebhookEndpointsAPI {
    private let api: StripeAPI

    public init(api: StripeAPI) { self.api = api }

    public func create(_ request: Webhook.Create.Request, idempotencyKey: String?) async throws -> Webhook.Create.Response {
        try await api.send(.POST, "v1/webhook_endpoints", body: request, idempotencyKey: idempotencyKey)
    }

    public func delete(id: Webhook.ID, idempotencyKey: String?) async throws -> Webhook.Delete.Response {
        try await api.send(.DELETE, "v1/webhook_endpoints/\(id)", idempotencyKey: idempotencyKey)
    }

    public func list(_ request: Webhook.List.Request) async throws -> Webhook.List.Response {
        try await api.list("v1/webhook_endpoints", parameters: request)
    }

    public func retrieve(id: Webhook.ID, _ request: Webhook.Retrieve.Request) async throws -> Webhook.Retrieve.Response {
        try await api.list("v1/webhook_endpoints/\(id)", parameters: request)
    }

    public func update(id: Webhook.ID, _ request: Webhook.Update.Request, idempotencyKey: String?) async throws -> Webhook.Update.Response {
        try await api.send(.POST, "v1/webhook_endpoints/\(id)", body: request, idempotencyKey: idempotencyKey)
    }
}

// A write with no explicit key behaves as it did before idempotency keys existed: no header,
// and no retry. See ``StripeAPI/isSafeToRetry(_:)``.
extension WebhookEndpointsAPI {
    public func create(_ request: Webhook.Create.Request) async throws -> Webhook.Create.Response {
        try await create(request, idempotencyKey: nil)
    }

    public func delete(id: Webhook.ID) async throws -> Webhook.Delete.Response {
        try await delete(id: id, idempotencyKey: nil)
    }

    public func list() async throws -> Webhook.List.Response {
        try await list(.init())
    }

    public func retrieve(id: Webhook.ID) async throws -> Webhook.Retrieve.Response {
        try await retrieve(id: id, .init())
    }

    public func update(id: Webhook.ID, _ request: Webhook.Update.Request) async throws -> Webhook.Update.Response {
        try await update(id: id, request, idempotencyKey: nil)
    }

    public func update(id: Webhook.ID, idempotencyKey: String? = nil) async throws -> Webhook.Update.Response {
        try await update(id: id, .init(), idempotencyKey: idempotencyKey)
    }
}
