//
//  Products/Products.Product+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Products.Product {
    public enum Create {}
    public enum Delete {}
    public enum List {}
    public enum Retrieve {}
    public enum Search {}
    public enum Update {}
}

// POST /v1/products
extension Stripe.Products.Product.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// Whether the product is currently available for purchase.
        public var active: Bool?
        /// Data used to generate a new Price object.
        public var defaultPriceData: DefaultPriceData?
        /// The product's description, meant to be displayable to the customer.
        public var description: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// An identifier will be randomly generated by Stripe.
        public var id: String?
        /// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        public var images: [String]?
        /// A list of up to 15 marketing features for this product.
        public var marketingFeatures: [MarketingFeatures]?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?
        /// The product's name, meant to be displayable to the customer.
        public var name: String
        /// The dimensions of this product for shipping purposes.
        public var packageDimensions: PackageDimensions?
        /// Whether this product is shipped (i.e., physical goods).
        public var shippable: Bool?
        /// An arbitrary string to be displayed on your customer's credit card or bank statement.
        public var statementDescriptor: String?
        /// A tax code ID.
        public var taxCode: String?
        /// The type of the product.
        public var `type`: Type?
        /// A label that represents units of this product.
        public var unitLabel: String?
        /// A URL of a publicly-accessible webpage for this product.
        public var url: String?

        public init(
            active: Bool? = nil,
            defaultPriceData: DefaultPriceData? = nil,
            description: String? = nil,
            expand: [String]? = nil,
            id: String? = nil,
            images: [String]? = nil,
            marketingFeatures: [MarketingFeatures]? = nil,
            metadata: [String: String]? = nil,
            name: String,
            packageDimensions: PackageDimensions? = nil,
            shippable: Bool? = nil,
            statementDescriptor: String? = nil,
            taxCode: String? = nil,
            `type`: Type? = nil,
            unitLabel: String? = nil,
            url: String? = nil
        ) {
            self.active = active
            self.defaultPriceData = defaultPriceData
            self.description = description
            self.expand = expand
            self.id = id
            self.images = images
            self.marketingFeatures = marketingFeatures
            self.metadata = metadata
            self.name = name
            self.packageDimensions = packageDimensions
            self.shippable = shippable
            self.statementDescriptor = statementDescriptor
            self.taxCode = taxCode
            self.`type` = `type`
            self.unitLabel = unitLabel
            self.url = url
        }

        public enum `Type`: String, Codable, Hashable, Sendable {
            case good
            case service
        }

        /// Data used to generate a new Price object.
        public struct DefaultPriceData: Codable, Hashable, Sendable {
            /// Three-letter ISO currency code, in lowercase.
            public var currency: Stripe.Currency
            /// Prices defined in each available currency option.
            public var currencyOptions: [String: CurrencyOptions]?
            /// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Li…
            public var customUnitAmount: CustomUnitAmount?
            /// Set of key-value pairs that you can attach to an object.
            public var metadata: [String: String]?
            /// The recurring components of a price such as `interval` and `interval_count`.
            public var recurring: Recurring?
            /// Only required if a default tax behavior) was not provided in the Stripe Tax settings.
            public var taxBehavior: TaxBehavior?
            /// A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.
            public var unitAmount: Int?
            /// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places.
            public var unitAmountDecimal: String?

            public init(
                currency: Stripe.Currency,
                currencyOptions: [String: CurrencyOptions]? = nil,
                customUnitAmount: CustomUnitAmount? = nil,
                metadata: [String: String]? = nil,
                recurring: Recurring? = nil,
                taxBehavior: TaxBehavior? = nil,
                unitAmount: Int? = nil,
                unitAmountDecimal: String? = nil
            ) {
                self.currency = currency
                self.currencyOptions = currencyOptions
                self.customUnitAmount = customUnitAmount
                self.metadata = metadata
                self.recurring = recurring
                self.taxBehavior = taxBehavior
                self.unitAmount = unitAmount
                self.unitAmountDecimal = unitAmountDecimal
            }

            public enum TaxBehavior: String, Codable, Hashable, Sendable {
                case exclusive
                case inclusive
                case unspecified
            }

            public struct CurrencyOptions: Codable, Hashable, Sendable {
                /// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Li…
                public var customUnitAmount: CustomUnitAmount?
                /// Only required if a default tax behavior) was not provided in the Stripe Tax settings.
                public var taxBehavior: TaxBehavior?
                /// Each element represents a pricing tier.
                public var tiers: [Tiers]?
                /// A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.
                public var unitAmount: Int?
                /// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places.
                public var unitAmountDecimal: String?

                public init(
                    customUnitAmount: CustomUnitAmount? = nil,
                    taxBehavior: TaxBehavior? = nil,
                    tiers: [Tiers]? = nil,
                    unitAmount: Int? = nil,
                    unitAmountDecimal: String? = nil
                ) {
                    self.customUnitAmount = customUnitAmount
                    self.taxBehavior = taxBehavior
                    self.tiers = tiers
                    self.unitAmount = unitAmount
                    self.unitAmountDecimal = unitAmountDecimal
                }

                public enum TaxBehavior: String, Codable, Hashable, Sendable {
                    case exclusive
                    case inclusive
                    case unspecified
                }

                /// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Li…
                public struct CustomUnitAmount: Codable, Hashable, Sendable {
                    /// Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.
                    public var enabled: Bool
                    /// The maximum unit amount the customer can specify for this item.
                    public var maximum: Int?
                    /// The minimum unit amount the customer can specify for this item.
                    public var minimum: Int?
                    /// The starting unit amount which can be updated by the customer.
                    public var preset: Int?

                    public init(
                        enabled: Bool,
                        maximum: Int? = nil,
                        minimum: Int? = nil,
                        preset: Int? = nil
                    ) {
                        self.enabled = enabled
                        self.maximum = maximum
                        self.minimum = minimum
                        self.preset = preset
                    }
                }

                public struct Tiers: Codable, Hashable, Sendable {
                    /// The flat billing amount for an entire tier, regardless of the number of units in the tier.
                    public var flatAmount: Int?
                    /// Same as `flat_amount`, but accepts a decimal value representing an integer in the minor units of the currency.
                    public var flatAmountDecimal: String?
                    /// The per unit billing amount for each individual unit for which this tier applies.
                    public var unitAmount: Int?
                    /// Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places.
                    public var unitAmountDecimal: String?
                    /// Specifies the upper bound of this tier.
                    public var upTo: UpTo

                    public init(
                        flatAmount: Int? = nil,
                        flatAmountDecimal: String? = nil,
                        unitAmount: Int? = nil,
                        unitAmountDecimal: String? = nil,
                        upTo: UpTo
                    ) {
                        self.flatAmount = flatAmount
                        self.flatAmountDecimal = flatAmountDecimal
                        self.unitAmount = unitAmount
                        self.unitAmountDecimal = unitAmountDecimal
                        self.upTo = upTo
                    }

                    /// Specifies the upper bound of this tier.
                    public enum UpTo: Codable, Hashable, Sendable {
                        case value(Int)
                        case inf

                        public init(from decoder: any Decoder) throws {
                            let container = try decoder.singleValueContainer()
                            if let value = try? container.decode(Int.self) { self = .value(value); return }
                            switch try container.decode(String.self) {
                            case "inf": self = .inf
                            case let other: throw DecodingError.dataCorruptedError(in: container, debugDescription: "unknown keyword \(other)")
                            }
                        }

                        public func encode(to encoder: any Encoder) throws {
                            var container = encoder.singleValueContainer()
                            switch self {
                            case .value(let value): try container.encode(value)
                            case .inf: try container.encode("inf")
                            }
                        }
                    }
                }
            }

            /// When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Li…
            public struct CustomUnitAmount: Codable, Hashable, Sendable {
                /// Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.
                public var enabled: Bool
                /// The maximum unit amount the customer can specify for this item.
                public var maximum: Int?
                /// The minimum unit amount the customer can specify for this item.
                public var minimum: Int?
                /// The starting unit amount which can be updated by the customer.
                public var preset: Int?

                public init(
                    enabled: Bool,
                    maximum: Int? = nil,
                    minimum: Int? = nil,
                    preset: Int? = nil
                ) {
                    self.enabled = enabled
                    self.maximum = maximum
                    self.minimum = minimum
                    self.preset = preset
                }
            }

            /// The recurring components of a price such as `interval` and `interval_count`.
            public struct Recurring: Codable, Hashable, Sendable {
                /// Specifies billing frequency.
                public var interval: Interval
                /// The number of intervals between subscription billings.
                public var intervalCount: Int?

                public init(
                    interval: Interval,
                    intervalCount: Int? = nil
                ) {
                    self.interval = interval
                    self.intervalCount = intervalCount
                }

                public enum Interval: String, Codable, Hashable, Sendable {
                    case day
                    case month
                    case week
                    case year
                }
            }
        }

        public struct MarketingFeatures: Codable, Hashable, Sendable {
            /// The marketing feature name.
            public var name: String

            public init(
                name: String
            ) {
                self.name = name
            }
        }

        /// The dimensions of this product for shipping purposes.
        public struct PackageDimensions: Codable, Hashable, Sendable {
            /// Height, in inches.
            public var height: Decimal
            /// Length, in inches.
            public var length: Decimal
            /// Weight, in ounces.
            public var weight: Decimal
            /// Width, in inches.
            public var width: Decimal

            public init(
                height: Decimal,
                length: Decimal,
                weight: Decimal,
                width: Decimal
            ) {
                self.height = height
                self.length = length
                self.weight = weight
                self.width = width
            }
        }
    }

    public typealias Response = Stripe.Products.Product
}

// DELETE /v1/products/{id}
extension Stripe.Products.Product.Delete {
    public typealias Response = DeletedObject<Stripe.Products.Product>
}

// GET /v1/products
extension Stripe.Products.Product.List {
    public struct Request: Codable, Hashable, Sendable {
        /// Only return products that are active or inactive (e.g., pass `false` to list all inactive products).
        public var active: Bool?
        /// Only return products that were created during the given date interval.
        public var created: Stripe.RangeQuery?
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// Only return products with the given IDs.
        public var ids: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// Only return products that can be shipped (i.e., physical, not digital products).
        public var shippable: Bool?
        /// A cursor for use in pagination.
        public var startingAfter: String?
        /// Only return products of this type.
        public var `type`: Type?
        /// Only return products with the given url.
        public var url: String?

        public init(
            active: Bool? = nil,
            created: Stripe.RangeQuery? = nil,
            endingBefore: String? = nil,
            expand: [String]? = nil,
            ids: [String]? = nil,
            limit: Int? = nil,
            shippable: Bool? = nil,
            startingAfter: String? = nil,
            `type`: Type? = nil,
            url: String? = nil
        ) {
            self.active = active
            self.created = created
            self.endingBefore = endingBefore
            self.expand = expand
            self.ids = ids
            self.limit = limit
            self.shippable = shippable
            self.startingAfter = startingAfter
            self.`type` = `type`
            self.url = url
        }

        public enum `Type`: String, Codable, Hashable, Sendable {
            case good
            case service
        }
    }

    public typealias Response = Stripe.Page<Stripe.Products.Product>
}

// GET /v1/products/{id}
extension Stripe.Products.Product.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Products.Product
}

// GET /v1/products/search
extension Stripe.Products.Product.Search {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// A cursor for pagination across multiple pages of results.
        public var page: String?
        /// The search query string.
        public var query: String

        public init(
            expand: [String]? = nil,
            limit: Int? = nil,
            page: String? = nil,
            query: String
        ) {
            self.expand = expand
            self.limit = limit
            self.page = page
            self.query = query
        }
    }

    public typealias Response = Stripe.SearchPage<Stripe.Products.Product>
}

// POST /v1/products/{id}
extension Stripe.Products.Product.Update {
    public struct Request: Codable, Hashable, Sendable {
        /// Whether the product is available for purchase.
        public var active: Bool?
        /// The ID of the Price object that is the default price for this product.
        public var defaultPrice: String?
        /// The product's description, meant to be displayable to the customer.
        public var description: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
        public var images: Stripe.Clearable<[String]>?
        /// A list of up to 15 marketing features for this product.
        public var marketingFeatures: Stripe.Clearable<[MarketingFeatures]>?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: Stripe.Clearable<[String: String]>?
        /// The product's name, meant to be displayable to the customer.
        public var name: String?
        /// The dimensions of this product for shipping purposes.
        public var packageDimensions: Stripe.Clearable<PackageDimensions>?
        /// Whether this product is shipped (i.e., physical goods).
        public var shippable: Bool?
        /// An arbitrary string to be displayed on your customer's credit card or bank statement.
        public var statementDescriptor: String?
        /// A tax code ID.
        public var taxCode: String?
        /// A label that represents units of this product.
        public var unitLabel: String?
        /// A URL of a publicly-accessible webpage for this product.
        public var url: String?

        public init(
            active: Bool? = nil,
            defaultPrice: String? = nil,
            description: String? = nil,
            expand: [String]? = nil,
            images: Stripe.Clearable<[String]>? = nil,
            marketingFeatures: Stripe.Clearable<[MarketingFeatures]>? = nil,
            metadata: Stripe.Clearable<[String: String]>? = nil,
            name: String? = nil,
            packageDimensions: Stripe.Clearable<PackageDimensions>? = nil,
            shippable: Bool? = nil,
            statementDescriptor: String? = nil,
            taxCode: String? = nil,
            unitLabel: String? = nil,
            url: String? = nil
        ) {
            self.active = active
            self.defaultPrice = defaultPrice
            self.description = description
            self.expand = expand
            self.images = images
            self.marketingFeatures = marketingFeatures
            self.metadata = metadata
            self.name = name
            self.packageDimensions = packageDimensions
            self.shippable = shippable
            self.statementDescriptor = statementDescriptor
            self.taxCode = taxCode
            self.unitLabel = unitLabel
            self.url = url
        }

        public struct MarketingFeatures: Codable, Hashable, Sendable {
            /// The marketing feature name.
            public var name: String

            public init(
                name: String
            ) {
                self.name = name
            }
        }

        public struct PackageDimensions: Codable, Hashable, Sendable {
            /// Height, in inches.
            public var height: Decimal
            /// Length, in inches.
            public var length: Decimal
            /// Weight, in ounces.
            public var weight: Decimal
            /// Width, in inches.
            public var width: Decimal

            public init(
                height: Decimal,
                length: Decimal,
                weight: Decimal,
                width: Decimal
            ) {
                self.height = height
                self.length = length
                self.weight = weight
                self.width = width
            }
        }
    }

    public typealias Response = Stripe.Products.Product
}
