//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: event
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import Stripe

extension Generated.Events {
    /// Snapshot events allow you to track and react to activity in your Stripe integration.
    public struct Event: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// The connected account that originates the event.
        public var account: String?
        /// The Stripe API version used to render `data` when the event was created.
        public var apiVersion: String?
        /// Authentication context needed to fetch the event or related object.
        public var context: String?
        /// Time at which the object was created.
        public var created: Date?
        public var data: Data?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// String representing the object's type.
        public var object: String?
        /// Number of webhooks that haven't been successfully delivered (for example, to return a 20x response) to the URLs you sp…
        public var pendingWebhooks: Int?
        /// Information on the API request that triggers the event.
        public var request: Request?
        /// Description of the event (for example, `invoice.created` or `charge.refunded`).
        public var `type`: Type?

        private enum CodingKeys: String, CodingKey {
            case id
            case account
            case apiVersion
            case context
            case created
            case data
            case livemode
            case object
            case pendingWebhooks
            case request
            case `type`
        }

        public init(
            id: ID,
            account: String? = nil,
            apiVersion: String? = nil,
            context: String? = nil,
            created: Date? = nil,
            data: Data? = nil,
            livemode: Bool? = nil,
            object: String? = nil,
            pendingWebhooks: Int? = nil,
            request: Request? = nil,
            `type`: Type? = nil
        ) {
            self.id = id
            self.account = account
            self.apiVersion = apiVersion
            self.context = context
            self.created = created
            self.data = data
            self.livemode = livemode
            self.object = object
            self.pendingWebhooks = pendingWebhooks
            self.request = request
            self.`type` = `type`
        }

        /// Description of the event (for example, `invoice.created` or `charge.refunded`).
        public enum `Type`: String, Codable, Hashable, Sendable {
            case accountApplicationAuthorized = "account.application.authorized"
            case accountApplicationDeauthorized = "account.application.deauthorized"
            case accountExternalAccountCreated = "account.external_account.created"
            case accountExternalAccountDeleted = "account.external_account.deleted"
            case accountExternalAccountUpdated = "account.external_account.updated"
            case accountUpdated = "account.updated"
            case applicationFeeCreated = "application_fee.created"
            case applicationFeeRefundUpdated = "application_fee.refund.updated"
            case applicationFeeRefunded = "application_fee.refunded"
            case balanceAvailable = "balance.available"
            case balanceSettingsUpdated = "balance_settings.updated"
            case billingAlertTriggered = "billing.alert.triggered"
            case billingCreditBalanceTransactionCreated = "billing.credit_balance_transaction.created"
            case billingCreditGrantCreated = "billing.credit_grant.created"
            case billingCreditGrantUpdated = "billing.credit_grant.updated"
            case billingMeterCreated = "billing.meter.created"
            case billingMeterDeactivated = "billing.meter.deactivated"
            case billingMeterReactivated = "billing.meter.reactivated"
            case billingMeterUpdated = "billing.meter.updated"
            case billingPortalConfigurationCreated = "billing_portal.configuration.created"
            case billingPortalConfigurationUpdated = "billing_portal.configuration.updated"
            case billingPortalSessionCreated = "billing_portal.session.created"
            case capabilityUpdated = "capability.updated"
            case cashBalanceFundsAvailable = "cash_balance.funds_available"
            case chargeCaptured = "charge.captured"
            case chargeDisputeClosed = "charge.dispute.closed"
            case chargeDisputeCreated = "charge.dispute.created"
            case chargeDisputeFundsReinstated = "charge.dispute.funds_reinstated"
            case chargeDisputeFundsWithdrawn = "charge.dispute.funds_withdrawn"
            case chargeDisputeUpdated = "charge.dispute.updated"
            case chargeExpired = "charge.expired"
            case chargeFailed = "charge.failed"
            case chargePending = "charge.pending"
            case chargeRefundUpdated = "charge.refund.updated"
            case chargeRefunded = "charge.refunded"
            case chargeSucceeded = "charge.succeeded"
            case chargeUpdated = "charge.updated"
            case checkoutSessionAsyncPaymentFailed = "checkout.session.async_payment_failed"
            case checkoutSessionAsyncPaymentSucceeded = "checkout.session.async_payment_succeeded"
            case checkoutSessionCompleted = "checkout.session.completed"
            case checkoutSessionExpired = "checkout.session.expired"
            case climateOrderCanceled = "climate.order.canceled"
            case climateOrderCreated = "climate.order.created"
            case climateOrderDelayed = "climate.order.delayed"
            case climateOrderDelivered = "climate.order.delivered"
            case climateOrderProductSubstituted = "climate.order.product_substituted"
            case climateProductCreated = "climate.product.created"
            case climateProductPricingUpdated = "climate.product.pricing_updated"
            case couponCreated = "coupon.created"
            case couponDeleted = "coupon.deleted"
            case couponUpdated = "coupon.updated"
            case creditNoteCreated = "credit_note.created"
            case creditNoteUpdated = "credit_note.updated"
            case creditNoteVoided = "credit_note.voided"
            case customerCreated = "customer.created"
            case customerDeleted = "customer.deleted"
            case customerDiscountCreated = "customer.discount.created"
            case customerDiscountDeleted = "customer.discount.deleted"
            case customerDiscountUpdated = "customer.discount.updated"
            case customerSourceCreated = "customer.source.created"
            case customerSourceDeleted = "customer.source.deleted"
            case customerSourceExpiring = "customer.source.expiring"
            case customerSourceUpdated = "customer.source.updated"
            case customerSubscriptionCreated = "customer.subscription.created"
            case customerSubscriptionDeleted = "customer.subscription.deleted"
            case customerSubscriptionPaused = "customer.subscription.paused"
            case customerSubscriptionPendingUpdateApplied = "customer.subscription.pending_update_applied"
            case customerSubscriptionPendingUpdateExpired = "customer.subscription.pending_update_expired"
            case customerSubscriptionResumed = "customer.subscription.resumed"
            case customerSubscriptionTrialWillEnd = "customer.subscription.trial_will_end"
            case customerSubscriptionUpdated = "customer.subscription.updated"
            case customerTaxIdCreated = "customer.tax_id.created"
            case customerTaxIdDeleted = "customer.tax_id.deleted"
            case customerTaxIdUpdated = "customer.tax_id.updated"
            case customerUpdated = "customer.updated"
            case customerCashBalanceTransactionCreated = "customer_cash_balance_transaction.created"
            case entitlementsActiveEntitlementSummaryUpdated = "entitlements.active_entitlement_summary.updated"
            case fileCreated = "file.created"
            case financialConnectionsAccountAccountNumbersUpdated = "financial_connections.account.account_numbers_updated"
            case financialConnectionsAccountCreated = "financial_connections.account.created"
            case financialConnectionsAccountDeactivated = "financial_connections.account.deactivated"
            case financialConnectionsAccountDisconnected = "financial_connections.account.disconnected"
            case financialConnectionsAccountExpectedDeactivationDateUpdated = "financial_connections.account.expected_deactivation_date_updated"
            case financialConnectionsAccountReactivated = "financial_connections.account.reactivated"
            case financialConnectionsAccountRefreshedBalance = "financial_connections.account.refreshed_balance"
            case financialConnectionsAccountRefreshedOwnership = "financial_connections.account.refreshed_ownership"
            case financialConnectionsAccountRefreshedTransactions = "financial_connections.account.refreshed_transactions"
            case financialConnectionsAccountSupportedPaymentMethodTypesUpdated = "financial_connections.account.supported_payment_method_types_updated"
            case financialConnectionsAccountUpcomingAccountNumberExpiry = "financial_connections.account.upcoming_account_number_expiry"
            case financialConnectionsAccountUpcomingDeactivation = "financial_connections.account.upcoming_deactivation"
            case financialConnectionsAuthorizationExpectedDeactivationDateUpdated = "financial_connections.authorization.expected_deactivation_date_updated"
            case financialConnectionsAuthorizationUpcomingDeactivation = "financial_connections.authorization.upcoming_deactivation"
            case identityVerificationSessionCanceled = "identity.verification_session.canceled"
            case identityVerificationSessionCreated = "identity.verification_session.created"
            case identityVerificationSessionProcessing = "identity.verification_session.processing"
            case identityVerificationSessionRedacted = "identity.verification_session.redacted"
            case identityVerificationSessionRequiresInput = "identity.verification_session.requires_input"
            case identityVerificationSessionVerified = "identity.verification_session.verified"
            case invoiceCreated = "invoice.created"
            case invoiceDeleted = "invoice.deleted"
            case invoiceFinalizationFailed = "invoice.finalization_failed"
            case invoiceFinalized = "invoice.finalized"
            case invoiceMarkedUncollectible = "invoice.marked_uncollectible"
            case invoiceOverdue = "invoice.overdue"
            case invoiceOverpaid = "invoice.overpaid"
            case invoicePaid = "invoice.paid"
            case invoicePaymentActionRequired = "invoice.payment_action_required"
            case invoicePaymentAttemptRequired = "invoice.payment_attempt_required"
            case invoicePaymentFailed = "invoice.payment_failed"
            case invoicePaymentSucceeded = "invoice.payment_succeeded"
            case invoiceSent = "invoice.sent"
            case invoiceUpcoming = "invoice.upcoming"
            case invoiceUpdated = "invoice.updated"
            case invoiceVoided = "invoice.voided"
            case invoiceWillBeDue = "invoice.will_be_due"
            case invoicePaymentPaid = "invoice_payment.paid"
            case invoiceitemCreated = "invoiceitem.created"
            case invoiceitemDeleted = "invoiceitem.deleted"
            case issuingAuthorizationCreated = "issuing_authorization.created"
            case issuingAuthorizationRequest = "issuing_authorization.request"
            case issuingAuthorizationUpdated = "issuing_authorization.updated"
            case issuingCardCreated = "issuing_card.created"
            case issuingCardUpdated = "issuing_card.updated"
            case issuingCardholderCreated = "issuing_cardholder.created"
            case issuingCardholderUpdated = "issuing_cardholder.updated"
            case issuingDisputeClosed = "issuing_dispute.closed"
            case issuingDisputeCreated = "issuing_dispute.created"
            case issuingDisputeFundsReinstated = "issuing_dispute.funds_reinstated"
            case issuingDisputeFundsRescinded = "issuing_dispute.funds_rescinded"
            case issuingDisputeSubmitted = "issuing_dispute.submitted"
            case issuingDisputeUpdated = "issuing_dispute.updated"
            case issuingPersonalizationDesignActivated = "issuing_personalization_design.activated"
            case issuingPersonalizationDesignDeactivated = "issuing_personalization_design.deactivated"
            case issuingPersonalizationDesignRejected = "issuing_personalization_design.rejected"
            case issuingPersonalizationDesignUpdated = "issuing_personalization_design.updated"
            case issuingTokenCreated = "issuing_token.created"
            case issuingTokenUpdated = "issuing_token.updated"
            case issuingTransactionCreated = "issuing_transaction.created"
            case issuingTransactionPurchaseDetailsReceiptUpdated = "issuing_transaction.purchase_details_receipt_updated"
            case issuingTransactionUpdated = "issuing_transaction.updated"
            case mandateUpdated = "mandate.updated"
            case paymentIntentAmountCapturableUpdated = "payment_intent.amount_capturable_updated"
            case paymentIntentCanceled = "payment_intent.canceled"
            case paymentIntentCreated = "payment_intent.created"
            case paymentIntentPartiallyFunded = "payment_intent.partially_funded"
            case paymentIntentPaymentFailed = "payment_intent.payment_failed"
            case paymentIntentProcessing = "payment_intent.processing"
            case paymentIntentRequiresAction = "payment_intent.requires_action"
            case paymentIntentSucceeded = "payment_intent.succeeded"
            case paymentLinkCreated = "payment_link.created"
            case paymentLinkUpdated = "payment_link.updated"
            case paymentMethodAttached = "payment_method.attached"
            case paymentMethodAutomaticallyUpdated = "payment_method.automatically_updated"
            case paymentMethodDetached = "payment_method.detached"
            case paymentMethodUpdated = "payment_method.updated"
            case payoutCanceled = "payout.canceled"
            case payoutCreated = "payout.created"
            case payoutFailed = "payout.failed"
            case payoutPaid = "payout.paid"
            case payoutReconciliationCompleted = "payout.reconciliation_completed"
            case payoutUpdated = "payout.updated"
            case personCreated = "person.created"
            case personDeleted = "person.deleted"
            case personUpdated = "person.updated"
            case planCreated = "plan.created"
            case planDeleted = "plan.deleted"
            case planUpdated = "plan.updated"
            case priceCreated = "price.created"
            case priceDeleted = "price.deleted"
            case priceUpdated = "price.updated"
            case productCreated = "product.created"
            case productDeleted = "product.deleted"
            case productUpdated = "product.updated"
            case promotionCodeCreated = "promotion_code.created"
            case promotionCodeUpdated = "promotion_code.updated"
            case quoteAccepted = "quote.accepted"
            case quoteCanceled = "quote.canceled"
            case quoteCreated = "quote.created"
            case quoteFinalized = "quote.finalized"
            case radarEarlyFraudWarningCreated = "radar.early_fraud_warning.created"
            case radarEarlyFraudWarningUpdated = "radar.early_fraud_warning.updated"
            case refundCreated = "refund.created"
            case refundFailed = "refund.failed"
            case refundUpdated = "refund.updated"
            case reportingReportRunFailed = "reporting.report_run.failed"
            case reportingReportRunSucceeded = "reporting.report_run.succeeded"
            case reportingReportTypeUpdated = "reporting.report_type.updated"
            case reserveHoldCreated = "reserve.hold.created"
            case reserveHoldUpdated = "reserve.hold.updated"
            case reservePlanCreated = "reserve.plan.created"
            case reservePlanDisabled = "reserve.plan.disabled"
            case reservePlanExpired = "reserve.plan.expired"
            case reservePlanUpdated = "reserve.plan.updated"
            case reserveReleaseCreated = "reserve.release.created"
            case reviewClosed = "review.closed"
            case reviewOpened = "review.opened"
            case setupIntentCanceled = "setup_intent.canceled"
            case setupIntentCreated = "setup_intent.created"
            case setupIntentRequiresAction = "setup_intent.requires_action"
            case setupIntentSetupFailed = "setup_intent.setup_failed"
            case setupIntentSucceeded = "setup_intent.succeeded"
            case sigmaScheduledQueryRunCreated = "sigma.scheduled_query_run.created"
            case sourceCanceled = "source.canceled"
            case sourceChargeable = "source.chargeable"
            case sourceFailed = "source.failed"
            case sourceMandateNotification = "source.mandate_notification"
            case sourceRefundAttributesRequired = "source.refund_attributes_required"
            case sourceTransactionCreated = "source.transaction.created"
            case sourceTransactionUpdated = "source.transaction.updated"
            case subscriptionScheduleAborted = "subscription_schedule.aborted"
            case subscriptionScheduleCanceled = "subscription_schedule.canceled"
            case subscriptionScheduleCompleted = "subscription_schedule.completed"
            case subscriptionScheduleCreated = "subscription_schedule.created"
            case subscriptionScheduleExpiring = "subscription_schedule.expiring"
            case subscriptionScheduleReleased = "subscription_schedule.released"
            case subscriptionScheduleUpdated = "subscription_schedule.updated"
            case taxSettingsUpdated = "tax.settings.updated"
            case taxRateCreated = "tax_rate.created"
            case taxRateUpdated = "tax_rate.updated"
            case terminalReaderActionFailed = "terminal.reader.action_failed"
            case terminalReaderActionSucceeded = "terminal.reader.action_succeeded"
            case terminalReaderActionUpdated = "terminal.reader.action_updated"
            case testHelpersTestClockAdvancing = "test_helpers.test_clock.advancing"
            case testHelpersTestClockCreated = "test_helpers.test_clock.created"
            case testHelpersTestClockDeleted = "test_helpers.test_clock.deleted"
            case testHelpersTestClockInternalFailure = "test_helpers.test_clock.internal_failure"
            case testHelpersTestClockReady = "test_helpers.test_clock.ready"
            case topupCanceled = "topup.canceled"
            case topupCreated = "topup.created"
            case topupFailed = "topup.failed"
            case topupReversed = "topup.reversed"
            case topupSucceeded = "topup.succeeded"
            case transferCreated = "transfer.created"
            case transferReversed = "transfer.reversed"
            case transferUpdated = "transfer.updated"
            case treasuryCreditReversalCreated = "treasury.credit_reversal.created"
            case treasuryCreditReversalPosted = "treasury.credit_reversal.posted"
            case treasuryDebitReversalCompleted = "treasury.debit_reversal.completed"
            case treasuryDebitReversalCreated = "treasury.debit_reversal.created"
            case treasuryDebitReversalInitialCreditGranted = "treasury.debit_reversal.initial_credit_granted"
            case treasuryFinancialAccountClosed = "treasury.financial_account.closed"
            case treasuryFinancialAccountCreated = "treasury.financial_account.created"
            case treasuryFinancialAccountFeaturesStatusUpdated = "treasury.financial_account.features_status_updated"
            case treasuryInboundTransferCanceled = "treasury.inbound_transfer.canceled"
            case treasuryInboundTransferCreated = "treasury.inbound_transfer.created"
            case treasuryInboundTransferFailed = "treasury.inbound_transfer.failed"
            case treasuryInboundTransferSucceeded = "treasury.inbound_transfer.succeeded"
            case treasuryOutboundPaymentCanceled = "treasury.outbound_payment.canceled"
            case treasuryOutboundPaymentCreated = "treasury.outbound_payment.created"
            case treasuryOutboundPaymentExpectedArrivalDateUpdated = "treasury.outbound_payment.expected_arrival_date_updated"
            case treasuryOutboundPaymentFailed = "treasury.outbound_payment.failed"
            case treasuryOutboundPaymentPosted = "treasury.outbound_payment.posted"
            case treasuryOutboundPaymentReturned = "treasury.outbound_payment.returned"
            case treasuryOutboundPaymentTrackingDetailsUpdated = "treasury.outbound_payment.tracking_details_updated"
            case treasuryOutboundTransferCanceled = "treasury.outbound_transfer.canceled"
            case treasuryOutboundTransferCreated = "treasury.outbound_transfer.created"
            case treasuryOutboundTransferExpectedArrivalDateUpdated = "treasury.outbound_transfer.expected_arrival_date_updated"
            case treasuryOutboundTransferFailed = "treasury.outbound_transfer.failed"
            case treasuryOutboundTransferPosted = "treasury.outbound_transfer.posted"
            case treasuryOutboundTransferReturned = "treasury.outbound_transfer.returned"
            case treasuryOutboundTransferTrackingDetailsUpdated = "treasury.outbound_transfer.tracking_details_updated"
            case treasuryReceivedCreditCreated = "treasury.received_credit.created"
            case treasuryReceivedCreditFailed = "treasury.received_credit.failed"
            case treasuryReceivedCreditSucceeded = "treasury.received_credit.succeeded"
            case treasuryReceivedDebitCreated = "treasury.received_debit.created"
        }

        public struct Data: Codable, Hashable, Sendable {
            /// Object containing the API resource relevant to the event.
            public var object: [String: String]?
            /// Object containing the names of the updated attributes and their values prior to the event (only included in events of …
            public var previousAttributes: [String: String]?

            private enum CodingKeys: String, CodingKey {
                case object
                case previousAttributes
            }

            public init(
                object: [String: String]? = nil,
                previousAttributes: [String: String]? = nil
            ) {
                self.object = object
                self.previousAttributes = previousAttributes
            }
        }

        public struct Request: Codable, Hashable, Sendable, Identifiable {
            public typealias ID = String
            public let id: ID
            /// The idempotency key transmitted during the request, if any.
            public var idempotencyKey: String?

            private enum CodingKeys: String, CodingKey {
                case id
                case idempotencyKey
            }

            public init(
                id: ID,
                idempotencyKey: String? = nil
            ) {
                self.id = id
                self.idempotencyKey = idempotencyKey
            }
        }
    }
}
