//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: apple_pay_domain
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe {
    public struct ApplePayDomain: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Time at which the object was created.
        public var created: Date?
        public var domainName: String?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?

        private enum CodingKeys: String, CodingKey {
            case id
            case object
            case created
            case domainName
            case livemode
        }

        public init(
            id: ID,
            object: String,
            created: Date? = nil,
            domainName: String? = nil,
            livemode: Bool? = nil
        ) {
            self.id = id
            self.object = object
            self.created = created
            self.domainName = domainName
            self.livemode = livemode
        }
    }
}
