//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: bank_account
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// These bank accounts are payment methods on `Customer` objects.
public struct BankAccount: Codable, Hashable, Sendable, Identifiable {
    public typealias ID = String
    public let id: ID
    /// String representing the object's type.
    public let object: String
    /// The account this bank account belongs to.
    @Expandable<Stripe.Connect.Account, String> public var account: String?
    /// The name of the person or business that owns the bank account.
    public var accountHolderName: String?
    /// The type of entity that holds the account.
    public var accountHolderType: String?
    /// The bank account type.
    public var accountType: String?
    /// A set of available payout methods for this bank account.
    public var availablePayoutMethods: [AvailablePayoutMethods]?
    /// Name of the bank associated with the routing number (e.g., `WELLS FARGO`).
    public var bankName: String?
    /// Two-letter ISO code representing the country the bank account is located in.
    public var country: String?
    /// Three-letter ISO code for the currency paid out to the bank account.
    public var currency: Stripe.Currency?
    /// The ID of the customer that the bank account is associated with.
    @Expandable<Stripe.Customers.Customer, String> public var customer: String?
    /// Whether this bank account is the default external account for its currency.
    public var defaultForCurrency: Bool?
    /// Uniquely identifies this particular bank account.
    public var fingerprint: String?
    /// Information about the upcoming new requirements for the bank account, including what information needs to be collected…
    public var futureRequirements: FutureRequirements?
    /// The last four digits of the bank account number.
    public var last4: String?
    /// Set of key-value pairs that you can attach to an object.
    public var metadata: [String: String]?
    /// Information about the requirements for the bank account, including what information needs to be collected.
    public var requirements: Requirements?
    /// The routing transit number for the bank account.
    public var routingNumber: String?
    /// For bank accounts, possible values are `new`, `validated`, `verified`, `verification_failed`, `tokenized_account_numbe…
    public var status: String?

    private enum CodingKeys: String, CodingKey {
        case id
        case object
        case account
        case accountHolderName
        case accountHolderType
        case accountType
        case availablePayoutMethods
        case bankName
        case country
        case currency
        case customer
        case defaultForCurrency
        case fingerprint
        case futureRequirements
        case last4
        case metadata
        case requirements
        case routingNumber
        case status
    }

    public init(
        id: ID,
        object: String,
        account: String? = nil,
        accountHolderName: String? = nil,
        accountHolderType: String? = nil,
        accountType: String? = nil,
        availablePayoutMethods: [AvailablePayoutMethods]? = nil,
        bankName: String? = nil,
        country: String? = nil,
        currency: Stripe.Currency? = nil,
        customer: String? = nil,
        defaultForCurrency: Bool? = nil,
        fingerprint: String? = nil,
        futureRequirements: FutureRequirements? = nil,
        last4: String? = nil,
        metadata: [String: String]? = nil,
        requirements: Requirements? = nil,
        routingNumber: String? = nil,
        status: String? = nil
    ) {
        self.id = id
        self.object = object
        self._account = Expandable(id: account)
        self.accountHolderName = accountHolderName
        self.accountHolderType = accountHolderType
        self.accountType = accountType
        self.availablePayoutMethods = availablePayoutMethods
        self.bankName = bankName
        self.country = country
        self.currency = currency
        self._customer = Expandable(id: customer)
        self.defaultForCurrency = defaultForCurrency
        self.fingerprint = fingerprint
        self.futureRequirements = futureRequirements
        self.last4 = last4
        self.metadata = metadata
        self.requirements = requirements
        self.routingNumber = routingNumber
        self.status = status
    }

    public enum AvailablePayoutMethods: String, Codable, Hashable, Sendable {
        case instant
        case standard
    }

    public struct FutureRequirements: Codable, Hashable, Sendable {
        /// Fields that need to be resolved to keep the external account enabled.
        public var currentlyDue: [String]?
        /// Fields that are `currently_due` and need to be collected again because validation or verification failed.
        public var errors: [Stripe.Shared.Errors]?
        /// Fields that haven't been resolved by `current_deadline`.
        public var pastDue: [String]?
        /// Fields that are being reviewed, or might become required depending on the results of a review.
        public var pendingVerification: [String]?

        private enum CodingKeys: String, CodingKey {
            case currentlyDue
            case errors
            case pastDue
            case pendingVerification
        }

        public init(
            currentlyDue: [String]? = nil,
            errors: [Stripe.Shared.Errors]? = nil,
            pastDue: [String]? = nil,
            pendingVerification: [String]? = nil
        ) {
            self.currentlyDue = currentlyDue
            self.errors = errors
            self.pastDue = pastDue
            self.pendingVerification = pendingVerification
        }
    }

    public struct Requirements: Codable, Hashable, Sendable {
        /// Fields that need to be resolved to keep the external account enabled.
        public var currentlyDue: [String]?
        /// Fields that are `currently_due` and need to be collected again because validation or verification failed.
        public var errors: [Stripe.Shared.Errors]?
        /// Fields that haven't been resolved by `current_deadline`.
        public var pastDue: [String]?
        /// Fields that are being reviewed, or might become required depending on the results of a review.
        public var pendingVerification: [String]?

        private enum CodingKeys: String, CodingKey {
            case currentlyDue
            case errors
            case pastDue
            case pendingVerification
        }

        public init(
            currentlyDue: [String]? = nil,
            errors: [Stripe.Shared.Errors]? = nil,
            pastDue: [String]? = nil,
            pendingVerification: [String]? = nil
        ) {
            self.currentlyDue = currentlyDue
            self.errors = errors
            self.pastDue = pastDue
            self.pendingVerification = pendingVerification
        }
    }
}
