//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: card
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// You can store multiple cards on a customer in order to charge the customer later.
public struct Card: Codable, Hashable, Sendable, Identifiable {
    public typealias ID = String
    public let id: ID
    /// String representing the object's type.
    public let object: String
    @Expandable<Stripe.Connect.Account, String> public var account: String?
    /// City/District/Suburb/Town/Village.
    public var addressCity: String?
    /// Billing address country, if provided when creating card.
    public var addressCountry: String?
    /// Address line 1 (Street address/PO Box/Company name).
    public var addressLine1: String?
    /// If `address_line1` was provided, results of the check: `pass`, `fail`, `unavailable`, or `unchecked`.
    public var addressLine1Check: String?
    /// Address line 2 (Apartment/Suite/Unit/Building).
    public var addressLine2: String?
    /// State/County/Province/Region.
    public var addressState: String?
    /// ZIP or postal code.
    public var addressZip: String?
    /// If `address_zip` was provided, results of the check: `pass`, `fail`, `unavailable`, or `unchecked`.
    public var addressZipCheck: String?
    /// This field indicates whether this payment method can be shown again to its customer in a checkout flow.
    public var allowRedisplay: AllowRedisplay?
    /// A set of available payout methods for this card.
    public var availablePayoutMethods: [AvailablePayoutMethods]?
    /// Card brand.
    public var brand: String?
    /// Two-letter ISO code representing the country of the card.
    public var country: String?
    /// Three-letter ISO code for currency in lowercase.
    public var currency: Stripe.Currency?
    /// The customer that this card belongs to.
    @Expandable<Stripe.Customers.Customer, String> public var customer: String?
    /// If a CVC was provided, results of the check: `pass`, `fail`, `unavailable`, or `unchecked`.
    public var cvcCheck: String?
    /// Whether this card is the default external account for its currency.
    public var defaultForCurrency: Bool?
    /// A high-level description of the type of cards issued in this range.
    public var description: String?
    /// (For tokenized numbers only.) The last four digits of the device account number.
    public var dynamicLast4: String?
    /// Two-digit number representing the card's expiration month.
    public var expMonth: Int?
    /// Four-digit number representing the card's expiration year.
    public var expYear: Int?
    /// Uniquely identifies this particular card number.
    public var fingerprint: String?
    /// Card funding type.
    public var funding: String?
    /// Issuer identification number of the card.
    public var iin: String?
    /// The name of the card's issuing bank.
    public var issuer: String?
    /// The last four digits of the card.
    public var last4: String?
    /// Set of key-value pairs that you can attach to an object.
    public var metadata: [String: String]?
    /// Cardholder name.
    public var name: String?
    public var networks: Networks?
    /// Status of a card based on the card issuer.
    public var regulatedStatus: RegulatedStatus?
    /// For external accounts that are cards, possible values are `new` and `errored`.
    public var status: String?
    /// If the card number is tokenized, this is the method that was used.
    public var tokenizationMethod: String?

    public init(
        id: ID,
        object: String,
        account: String? = nil,
        addressCity: String? = nil,
        addressCountry: String? = nil,
        addressLine1: String? = nil,
        addressLine1Check: String? = nil,
        addressLine2: String? = nil,
        addressState: String? = nil,
        addressZip: String? = nil,
        addressZipCheck: String? = nil,
        allowRedisplay: AllowRedisplay? = nil,
        availablePayoutMethods: [AvailablePayoutMethods]? = nil,
        brand: String? = nil,
        country: String? = nil,
        currency: Stripe.Currency? = nil,
        customer: String? = nil,
        cvcCheck: String? = nil,
        defaultForCurrency: Bool? = nil,
        description: String? = nil,
        dynamicLast4: String? = nil,
        expMonth: Int? = nil,
        expYear: Int? = nil,
        fingerprint: String? = nil,
        funding: String? = nil,
        iin: String? = nil,
        issuer: String? = nil,
        last4: String? = nil,
        metadata: [String: String]? = nil,
        name: String? = nil,
        networks: Networks? = nil,
        regulatedStatus: RegulatedStatus? = nil,
        status: String? = nil,
        tokenizationMethod: String? = nil
    ) {
        self.id = id
        self.object = object
        self._account = Expandable(id: account)
        self.addressCity = addressCity
        self.addressCountry = addressCountry
        self.addressLine1 = addressLine1
        self.addressLine1Check = addressLine1Check
        self.addressLine2 = addressLine2
        self.addressState = addressState
        self.addressZip = addressZip
        self.addressZipCheck = addressZipCheck
        self.allowRedisplay = allowRedisplay
        self.availablePayoutMethods = availablePayoutMethods
        self.brand = brand
        self.country = country
        self.currency = currency
        self._customer = Expandable(id: customer)
        self.cvcCheck = cvcCheck
        self.defaultForCurrency = defaultForCurrency
        self.description = description
        self.dynamicLast4 = dynamicLast4
        self.expMonth = expMonth
        self.expYear = expYear
        self.fingerprint = fingerprint
        self.funding = funding
        self.iin = iin
        self.issuer = issuer
        self.last4 = last4
        self.metadata = metadata
        self.name = name
        self.networks = networks
        self.regulatedStatus = regulatedStatus
        self.status = status
        self.tokenizationMethod = tokenizationMethod
    }

    /// This field indicates whether this payment method can be shown again to its customer in a checkout flow.
    public enum AllowRedisplay: String, Codable, Hashable, Sendable {
        case always
        case limited
        case unspecified
    }

    public enum AvailablePayoutMethods: String, Codable, Hashable, Sendable {
        case instant
        case standard
    }

    /// Status of a card based on the card issuer.
    public enum RegulatedStatus: String, Codable, Hashable, Sendable {
        case regulated
        case unregulated
    }

    public struct Networks: Codable, Hashable, Sendable {
        /// The preferred network for co-branded cards.
        public var preferred: String?

        public init(
            preferred: String? = nil
        ) {
            self.preferred = preferred
        }
    }
}
