//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: exchange_rate
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe {
    /// [Deprecated] The `ExchangeRate` APIs are deprecated.
    public struct ExchangeRate: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Hash where the keys are supported currencies and the values are the exchange rate at which the base id currency conver…
        public var rates: [String: Double]?

        public init(
            id: ID,
            object: String,
            rates: [String: Double]? = nil
        ) {
            self.id = id
            self.object = object
            self.rates = rates
        }
    }
}
