//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: reporting.report_run
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// The Report Run object represents an instance of a report type generated with specific run parameters.
public struct ReportRun: Codable, Hashable, Sendable, Identifiable {
    public typealias ID = String
    public let id: ID
    /// String representing the object's type.
    public let object: String
    /// Time at which the object was created.
    public var created: Date?
    /// If something should go wrong during the run, a message about the failure (populated when `status=failed`).
    public var error: String?
    /// `true` if the report is run on live mode data and `false` if it is run on test mode data.
    public var livemode: Bool?
    public var parameters: Parameters?
    /// The ID of the report type to run, such as `"balance.summary.1"`.
    public var reportType: String?
    /// The file object representing the result of the report run (populated when `status=succeeded`).
    @Boxed public var result: Stripe.Files.File?
    /// Status of this report run.
    public var status: String?
    /// Timestamp at which this run successfully finished (populated when `status=succeeded`).
    public var succeededAt: Date?

    private enum CodingKeys: String, CodingKey {
        case id
        case object
        case created
        case error
        case livemode
        case parameters
        case reportType
        case result
        case status
        case succeededAt
    }

    public init(
        id: ID,
        object: String,
        created: Date? = nil,
        error: String? = nil,
        livemode: Bool? = nil,
        parameters: Parameters? = nil,
        reportType: String? = nil,
        result: Stripe.Files.File? = nil,
        status: String? = nil,
        succeededAt: Date? = nil
    ) {
        self.id = id
        self.object = object
        self.created = created
        self.error = error
        self.livemode = livemode
        self.parameters = parameters
        self.reportType = reportType
        self._result = Boxed(wrappedValue: result)
        self.status = status
        self.succeededAt = succeededAt
    }

    public struct Parameters: Codable, Hashable, Sendable {
        /// The set of output columns requested for inclusion in the report run.
        public var columns: [String]?
        /// Connected account ID by which to filter the report run.
        public var connectedAccount: String?
        /// Currency of objects to be included in the report run.
        public var currency: Stripe.Currency?
        /// Ending timestamp of data to be included in the report run.
        public var intervalEnd: Date?
        /// Starting timestamp of data to be included in the report run.
        public var intervalStart: Date?
        /// Payout ID by which to filter the report run.
        public var payout: String?
        /// Category of balance transactions to be included in the report run.
        public var reportingCategory: String?
        /// Defaults to `Etc/UTC`.
        public var timezone: String?

        private enum CodingKeys: String, CodingKey {
            case columns
            case connectedAccount
            case currency
            case intervalEnd
            case intervalStart
            case payout
            case reportingCategory
            case timezone
        }

        public init(
            columns: [String]? = nil,
            connectedAccount: String? = nil,
            currency: Stripe.Currency? = nil,
            intervalEnd: Date? = nil,
            intervalStart: Date? = nil,
            payout: String? = nil,
            reportingCategory: String? = nil,
            timezone: String? = nil
        ) {
            self.columns = columns
            self.connectedAccount = connectedAccount
            self.currency = currency
            self.intervalEnd = intervalEnd
            self.intervalStart = intervalStart
            self.payout = payout
            self.reportingCategory = reportingCategory
            self.timezone = timezone
        }
    }
}
