//
//  Generated by Scripts/generate-models.py — do not edit.
//  Source: Stripe OpenAPI spec, version 2026-07-29.dahlia
//  Schema: promotion_code
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Promotion {
    /// A Promotion Code represents a customer-redeemable code for an underlying promotion.
    public struct Code: Codable, Hashable, Sendable, Identifiable {
        public typealias ID = String
        public let id: ID
        /// String representing the object's type.
        public let object: String
        /// Whether the promotion code is currently active.
        public var active: Bool?
        /// The customer-facing code.
        public var code: String?
        /// Time at which the object was created.
        public var created: Date?
        /// The customer who can use this promotion code.
        @Expandable<Stripe.Customers.Customer, String> public var customer: String?
        /// The account representing the customer who can use this promotion code.
        public var customerAccount: String?
        /// Date at which the promotion code can no longer be redeemed.
        public var expiresAt: Date?
        /// If the object exists in live mode, the value is `true`.
        public var livemode: Bool?
        /// Maximum number of times this promotion code can be redeemed.
        public var maxRedemptions: Int?
        /// Set of key-value pairs that you can attach to an object.
        public var metadata: [String: String]?
        public var promotion: Promotion?
        public var restrictions: Restrictions?
        /// Number of times this promotion code has been used.
        public var timesRedeemed: Int?

        public init(
            id: ID,
            object: String,
            active: Bool? = nil,
            code: String? = nil,
            created: Date? = nil,
            customer: String? = nil,
            customerAccount: String? = nil,
            expiresAt: Date? = nil,
            livemode: Bool? = nil,
            maxRedemptions: Int? = nil,
            metadata: [String: String]? = nil,
            promotion: Promotion? = nil,
            restrictions: Restrictions? = nil,
            timesRedeemed: Int? = nil
        ) {
            self.id = id
            self.object = object
            self.active = active
            self.code = code
            self.created = created
            self._customer = Expandable(id: customer)
            self.customerAccount = customerAccount
            self.expiresAt = expiresAt
            self.livemode = livemode
            self.maxRedemptions = maxRedemptions
            self.metadata = metadata
            self.promotion = promotion
            self.restrictions = restrictions
            self.timesRedeemed = timesRedeemed
        }

        public struct Promotion: Codable, Hashable, Sendable {
            /// If promotion `type` is `coupon`, the coupon for this promotion.
            @Expandable<Stripe.Products.Coupon, String> public var coupon: String?
            /// The type of promotion.
            public var `type`: String?

            public init(
                coupon: String? = nil,
                `type`: String? = nil
            ) {
                self._coupon = Expandable(id: coupon)
                self.`type` = `type`
            }
        }

        public struct Restrictions: Codable, Hashable, Sendable {
            /// Promotion code restrictions defined in each available currency option.
            public var currencyOptions: [String: CurrencyOptions]?
            /// A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or in…
            public var firstTimeTransaction: Bool?
            /// Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
            public var minimumAmount: Int?
            /// Three-letter ISO code for minimum_amount
            public var minimumAmountCurrency: String?

            public init(
                currencyOptions: [String: CurrencyOptions]? = nil,
                firstTimeTransaction: Bool? = nil,
                minimumAmount: Int? = nil,
                minimumAmountCurrency: String? = nil
            ) {
                self.currencyOptions = currencyOptions
                self.firstTimeTransaction = firstTimeTransaction
                self.minimumAmount = minimumAmount
                self.minimumAmountCurrency = minimumAmountCurrency
            }

            public struct CurrencyOptions: Codable, Hashable, Sendable {
                /// Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
                public var minimumAmount: Int?

                public init(
                    minimumAmount: Int? = nil
                ) {
                    self.minimumAmount = minimumAmount
                }
            }
        }
    }
}
