//
//  Fraud/ValueListItems/ValueListItem+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Fraud.ValueListItems.ValueListItem {
    public enum Create {}
    public enum Delete {}
    public enum List {}
    public enum Retrieve {}
}

// POST /v1/radar/value_list_items
extension Stripe.Fraud.ValueListItems.ValueListItem.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// The value of the item (whose type must match the type of the parent value list).
        public var value: String
        /// The identifier of the value list which the created item will be added to.
        public var valueList: String

        private enum CodingKeys: String, CodingKey {
            case expand
            case value
            case valueList
        }

        public init(
            expand: [String]? = nil,
            value: String,
            valueList: String
        ) {
            self.expand = expand
            self.value = value
            self.valueList = valueList
        }
    }

    public typealias Response = Stripe.Fraud.ValueListItems.ValueListItem
}

// DELETE /v1/radar/value_list_items/{item}
extension Stripe.Fraud.ValueListItems.ValueListItem.Delete {
    public typealias Response = DeletedObject<Stripe.Fraud.ValueListItems.ValueListItem>
}

// GET /v1/radar/value_list_items
extension Stripe.Fraud.ValueListItems.ValueListItem.List {
    public struct Request: Codable, Hashable, Sendable {
        /// Only return items that were created during the given date interval.
        public var created: Stripe.RangeQuery?
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// A cursor for use in pagination.
        public var startingAfter: String?
        /// Return items belonging to the parent list whose value matches the specified value (using an "is like" match).
        public var value: String?
        /// Identifier for the parent value list this item belongs to.
        public var valueList: String

        private enum CodingKeys: String, CodingKey {
            case created
            case endingBefore
            case expand
            case limit
            case startingAfter
            case value
            case valueList
        }

        public init(
            created: Stripe.RangeQuery? = nil,
            endingBefore: String? = nil,
            expand: [String]? = nil,
            limit: Int? = nil,
            startingAfter: String? = nil,
            value: String? = nil,
            valueList: String
        ) {
            self.created = created
            self.endingBefore = endingBefore
            self.expand = expand
            self.limit = limit
            self.startingAfter = startingAfter
            self.value = value
            self.valueList = valueList
        }
    }

    public typealias Response = Stripe.Page<Stripe.Fraud.ValueListItems.ValueListItem>
}

// GET /v1/radar/value_list_items/{item}
extension Stripe.Fraud.ValueListItems.ValueListItem.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        private enum CodingKeys: String, CodingKey {
            case expand
        }

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Fraud.ValueListItems.ValueListItem
}
