//
//  Billing/TestClocks/TestClock+Requests.swift
//  Stripe
//
//  Generated by Scripts/generate-requests.py from Stripe's OpenAPI spec (2026-07-29.dahlia).
//  Do not edit by hand.
//

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

extension Stripe.Billing.TestClocks.TestClock {
    public enum Advance {}
    public enum Create {}
    public enum Delete {}
    public enum List {}
    public enum Retrieve {}
}

// POST /v1/test_helpers/test_clocks/{test_clock}/advance
extension Stripe.Billing.TestClocks.TestClock.Advance {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// The time to advance the test clock.
        public var frozenTime: Date

        public init(
            expand: [String]? = nil,
            frozenTime: Date
        ) {
            self.expand = expand
            self.frozenTime = frozenTime
        }
    }

    public typealias Response = Stripe.Billing.TestClocks.TestClock
}

// POST /v1/test_helpers/test_clocks
extension Stripe.Billing.TestClocks.TestClock.Create {
    public struct Request: Codable, Hashable, Sendable {
        /// Existing customer this test clock will be attached to.
        public var customer: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// The initial frozen time for this test clock.
        public var frozenTime: Date
        /// The name for this test clock.
        public var name: String?

        public init(
            customer: String? = nil,
            expand: [String]? = nil,
            frozenTime: Date,
            name: String? = nil
        ) {
            self.customer = customer
            self.expand = expand
            self.frozenTime = frozenTime
            self.name = name
        }
    }

    public typealias Response = Stripe.Billing.TestClocks.TestClock
}

// DELETE /v1/test_helpers/test_clocks/{test_clock}
extension Stripe.Billing.TestClocks.TestClock.Delete {
    public typealias Response = DeletedObject<Stripe.Billing.TestClocks.TestClock>
}

// GET /v1/test_helpers/test_clocks
extension Stripe.Billing.TestClocks.TestClock.List {
    public struct Request: Codable, Hashable, Sendable {
        /// A cursor for use in pagination.
        public var endingBefore: String?
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?
        /// A limit on the number of objects to be returned.
        public var limit: Int?
        /// A cursor for use in pagination.
        public var startingAfter: String?

        public init(
            endingBefore: String? = nil,
            expand: [String]? = nil,
            limit: Int? = nil,
            startingAfter: String? = nil
        ) {
            self.endingBefore = endingBefore
            self.expand = expand
            self.limit = limit
            self.startingAfter = startingAfter
        }
    }

    public typealias Response = Stripe.Page<Stripe.Billing.TestClocks.TestClock>
}

// GET /v1/test_helpers/test_clocks/{test_clock}
extension Stripe.Billing.TestClocks.TestClock.Retrieve {
    public struct Request: Codable, Hashable, Sendable {
        /// Specifies which fields in the response should be expanded.
        public var expand: [String]?

        public init(
            expand: [String]? = nil
        ) {
            self.expand = expand
        }
    }

    public typealias Response = Stripe.Billing.TestClocks.TestClock
}
